### ISSUE TITLE
"This Duplicant got so good at their job that ..."

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#10]
「(that に続く仕事に)長けるようになった。」という意味合いらしいが、that に続く文章が

- they became claustrophobic (閉所恐怖症になった)
- they stopped being comfortable sleeping near other people (他人と近寄りすぎて快眠できなかった)
- they forgot how to be comfortable doing anything else (快適になる方法を忘れてしまった)

等のネガティブな文章なので、意味の通る文章にするのが難しい。

**Comment by seameteo** [comment]
「DUPLICANTS.MODIFIERS.*.CAUSE」におけるコンテキストなので、MODIFIERが付与された原因を表す文章のようです。
「この複製人間は(that)のような仕事環境に慣れてしまった」という意味合いになるでしょうか。それぞれに当てはめると
- 「この複製人間は閉所恐怖症になるような仕事環境に慣れてしまった」
- 「この複製人間は他人と寄りすぎて快眠できないような仕事環境に慣れてしまった」
- 「この複製人間は快適になることを忘れるような仕事環境に慣れてしまった」
という感じですね。（DUPLICANTS.MODIFIERS.*.CAUSEは共通で文末にピリオドなし）

余談(STRINGS.DUPLICANTS.MODIFIERS.PEOPLETOOCLOSEWHILESLEEPING.NAME)
「burst one's bubble」は「思い込みや夢を壊す」という意味があるようです。
1人で寝られない環境にうんざりしているという状態を表すので、直訳だと「ひとりになるという夢がない」でしょうか。

**Comment by nsk4762jp** [comment]
おー、なるほど、そういうことでしたか。それならしっくりきますね。

burst one's bubble は丁度いい単語がありますね。「幻滅」って。プルリク取り込んでおきますね。
