### ISSUE TITLE
「Wrangling」を「懐柔」と訳すのが違和感があるので修正したい

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#100]
タイトルの通りですが、英語の意味として懐柔ではなさそうなのと、日本語では動物相手に懐柔という言葉は使わないので別の言葉にした方が良いと思います。

「Wrangling」を辞書を引くかぎり、かなり意味不明です。ゲーム内での使われ方はメジャーな意味での使われ方ではないようです。
調べていくと、 wranglerという名詞から動詞化されたのが語源であるらしく日本語に無理やり訳すなら「カウボーイする」というニュアンスだと思われます。
ビジュアル的なイメージとしては輪になった縄をくるくると回して馬や牛の首に投げて捕らえる、いわゆる西部劇なイメージだです。

Minecraftなどのメジャーなゲームでは「Wrangling」という単語は使っていませんが、同様の作業のことを「手懐ける」と表現しているように思います。

以上のことから総合して

- Critter Wrangling → 動物手懐け
- Wrangle → 縄をかける
- Wrangling → 縄かけ中
- Capture Method: Wrangling → 捕獲方法: 縄をかける
- Cannot Wrangle → 縄かけ不可
- Wrangle tool → 縄かけツール
- Auto-Wrangle Surplus → 自動間引き

このように少し同じ単語でも幅のある翻訳をした方が良いのではないかと思います。全部「手懐け」でも良いのですが、パフのように縄では捕まらないけど、家畜化できる場合にどう表現するかが難しいので、縄をかけるという表現が良いのではと考えています。いかがでしょうか。検討お願いします。

**Comment by nsk4762jp** [comment]
この `Wrangling` もどう訳すか悩んだものの一つです。

> 英語の意味として懐柔ではなさそうなのと、日本語では動物相手に懐柔という言葉は使わない  

これも分かってて敢えてそうしたところがあります。
他の訳語と揃えるためにできれば熟語にしたいところですが、無理に揃える必要もないのかもしれません。

公式の言語パック(中国語)で `Wrangle` を見てみると `捕捉` とありました。これも案の一つとして挙げておきます。

**Comment by souki-tn** [comment]
`捕捉` は家畜に使うイメージは日本語ではないですね。 `捕捉` は敵対的な相手に使うものになりますね。
中国語でどう訳し分しているかは確認してみます。

**Comment by nsk4762jp** [comment]
> ビジュアル的なイメージとしては輪になった縄をくるくると回して馬や牛の首に投げて捕らえる、いわゆる西部劇なイメージだです。

このイメージからだと `Wrangle` を `投げ縄`、`Wrangling` を `縄投げ中` とも訳せそうですね(実際は縄でぐるぐる巻きにしてるだけですが...)。

**Comment by nsk4762jp** [comment]
だいぶ間が空いてしまいましたが、特に良い案も浮かばなかったので今回は @souki-tn さんの案を取り込もうと思います。
