### ISSUE TITLE
若干の翻訳案提示

### ISSUE THREAD

**Issue by HOP-katchan** [nsk4762jp/OxygenNotIncluded-Japanese#105]
1.データベースに表示される動物の`～～種`を`～～属`に。
理由）外見がわかりやすく異なっているため、ひとくくりとしてまとめるには、生物学上の定義からして、種ではなく属を用いる方が理にかなっているため。
2.データベースに表示される`装置`(equipment)を`装具`に。
理由）身につけるアイテムとしてわかりづらく、設備(buildings)と紛らわしい。equipmentの訳例に装具とあり意味として通るため。

**Comment by nsk4762jp** [comment]
ご指摘どうもありがとうございます。

指摘内容は尤もだと思うので、1. はそのまま採用、2. は他の訳語と揃えるために `装備` にしようと思います。

**Comment by HOP-katchan** [comment]
ありがとうございます。これからの翻訳作業も頑張ってください。

**Comment by HOP-katchan** [comment]
追加ですいません。データベースのヒップの記述の欄で「ヒップには～非常に器用**なな**足を～」となっている箇所がありましたのでそちらも修正お願いします。

**Comment by nsk4762jp** [comment]
ピップの説明も込みで取り込みが終わったので、この issue はクローズとします。
また何かあったらよろしくお願いします。
