### ISSUE TITLE
訳の統一など

### ISSUE THREAD

**Issue by HOP-katchan** [nsk4762jp/OxygenNotIncluded-Japanese#109]
1.素材レイヤ―の"鉱石"を"無機物原石"に。（金属鉱石は"金属"扱いのため）
→英語では"Ore"だが、無機物原石が表示される。わかりやすさを優先したほうがいいのではないかと考えたため。
2.データベース>index>レッスン 内の"Decor"が翻訳されていない

以下個人的に気になるため列挙。変更する必要性は薄いと思われます。
a. 気体（液体）用 輻射パイプ を 輻射型 気体（液体）用パイプ に。
→ 断熱型 気体（液体）用パイプ と同じようにした方が「気持ちがいい」から。
b. 固体フィルター を コンベアフィルター に。
→他は コンベア～～ となっているから。
c. 長音の有無の統一（ シグナルセレクタ , コンベアレセプタ ）
→他は センサー などのように最後に長音が付いているため。

**Comment by nsk4762jp** [comment]
@HOP-katchan さん

どうもありがとうございます。
1. については了解しました。中身を見てみます。
2. の「データベース>index>レッスン 内の"Decor"が翻訳されていない」ですが、どうも翻訳ファイル上に該当する箇所が無いみたいです。  
`データベース>Index>(カテゴリ名)` が指すところはどうも `STRINGS.CODEX.(カテゴリ名).TITLE` らしいのですが、Decor は何故かふさふさ スリックスターの説明になっています。(原文からしてそうなっています)

**Comment by nsk4762jp** [comment]
1. については 7ecb767502f9c2963fc9af03343ff00dbcaf0566 で対応しました。

**Comment by nsk4762jp** [comment]
2. a, c については 8199e65 で対応しました。  
2.b ですが、「〇〇フィルター」は〇〇を振り分けるものとして訳してあるので(例: 液体フィルター、気体フィルター)、ここは「固体フィルター」のままにしようと思います。
