### ISSUE TITLE
翻訳不具合

### ISSUE THREAD

**Issue by piyo-gh** [nsk4762jp/OxygenNotIncluded-Japanese#13]
![2017-05-26 23_11_52-oxygen not included](https://cloud.githubusercontent.com/assets/18474085/26517095/afd14a00-42cc-11e7-97a1-1b1c08b8c5d2.png)

style属性が一部原文と違うため、タグがそのまま出ているようです。
翻訳も、出力側と入力側のどちらのパイプが必要かがわかるほうがいいですね。
さらに欲を言えば、Output Pipe と Output Pipes の違いも翻訳でわかるとうれしいです。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po#L16226-L16254

**Comment by seameteo** [comment]
ソースを見てみたところ、曖昧一致による自動翻訳がそのままコンテキストになっていました。
該当部分を修正したものをコミットしました。

https://github.com/seameteo/OxygenNotIncluded-Japanese/tree/fix-pipe

**Comment by nsk4762jp** [comment]
取り込んでおきましたんでクローズとします。

**Comment by piyo-gh** [comment]
対応ありがとうございます。


さらにいくつか修正可能なものを見つけましたので、この課題を再利用させてください。
もし新しい課題を立てたほうがよければ、次回からそうします。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po#L8419-L8422

```
#. STRINGS.DUPLICANTS.STATUSITEMS.EMITTINGCO2.NAME
msgctxt "STRINGS.DUPLICANTS.STATUSITEMS.EMITTINGCO2.NAME"
msgid "Exhaling {EmittingRate} CO2"
msgstr "CO2 を {FlowRate} はき出している"
```

{FlowRate} は、{EmittingRate} が正しいです。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po#L13564-L13567

```
#. STRINGS.MISC.STATUSITEMS.OREMASS.TOOLTIP
msgctxt "STRINGS.MISC.STATUSITEMS.OREMASS.TOOLTIP"
msgid "The selected item has a mass of {Mass}"
msgstr "選択しているアイテムの質量は {0} です"
```

`{0}` は、`{Mass}` が正しいです。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po#L13574-L13577

```
#. STRINGS.MISC.STATUSITEMS.ORETEMP.TOOLTIP
msgctxt "STRINGS.MISC.STATUSITEMS.ORETEMP.TOOLTIP"
msgid "The selected item is currently {Temp}"
msgstr "選択しているアイテムの温度は {0} です"
```

`{0}` は、`{Temp}` が正しいです。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po#L16462-L16465

```
#. STRINGS.UI.BUILDINGEFFECTS.TOOLTIPS.REQUIRESPOWER
msgctxt "STRINGS.UI.BUILDINGEFFECTS.TOOLTIPS.REQUIRESPOWER"
msgid "Must be connected to a power grid with at least -{0} of available power"
msgstr "最低でも -{0] の電力が備わった回路に接続されている必要があります"
```

`{0]` は `{0}` が正しいです。

-----

あといくつか見つけたのですが、翻訳自体に問題がなさそうでしたので、おそらくプログラム側の不具合だと思います。
現在のところは以上です。

**Comment by nsk4762jp** [comment]
了解しました。
日本語化MODページのほうにも指摘が挙がってきているので、それと合わせて取り込んでおきます。

どうもありがとうございます。

**Comment by nsk4762jp** [comment]
取り込んだのでまたクローズします。
