### ISSUE TITLE
DLC仕様のロケット関連の訳語について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#137]
ロケット関連の翻訳を見直している中で、いくつか気になった単語があったので、変更案を考えてみました。
ここに並べますので、ご検討をお願いします。

- (Trailblazer Module)
「開拓者モジュール」 → 「先遣隊モジュール」
趣旨は以下の通りです。
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/discussions/116#discussioncomment-927634

- (Rover's Module)
「ローバーモジュール」 → 「探査機モジュール」 or 「探査ロボ モジュール」
参考: [探査車](https://ja.wikipedia.org/wiki/%E6%8E%A2%E6%9F%BB%E8%BB%8A)
日本人は、なかなかローバーという名称から宇宙探査機は思い浮かべられないと思います。
見た目は車というよりロボットなので、「探査機」あるいは「探査ロボ」。

- (Rover Bot)
「ローバーボット」 → 「探査機」 or 「探査ロボ」
上記に合わせて。

- (Trailblazer Lander) (Rover's Lander)
「開拓者ランダー」 → 「先遣隊 着陸船」
「ローバーランダー」 → 「探査機 着陸船」 or 「探査ロボ 着陸船」
参考: [着陸船](https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%B3%E3%83%80%E3%83%BC)
実際にゲームを遊んでいて、ランダーが何なのか、なかなか具体的にイメージできませんでした。
Trailblazer Moduleには降下用のTrailblazer Landerを積む必要があるので、モジュールを完成させた後、追加でLanderを建造する必要があるという仕様をなかなか理解できなかった。

- (Artifact)
「遺物」 → 「旧世界の遺物」
意訳ですが、「遺物」だけでは意味が広すぎる気がしたので。

- (Solo Spacefarer Nosecone)
「一人用宇宙旅行ノーズコーン」 → 「単独航宙用ノーズコーン」 or 「単独航行用ノーズコーン」
Seafarerが「海の旅人」なら、Spacefarerは「宇宙の旅人」
海が「航海」なら、宇宙は「航宙」になるはず…（？）。

- (Spacefarer Module)
「宇宙旅行モジュール」 → 「航宙用モジュール」 or 「航行用モジュール」
純粋な訳語としてなら元の訳で文句なしなのですが、「宇宙旅行」だと、どうしてもバニラの観光モジュールを連想してしまうので…。（実際は観光ではなく、宇宙空間で複製人間の居住空間となるモジュールです）
複製人間が乗り込むという点をもう少し強調したくて「居住（用）モジュール」という案も考えています。

- (Fitting)
「継ぎ手」 → 「端子」 or 「口」
具体的には「気体入力端子（気体入力口）」「コンベアレセプタ端子（コンベアレセプタ接続口）」などとなります。
訳としては継ぎ手で何の問題もないのですが、聞き慣れない名称だったため、なかなか機能を理解できませんでした。
実際は単に（ブリッジなどと同様）パイプの接続口でしかないので、敢えて存在感の薄い訳語を選んでいます。

- (Gantry)
「発射台」 → 「整備用足場」 or 「足場」
Spaced Out! で新たに "Rocket Platform"（ロケット発射台）が登場したので、混同を避けるためです。
Gantryには発射整備塔や構台といった訳語があるようですが、どう見てもゲーム上の形状とはかけ離れているので、意訳です。
**（追記）**
さらに調べたら、鉄道用語が由来のようです。
参考: [ガントリー](https://kotobank.jp/word/%E3%82%AC%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC-238173)、[ガントリーシグナル](https://www.canstockphoto.jp/%E3%82%B7%E3%82%B0%E3%83%8A%E3%83%AB-%E3%82%AC%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC-4696844.html)
ゲーム内の形状と使われ方を見ると「高架橋」や「可動橋」という意訳も捨てがたい気がします。
**（追記おわり）**

ひとまず以上です。
案が複数ある場合、先に書いてあるほうが推しです。
よろしくお願いします。

**Comment by nsk4762jp** [comment]
翻訳するのが難しかった箇所に色々と案を頂き、どうもありがとうございます。
翻訳しているときは設備のグラフィックスがどんなものか全く確認できていないので、訳語としては正しいけれど見た目とのミスマッチが発生することが多々あります。
そういう時に実際触ってみた人からのフィードバックはとても助かります。

下記一覧はそのまま採用しても良いと思います。

`Trailblazer Module` → `先遣隊モジュール`
`Rover's Module` → `探査ロボモジュール`
`Rover Bot` → `探査ロボ`
`Trailblazer Lander` → `先遣隊着陸船`
`Rover's Lander` → `探査ロボ着陸船`
`Artifact` → `旧世界の遺物`
`Fitting` → `端子`
`Gantry` → `整備用足場`

**Comment by nsk4762jp** [comment]
`Solo Spacefarer Nosecone`, `Spacefarer Module` の訳語について  

「航宙」でぐぐると小説のタイトルがヒットする程度で、あんまり馴染みがないみたいですね。  
`単独航行用ノーズコーン`、`航行用モジュール` にしましょうか。

**Comment by denev-rove** [comment]
検討ありがとうございます。
同意が得られた語句について、修正したいと思います。

ここで聞いていいのか分かりませんが、可読性に配慮して、固有名詞に半角スペースを含めることは差し支えないでしょうか。（`ぷすぷす モー`のように）
具体的には`探査ロボ モジュール`などのように、カタカナや漢字が何文字も続く場合に、単語の区切りを分かりやすくしたいと思っています。

**Comment by nsk4762jp** [comment]
その辺もルール決めしてないので半角スペースがあったりなかったりしますね。短い名前に半角スペース入れると却ってヘンですし。
名称が長すぎる場合は適宜半角スペース入れて頂いて構いません。

**Comment by denev-rove** [comment]
> 「航宙」でぐぐると小説のタイトルがヒットする程度で、あんまり馴染みがないみたいですね。

無難に`航行用`にしたいと思います。

`航宙`の単語は、まだ一般には浸透していない、主に創作の分野で（たまに）使われる造語といった感じですね。
人類の`宇宙進出！`が一般的になった未来には、市民権を得ていると期待します。

**Comment by denev-rove** [comment]
> 名称が長すぎる場合は適宜半角スペース入れて頂いて構いません。

ありがとうございます。
なるべく長い名前自体を避けるように工夫しているのですが、複合語などは（語意を省略したくないため）どうしても長くならざるを得なくて…。

1. なるべく長い名前を避ける
2. どうしても長くて見づらい場合には半角スペースを入れる

という優先順位で考えたいと思います。

**Comment by nsk4762jp** [comment]
#136, #137 の結果を取り込みました。
とりあえずこれで一旦リリースして、他の issue はその後で不定期更新しようと思います。

**Comment by nsk4762jp** [comment]
リリースしたのでこの issue はクローズします。
