### ISSUE TITLE
間欠泉の訳語について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#138]
間欠泉の名称について、変更案を考えてみました。

逐語訳からは離れますが、ゲームを遊びながら、いちいち攻略サイトやゲーム内ヘルプを開いて確認しなければならないことにストレスを感じたためです。
原則として、名称を見るだけで間欠泉の機能を読み取れるような形式（［噴出物の持つ性質］ ＋ 噴出物の名称 ＋ 本体の名称）にしています。

意訳が行き過ぎていると判断される場合を考えて、あくまで原語を尊重する方針の訳（直訳）も併記しています。

また、ものによっては漢字が何文字も続くような名称もあるため、既存の動物名などに倣って、適宜間に空白を入れています。

原語|噴出物|現行訳|変更案1<br>(直訳)|変更案2<br>(意訳)
--|--|--|--|--
Water Geyser|水 (95℃)|間欠泉|（現行どおり）|**熱水** 間欠泉
Cool Steam Vent|蒸気 (110℃)|蒸気噴出口|**低温** 蒸気 噴出**孔**|蒸気 噴出**孔**
Steam Vent|蒸気 (500℃)|蒸気噴出口|蒸気 噴出**孔**|**高温** 蒸気 噴出**孔**
Polluted Water Vent|汚染水 (30℃)<br>**(食中毒菌)**|汚染水 噴出口|汚染水 噴出**孔**|**食中毒** 汚染水 噴出**孔**
Cool Slush Geyser|汚染水(-10℃)|雪氷間欠泉|冷雪 間欠泉|**低温 汚染水** 間欠泉
Salt Water Geyser|塩水 (95℃)|塩水間欠泉|塩水 間欠泉|-
Cool Salt Slush Geyser|濃塩水(-10℃)|冷塩雪間欠泉|（現行どおり）|**低温 濃塩水** 間欠泉
Infectious Polluted Oxygen Vent|汚染酸素 (60℃)<br>**(腐肺病菌)**|汚染酸素噴出口|**病原** 汚染酸素 噴出**孔**|-
Hot Polluted Oxygen Vent|汚染酸素 (500℃)|高熱汚染酸素噴出口|高**温** 汚染酸素 噴出**孔**|-
||||
Leaky Oil Fissure|原油|オイル噴出口|原油 **漏出**孔|-
||||
Minor Volcano|マグマ|ミニ火山|**小**火山|-

（意訳の補足）
- Water Geyser（熱水 間欠泉）
[熱水噴出孔](https://ja.wikipedia.org/wiki/%E7%86%B1%E6%B0%B4%E5%99%B4%E5%87%BA%E5%AD%94)
- Cool Steam Vent, Steam Vent（蒸気 噴出孔、高温 蒸気 噴出孔）
通常のSteam Vent(500℃)と比較して低温という意味で"cool"なのだと思いますが、ほかのCool Geyserが氷点下なので、混乱を避けるため、Steam Ventのほうに**高温**と冠して、こちらを単なる蒸気噴出孔としました。
- Polluted Water Vent（食中毒 汚染水 噴出孔）
原語には修飾が存在しませんが、食中毒菌が含まれていることを明示するため、**食中毒**と冠しています。
- Cool Slush Geyser（低温 汚染水 間欠泉）, Cool Salt Slush Geyser（低温 濃塩水 間欠泉）
"slush"の語意が完全に消えていますが、もともと訳すのに苦労する単語であること、ゲームシステムと連動していない単語であること等を考えると、やむを得ないと考えます。

（直訳の補足）
- Cool Slush Geyser
直訳案は、Cool *Salt* Slush Geyserの現行訳（冷塩雪間欠泉）から「塩」の一文字を消して「冷雪間欠泉」にしています。
- Hot Polluted Oxygen Vent
Cool / Hot の対比を訳す場合、低温 / 高温 としたほうが座りがいいので、高熱ではなく高*温*としています。
- Leaky Oil Fissure
"Leaky Fissure"で「漏出孔」と訳しています。（実際、噴き出るというより漏れ出ると呼んだほうがふさわしいほどの産油量です）
本当は"Fissure"（裂け目）も訳したかったのですが、しっくりくる訳が見つかりませんでした。
また、自然に湧き出るOilなら原油と言い切ってしまって問題ないと思うので、原油としています。

以上、ご検討をよろしくお願いします。

**Comment by nsk4762jp** [comment]
`噴出口` と `噴出孔` は同じだと思ってましたが、チムニーを形成するほうは `噴出孔` なんですね。

- #####  `Cool Steam Vent` / `Steam Vent`  

熱量の高い蒸気のことを [過熱蒸気](https://kotobank.jp/word/%E9%81%8E%E7%86%B1%E8%92%B8%E6%B0%97-465405) というらしいです。  
こちらについては変更案２のほうの `蒸気噴出孔` / `過熱蒸気噴出孔` にしたいと思います。


- ##### `Polluted Water Vent`  
 
`食中毒 汚染水 噴出孔` はちょっと機能的すぎるのと、発見の楽しみをスポイルしそうなので、`汚染水 噴出孔` までにしたいです。
`病原 汚染酸素 噴出孔` も同様ですね。


- ##### `Cool Slush Geyser` / `Cool Salt Slush Geyser`

`Slush` は `雪解けの水` を指すということで `雪氷` と訳していましたが、凍ってる訳でもないので [`雪水`](https://kotobank.jp/word/%E9%9B%AA%E6%B0%B4-651673) を取って `雪水間欠泉` に、`Cool Salt Slush Geyser` は `雪塩水間欠泉` あたりでどうでしょうか。

**Comment by denev-rove** [comment]
- `Cool Steam Vent` / `Steam Vent`
`過熱蒸気`という表現は、500℃の蒸気がゲームに与えるインパクトをよく表していて、とてもいいと思います。

- `Polluted Water Vent`
`汚染水 噴出孔`については、原語表記を尊重するということで了解です。

- `Cool Slush Geyser` / `Cool Salt Slush Geyser`
`雪水`という単語はあまり一般的ではない気もしますが、`Slush`の語意を残す前提なら妥当な訳語だと思います。初見でも冷たい液体が出てくるんだなと素直に理解できる気がします。

- `Infectious Polluted Oxygen Vent`
`病原汚染酸素 噴出孔`については、原語名からして`Infectious Polluted Oxygen Vent`なので、敢えて`Infectious`を省く必要はないと思うのですが、どうでしょうか。

- 半角スペースについて
改めて見てみると、半角スペースを2つも入れるのは確かに機能的すぎるかなと感じました。
長い場合に噴出物名と本体名の間にひとつ入れるくらいで十分でしょうか。

そのほか、ここで言及されていない提案についてはいかがでしょう。
提案どおりで問題なければ、指示していただければ私の方で作業に取り掛かります。
nskさんのほうで作業する方針なら、お任せします。

以上よろしくお願いします。

**Comment by nsk4762jp** [comment]
先のコメントで言及されてない箇所についてはOKだと思います。
この issue の分量だったらこちらで取り込んでも良いかなと思ってます。

**Comment by nsk4762jp** [comment]
セルフチェックリスト

- [ ] Water Geyser 熱水間欠泉
- [ ] Cool Steam Vent 蒸気噴出孔
- [ ] Steam Vent 過熱蒸気噴出孔
- [ ] Polluted Water Vent 汚染水噴出孔
- [ ] Cool Slush Geyser 雪水間欠泉
- [ ] Salt Water Geyser 塩水間欠泉
- [ ] Cool Salt Slush Geyser 雪塩水間欠泉
- [ ] Infectious Polluted Oxygen Vent 病原汚染酸素噴出孔
- [ ] Hot Polluted Oxygen Vent 高温汚染酸素噴出孔
- [ ] Leaky Oil Fissure 原油漏出孔
- [ ] Minor Volcano 小火山

**Comment by nsk4762jp** [comment]
コミットしたのでクローズします。
