### ISSUE TITLE
Thermo Regulatorの訳語について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#139]
Thermo Regulator（空調設備）とThermo Aquatuner（液体クーラー）の訳について提案させていただきます。

原語|現行訳|変更案1|変更案2|変更案3
--|--|:--:|:--:|--
Thermo Regulator<br>（直訳：温度調節器）|空調設備|空冷装置<br>or<br>空冷設備|気体冷却機<br>or<br>気体冷却装置|気体クーラー
Thermo Aquatuner<br>（直訳：液温調節器…といった感じでしょうか）|液体クーラー|液冷装置<br>or<br>液冷設備|液体冷却機<br>or<br>液体冷却装置|液体クーラー

Thermo Regulatorは、見た目も機能もエアコンの室外機そのもので、空調設備というのは自然な意訳だと思います。
一方で、単に空調設備と言った場合、（我々利用者の立場からは）室外機よりも室内機の機能に主眼を置くことが多いように思います。

空冷/液冷と言った場合、自動車のエンジンやCPUなどの冷却機構として馴染み深く、（対象から奪った熱を放熱することまで含めて）直感的にこの設備の全体像を思い浮かべることができると思います。

変更案を3つ挙げてありますが、原語に倣って、いずれも両者の名称に対応関係があるようにしています。

以上ご検討をお願いします。

**Comment by nsk4762jp** [comment]
`空調設備`は割と初期の段階(Thermal Update)からある設備で、`液体クーラー`はその後追加された設備なので、似たような原文でも訳語があんまり統一されてませんね。
空調は冷暖房を含むので、冷房のみに特化しているのであれば`気体クーラー`が良いと思います。
似たような設備で`空間ヒーター`、`液体ヒーター`がありますしね。

**Comment by denev-rove** [comment]
あー、`ヒーター`の存在をすっかり失念していました。

`ヒーター`は現実にある暖房器具と同じく、周囲の環境を温めるというプレイヤーにも理解しやすい機能をしていると思います。
ここで`ヒーター`⇔`クーラー`という対応関係を作り出してしまうと、`クーラー`も**周囲の環境を**冷やす設備だと誤解を生んでしまうのではないかと危惧します。（実際は、ヒーターと同じく周囲の環境を温める効果を持っているのに）
自分で変更案として挙げておきながら、申し訳ありません。

プレイヤーに誤解を与えない（ヒーターとは系統が異なる設備だと理解してもらう）ための名称を色々と考えてみましたが、`熱交換器`が設備の効果を正確に表現しているのではないかと思います。
`Thermo Regulator` → `空冷式 熱交換器`
`Thermo Aquatuner` → `液冷式 熱交換器`
いわゆる熱破壊を行う設備ではなく、交換した熱を捨てる先が必要になる設備だということが伝わりやすいと思います。

余談ですが、ゲームと同じように冷媒を介して熱を移動させる冷却システムは現実にも存在していて、様々な名称で呼ばれているようです。
参考: [チラー](https://ja.wikipedia.org/wiki/%E3%83%81%E3%83%A9%E3%83%BC)

**Comment by nsk4762jp** [comment]
なるほど。
冷却装置は外界に対してじゃなくて入力に対してだから、クーラーという単語はあまり正しい意味じゃないんですね。  
たしか液体クーラーは水没してなくても動作するんですよね(お勧めはできませんが)。

変更案２の「気体冷却機」「液体冷却機」が「何を」「どうしてくれる」かが一目瞭然なので良いかなと思います。

**Comment by nsk4762jp** [comment]
dc6db432e3f9bbaecbec5ae9518cc2ca274f6c9c で取り込んだので、クローズとします。
