### ISSUE TITLE
植物名の翻訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#140]
全体的に植物の名称を見直してみました。
なるべく名前を見ただけで、植物の特性やゲーム内における位置付けなどを類推できるようにという方向性で訳しています。

固有名詞や品種名に関しては、日本語に訳すか、そのままカタカナ語にしてしまうかは好みが分かれるところだと思いますので、そのあたりの匙加減について意見があればお聞きしたいです。

植物名<br>（収穫物名）|現行訳|変更案1|変更案2|種子
--|--|--|--|--
Balm Lily<br>(Balm Lily Flower)|バームリリー<br>（バームリリーの花）|**ジャコウユリ**|**芳香ユリ**|Balm Lily Seed
Dusk Cap<br>(Mushroom)|ダスクキャップ<br>（キノコ）|**夕闇茸**|**夕闇ダケ**|Fungal Spore
Gas Grass|浮き草|**ぷすぷす**草||-
Mirth Leaf|マース リーフ|**にぎやか葉**||Mirth Leaf Seed
Nosh Sprout<br>(Nosh Bean)|ノッシュの木<br>（ノッシュ豆）|ノッシュ**もやし**<br>（ノッシュ豆）|ノッシュの**新芽**|Nosh Bean
Oxyfern|オキシファーン|**酸素シダ**||Oxyfern Seed
Pincha Pepper<br>(Pincha Peppernut)|ピンチャ ペッパー<br>（ピンチャペッパー）|**逆立ち胡椒**<br>（**逆立ち胡椒の実**）||Pincha Pepper Seed
Sleet Wheat<br>(Sleet Wheat Grain)|スリート ウィート<br>（スリート ウィートの穀粒）|**みぞれ麦**<br>（**みぞれ麦**の**種籾**）||Sleet Wheat Grain
Swamp Chard|ヌマビーツ|**沼**ビーツ||-
Thimble Reed<br>(Reed Fiber)|シンブル リード<br>（リード繊維）|**ウツギ葦**<br>（**葦の繊維**）||Thimble Reed Seed

- `Balm Lily`
`バームリリー` → `ジャコウユリ`
「ジャコウ（麝香）」は「香りの強い」という程度の意味で使っています。
参考: [タチジャコウソウ](https://ja.wikipedia.org/wiki/%E3%82%BF%E3%83%81%E3%82%B8%E3%83%A3%E3%82%B3%E3%82%A6%E3%82%BD%E3%82%A6)（ハーブの一種）
参考: [レモンバーム](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%A2%E3%83%B3%E3%83%90%E3%83%BC%E3%83%A0)（同じくハーブの一種）
ちなみに中文版では「芳香百合」となっていました。

- `Dusk Cap`
`ダスクキャップ` → `夕闇茸`
暗闇でしか育たない作物なので、`闇`の字を入れています。

- `Gas Grass`
`浮き草` → `ぷすぷす草`
`Gassy Moo`（`ぷすぷすモー`）と関わりが深い植物なので。

- `Nosh Sprout`
`ノッシュの木` → `ノッシュもやし`
厳密には（ゲーム内では、新芽ではなく発芽前の豆を加工して食べているため）`もやし`ではありませんが、`Sprout`の語感を端的に表す言葉として採用しています。
ゲーム内のグラフィックでは豆が鈴なりに実っている（成熟している）ため、新芽でもなんでもないはずですが、そこまで厳密に考えても仕方ないということなのでしょう。

- `Oxyfern`
`オキシファーン` → `酸素シダ`
直訳で問題ないのではないかと思います。あとは好みの問題でしょうか。

- `Pincha Pepper`
`ピンチャ ペッパー` → `逆立ち胡椒`
参考: [Pincha Mayurasana](https://www.google.com/search?q=%E5%AD%94%E9%9B%80%E3%81%AE%E7%BE%BD%E3%81%AE%E3%83%9D%E3%83%BC%E3%82%BA&lr=lang_ja)
かなり回りくどい表現ですが、名前の由来はこれなのではないかと思います。
`逆立ちコショウ`とカタカナでもいいかもしれません。

- `Sleet Wheat`
`スリート ウィート` → `みぞれ麦`
見た目やゲーム内の挙動に照らしても、直訳で特に問題がないのではないかと思います。
`穀粒`という単語は、`grain`に対して過不足のない優れた訳語と思いますが、同時に、主に農業の世界で使われている一般に馴染みの薄い単語のようにも感じるので、個人的には`種籾`（`種もみ`）という意訳を推します。

- `Swamp Chard`
`ヌマビーツ` → `沼ビーツ`
標準和名はカタカナで表記するという、現代の慣例に従った訳だと推察します。
一方で、`ヌマ`というカタカナ表記は、そのまま沼の意味なのか、ある種の[固有名詞](https://ja.wikipedia.org/wiki/%E3%83%8C%E3%83%9E%E3%83%BB%E3%83%9D%E3%83%B3%E3%83%94%E3%83%AA%E3%82%A6%E3%82%B9)なのか、判断しづらいと感じました。
`ビーツ`という外来語を含んでいることから、標準和名ではなく、あくまで慣用名という位置づけで、`沼ビーツ`としたほうが意味を汲みやすいと思います。

- `Thimble Reed`
`シンブル リード` → `ウツギ葦`
たとえば[thimbleberry](https://en.wikipedia.org/wiki/Rubus_parviflorus)という植物の名前は、果実が[指ぬき](https://ja.wikipedia.org/wiki/%E6%8C%87%E8%B2%AB_(%E8%A3%81%E7%B8%AB%E9%81%93%E5%85%B7))([thimble](https://en.wikipedia.org/wiki/Thimble))のように中空であることに由来しているようです。
和名が[ウツギ](https://ja.wikipedia.org/wiki/%E3%82%A6%E3%83%84%E3%82%AE)（空木）という植物も同様の由来のようなので、Thimbleの訳語として採用してみました。
`葦`を漢字にしているのは、これが植物の名前であるということを、文脈に頼らず名称のみで誤解なく伝えるためです。標準和名の慣例を優先するなら`ウツギアシ`になると思います。
　
問題は収穫物である`リード繊維`です。直訳なら`葦の繊維`、意訳なら`植物繊維`を候補に考えていましたが、これはドレッコの体毛からも採集できる資源なので、それを考えると少し違和感があります。
元のゲームにも存在する違和感なので、一覧表には違和感を無視する前提で`葦の繊維`を記載していますが、どうしても気になる場合は、カタカナ語の意味の曖昧さを逆手に取って`リード繊維`のままにしておく選択もあるかなと思います。

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

固有名詞はこのリポジトリの wiki にある翻訳ポリシー: 

- 訳語が存在しない場合、(1)そのまま発音をカタカナ訳するか、(2)単語を構成する要素名から新たに造語する。

に毎回引っ掛かるので、大抵はカタカナ訳にしています(カタカナ訳にしたときに宇宙語になってしまうようなものは造語しています)。
カタカナ訳を取り入れているのは、

- 原語の言葉遊び(韻を踏んでいる等)をできるだけ残したい
- 英語版で遊んでる人と話が通じるようにしたい

という割とふんわりとした理由からです。  
とはいえ長いこと翻訳作業してると結構逸脱してたりすることもあるので、どこかのタイミングで全般的に見直す必要があるかもしれません。  

定着した名前を変えるのは(元々の名前が原文からかけ離れていない限り)、「うーん」と言う感じがします。

**Comment by denev-rove** [comment]
定着した名前を変えるリスクは理解できます。
今回の提案は、とりあえずリスクは置いて、（第三者の感覚に照らして取捨選択してもらう前提で）ひとまず訳せそうなものを全て洗い出した結果です。

私の中にも温度差があり、とりあえず訳してみたものから、ぜひとも変えてほしいものまであります。

特に変えてほしいと思っているものが、`Sleet Wheat`です。
小麦という、日本人にも非常に馴染みのある作物なので、訳すことに差し支えはないと思います。
「小麦」も"Wheat"も、どちらも日常的に触れる機会の多い単語ですが、カタカナで「ウィート」と書かれることは稀なので（少なくとも私は）それが小麦のことだとはなかなか気付けませんでした。（翻訳ファイルを見て初めて膝を打った）

2つ目の理由が、ウィーズ「ウォート」と非常に紛らわしいという点です。
どちらも温度の低い印象のある植物（？）なので、よけいにそう感じます。

次に、できれば変えたほうがいいと思っているものが、Pincha Pepper**nut**（ピンチャ ペッパー**の実**）です。
（これは固有名詞の問題ではなく、単に翻訳の正確性の問題ですが。）

その次に、少し違和感を感じているのがGas Grassです。

このような優先順位です。

**Comment by nsk4762jp** [comment]
ありがとうございます。

確かに似たような響きでなんだかな、ってところがあります。
冷たい感じを出しつつ言葉遊びした訳となると、`雪ん子麦` (雪ん子 + 小麦) みたいなのが思い付きました。

`Gass Grass` は苦し紛れの意訳なので違和感を感じるのは当然だと思います。  
浮き草というと普通水面に浮いてるヤツを想像しますよね。
浮き草自体は「ぷすぷす」しないので、「ぷかぷか草」とかはどうでしょうか。

**Comment by denev-rove** [comment]
`雪ん子麦`！とてもいいと思います！
字面はいっそ`雪ん小麦`にしてしまってもいいと思いますが（大麦でもライ麦でもなく小麦だとハッキリするので）、いずれにせよ翻訳の妙を感じる名訳だと思います。

`Gas Grass`も、言われてみれば確かに直接ガスを発するわけではないですね。
`ぷすぷす`と`ぷかぷか`なら、それぞれの体を表す名になっている上、'**Gassy** Moo' と '**Gas** Grass' という原語の韻も踏襲していて、これまた名訳だと思います！

**Comment by nsk4762jp** [comment]
既存の植物については当面そのままで行くことにしたので、この issue は一旦クローズとします。
