### ISSUE TITLE
Maeの日本語訳について

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#160]
人名でMaeというのは珍しいのですが、一応ネット上にも資料がありました。

https://kanji.reader.bz/Mae

そちらだと「メイ」さんなんですよね。「ミー」さんではないのですよ。
今更変えられるかというところもありますが、変えませんか？

ムービーなどでも主役を張っていますし、主要キャラですから難しいかもしれませんが、だからこそ誤訳は微妙かなとも。

**Comment by souki-tn** [comment]
DLCでも発売されたようなタイミングでないと変えられないだろうということで出しました。

**Comment by nsk4762jp** [comment]
どうもです。

[Mae (given name)](https://en.m.wikipedia.org/wiki/Mae_(given_name)) 
> It is a variant of May,

ということで「メイ」ですねえ。

**Comment by souki-tn** [comment]
ハリウッドの女優さんの名前とかでもボチボチヒットしますね。
そっちも日本語訳は「メイ」で統一されているようです。
問題は変えるか変えないかですね。

**Comment by nsk4762jp** [comment]
人名は特に拘りがあって訳したところもないので「メイ」に直しましょう。
