### ISSUE TITLE
複製人間の"Attributes"の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#164]
非常に基本的なことで恐縮ですが、複製人間の"Attributes"の訳についてです。

現在は「属性（値）」と訳されていますが、ゲーム用語としては、いわゆる「能力（値）」を表す言葉として使われることが多いようです。ファンタジーRPGで言えば、力とか素早さとか魅力とかです。（TRPGのD&Dにまでその起源を遡れるらしい？）
https://en.wikipedia.org/wiki/Attribute_(role-playing_games)
https://ja.wikipedia.org/wiki/%E8%83%BD%E5%8A%9B%E5%80%A4
このゲームも例に漏れず、複製人間の能力が数値の大小で表され、それを"Attributes"と呼んでいます。

個人的な感覚かもしれませんが、ゲーム用語として「属性」と聞くと、強弱ではなく（火属性とか水属性のような）種類や所属の違いを表す言葉という印象があります。能力（値）としたほうが、ゲームに慣れている人ほど素直にシステムを理解しやすいと思うのですが、いかがでしょうか。

よろしくご検討ください。

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

確かに「属性」でイメージするのは数値ではなくて「種類や所属」ですね。
「属性上昇」だとあまりしっくりこないなあとモヤモヤしてたのが「能力上昇」だとぴったりな気がします。

`Attribute` は `能力` に変更しましょう。

**Comment by nsk4762jp** [comment]
#165 でプルリクを作成しました。
