### ISSUE TITLE
データベースの項目名にある"Notes"の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#169]
ゲーム中に開けるデータベースの項目名の幾つかに、表記ゆれがあるようです。
原文|現行訳
-- | --
Director's Notes|所長のノート
Research Notes|研究の通知
Husbandry Notes|畜産ノート
Agricultural Notes|農業メモ
Byproduct Notes|副産物に関するメモ

統一するなら「ノート」か「メモ」になるでしょうか。
どれも体系的な情報ではなく、個人的な手記や、研究や実験の現場における生の音声記録なので、どちらかといえば「メモ」のほうが臨場感があっていいかもしれません。

**Comment by denev-rove** [comment]
おー、できました。ありがとうございます。

**Comment by nsk4762jp** [comment]
確かに「ノート」だと冊子をイメージするので、ページの寄せ集めであるならば「メモ」が良さそうです。

**Comment by nsk4762jp** [comment]
取り込みましたのでクローズとします。
