### ISSUE TITLE
Roverの訳語について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#178]
`Rover`の訳語についての提案です。
現行訳である`探査ロボ`は確か私が提案したものだった気がするので、今更この話をするのは非常に気が引けるのですが…。

テキストの中で、`Rover Bot`という用例を見つけてしまいました。
`Rover`が遠隔式なのか自律式なのか厳密には不明ですが、小惑星に降り立った`Rover`が健気に探査している姿を見ると、まさに`ボット`（事前に決められたアルゴリズムに従って自動的に行動するプログラム）と呼ぶにふさわしい存在に感じられます。

そういうわけで、`探査ボット`という訳語のほうが、より良いような気がしてきました。

既存のゲーム内用語を変更することになるので慎重に判断すべきですが、検討をよろしくお願いします。

**Comment by nsk4762jp** [comment]
`Rover Bot` で使われている箇所は一か所だけなので、ここはこのままでもいいんじゃないかなって気がします。

**Comment by denev-rove** [comment]
了解しました。
