### ISSUE TITLE
「建築」と「建設」の違い

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#182]
`Building` を `建設` と訳しているが、建築と建設の違いについて調べてみたところ以下の情報が得られた。

[「建設」と「建築」の違いについて](https://kensetsu-gate.com/archives/1105)

> 「建設」は、私たちの生活の向上や利便性を図ったり、広範囲にわたって「大きな構築物を建てる」という意味合いを持っています。
> それに対して「建築」は、私たちの生活で身近なもの（家・マンション・ビル）を造る分野として使われます。
> まとめると、「建設」は「建築」を含む大きなカテゴリーであり、「建設」の中に「建築」という分類があるということですね。

コロニーは「建設」するもので、コロニー内の設備は「建築」するものであるらしい。
あとで見直す。

**Comment by denev-rove** [comment]
建築と建設の違いは、言葉を扱う作業に従事した人なら一度は考えたことのあるテーマだと思います。
もちろん私もです。

私の場合は、`建築` も `建設`も、実質的には同義語であるとの結論に達しました。
わずかに慣例的な用法の違いがあるものの、それらは殆ど全て相互に入れ替え可能だからです。

建築と建設の違いはなんだろう？と突き詰めれば、なにかしら慣例的な違いは見いだせるけども、日本語としてそれらを（意味の違うものとして）使い分けている人も、使い分けなければならない状況も、実際は殆ど存在しないと思います。
（ぶっちゃけ建築業界の人も、そんなに使い分けしてないんじゃないでしょうか。建設業界、建築業界、全く同じ意味に聞こえます）

ともあれ、両者が混在している状況は美しくないので、用法を統一するのは素晴らしいことだと思います。私も今後は`Build(ing)`の定訳を`建築`として見直しを進めます。

ちなみに英語では、`Building` と `Construction` の関係がこれに近いと思います。
このゲームにおいては、`Build(ing)`が設備を作るのに汎く使われている一般的な用語、`Construction` が特に複製人間の能力値を表す名称、という使い分けがなされているようです。

実は作業名と職業名が一段落してから提案するつもりだったのですが、`Building`（作業名）を `建設`、`Construction`（能力値名）を `建築` とするような案を考えていました。作業と能力値は、ゲームシステム上では別の概念なのだと明確にするためです。
（同様に`Farming`（作業名）を`農業`、`Agriculture`（能力値名）を`農耕`に）
（同様に`Cooking`（作業名）を`料理`、`Cuisine`（能力値名）を`調理`に）
（同様に`Digging`（作業名）を`採掘`、`Excavation`（能力値名）を`掘削`に）
