### ISSUE TITLE
Pickled Meal の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#187]
現行訳は`ピクルス`となっていますが、確か`Meal`（食事）の部分は訳すまでもないだろうということで省略されていたかと思います。
ただこのゲームにおいて`Meal`は、`Mealwood`や`Meal Lice`のように、半ば固有名詞（植物の品種名）として扱われている単語でもあります。
`Pickled Meal`についても、原義としては「酢漬けの食事」というよりは「酢漬けにしたミール」つまり`ミールの酢漬け`といったほうが近いと思います。
ゲームシステム上も、`Pickled Meal`は`Mealwood`から収穫できる`Meal Lice`を材料にした食事なのだとすぐに理解できるため、`ミール`の語は残したほうが都合がいいと思いますが、どうでしょうか。

**Comment by nsk4762jp** [comment]
`Pickled Meal` は日本で言うところの漬物だと思ったのでそのまま `ピクルス` としていました。

[Pickled の例文](https://ejje.weblio.jp/content/pickled) を見ると `pickled ~` で `~漬け` と訳しているので、`ミール` の語感を残したいのであれば `ミール漬け` になるのかなと思います。

**Comment by denev-rove** [comment]
`ミール漬け` いいと思います！わさび漬け、らっきょう漬け、`ミール漬け`。

日本語でピクルスというと一般に酢漬けが連想されるのと、ゲーム内の説明で酢に漬けたと説明があったので`酢漬け`としましたが、`ミール漬け`のほうが簡潔で良いと思います。

**Comment by nsk4762jp** [comment]
取り込んだのでクローズとします。
