### ISSUE TITLE
EXOスーツまわりの訳語について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#189]
- `Store Equipment` `装備品の格納`

EXOスーツを、スーツの配達を求めているドックへ取り付けるときの作業名です。(STRINGS.DUPLICANTS.CHORES.EQUIPMENTFETCH.NAME)
作業内容としては、建材の配達を待っている建設場所へ建材を運んだり、調理指示した調理器具へ食材を運んだりするのと同列になります。つまり作業種別としては`Supplying`(`配達`)に分類されます。

しかし、このゲームで`格納`と言った場合、どちらかと言えば床に散らばった`がれき`などを`格納庫`へ片付ける作業を指します。（作業種別`Storing`(`格納`)ですね）
これは**原文がそうなってる**（どちらも`Store`という単語を使っている）せいなんですが、非常に紛らわしい、プレイヤーがゲームシステムを把握する上で、極めて大きな混乱の要因になるものだと思います。ただでさえ`清掃` `配達` `格納`の作業種別は内容が似ているというのに。

そこで提案なのですが、`装備品の格納`と区別するため、作業種別`格納`を`収納`と改めるのはどうでしょうか。
というのも、格納と収納という単語を比較した場合、`格納`は比較的重々しい物に対して使われ（飛行機の格納庫、武器弾薬の格納庫など）、`収納`は我々の日常生活に身近な整理整頓に使われることが多いからです。
がれきの片付けは、`収納`のほうが意味が通りやすいように感じます。（`Storage Bin`も`収納庫`のほうが実態に近い感じがする）
（逆に、ロケットの貨物庫など大きなものは`格納`のほうが相応しい感じがする）

これを修正するとなると、作業がかなり広範囲に亘ることが難点ですが、私としてはこれが最も良い案だと考えています。
（修正に賛同いただける場合は、修正作業を私が行う（その後nskさんにレビューしてもらう）形も考えています）

次善の案として、`装備品の格納`を作業種別に合わせて`装備品の配達`とする方法もあると思います。
これなら修正範囲は一部だけで済みます。

よろしくご検討ください。

- `Checkpoint` `チェックポイント`

`アトモスーツ チェックポイント`、`複製人間チェックポイント` などに共通した訳語です。
設備の機能はどれも同じ（複製人間の通行を制限する）であるため、`検問所`と訳するのはどうでしょうか。
何をチェックする設備なのか、より機能が明確になると思います。

**Comment by nsk4762jp** [comment]
> というのも、格納と収納という単語を比較した場合、格納は比較的重々しい物に対して使われ（飛行機の格納庫、武器弾薬の格納庫など）、収納は我々の日常生活に身近な整理整頓に使われることが多いからです。

確かにそうですね。`収納` に直しましょうか。

作業手順としては下記のような感じでお願いします。

1. 「格納」で *.po を grep 
2.  該当結果を一つずつ確認
3.  修正
4.  変更内容を確認後コミット
5. プルリクエストによるレビュー

チェックポイントも `検問所` でいいと思います。

**Comment by denev-rove** [comment]
了解しました。
順次作業を進めたいと思います。
完了しましたらプルリクエストいたします。
