### ISSUE TITLE
タブ書式の取り扱いへの提案

### ISSUE THREAD

**Issue by piyo-gh** [nsk4762jp/OxygenNotIncluded-Japanese#19]
Steamでも指摘されている `\t` の取り扱いへの提案です。

英語やドイツ語ではちゃんとタブ表示されているようですが、日本語では参照画像のように　`\t`　がそのまま表示されてしまいます。

![2017-05-28 22_51_25-oxygen not included](https://user-images.githubusercontent.com/18474085/26897779-a5404a64-4c04-11e7-861d-b155dc59a010.png)

メーカー側の修正を待っていても仕方がないので、暫定的にこの　`\t`　を翻訳で半角スペース4個に置き換えたらどうかと思います。

L17041-L17048
```
#. STRINGS.UI.DETAILTABS.DETAILS.CONTENTS_ROTTABLE
msgctxt "STRINGS.UI.DETAILTABS.DETAILS.CONTENTS_ROTTABLE"
msgid ""
"\n"
"\t• {0}"
msgstr ""
"\n"
"    • {0}"
```

置き換えの根拠は

 - 翻訳全体で `\t` はここでしか使われていない。しかも最近の更新で追加された部分である
 - 半角スペース4個でのインデントは９か所ですでに使われている

という２点です。

ちなみに半角スペース4個の場合の参考画像です。

![2017-06-08 04_17_09-oxygen not included](https://user-images.githubusercontent.com/18474085/26897744-85586e52-4c04-11e7-9ed9-75a2f9426681.png)

どうでしょうか。

**Comment by seameteo** [comment]
半角スペースに変えてしまって良いと思います。

**Comment by nsk4762jp** [comment]
そうですね。別にタブじゃなきゃいけない理由もないと思いますので、半角スペース4個で良いと思います。

**Comment by nsk4762jp** [comment]
[061c772](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/commit/56b6d11306abc551c1b019443e1881d6dfeed603) で取り込んでおきました。
