### ISSUE TITLE
熱容量や熱伝導率が高い（低い）物質の記述子について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#191]
`Thermally Reactive`
`Slow heating`
`Insulator`
`High Thermal Conductivity`

これら4つのゲーム内用語は、熱容量や熱伝導率が高い（低い）物質に付されるものです。

`Thermally Reactive` ←→ `Slow heating`
`Insulator` ←→ `High Thermal Conductivity`

このような関係です。

（参考）: https://oxygennotincluded.fandom.com/wiki/Thermal_Conductivity

つまりこれらの記述子は、あらゆる物質がもともと備えている熱容量や熱伝導率が一定の閾値を超えている場合に、それを明示するだけに過ぎず、記述子自体に（断熱型パイプの`断熱`属性のような）何らかの効果があるわけではありません。

そのことと、上記の関係（対義語であること）を明確にするため、次のような表記にするのはどうでしょうか。
`Thermally Reactive` → `熱容量が小さい`
`Slow heating` → `熱容量が大きい`
`Insulator` → `熱伝導率が低い`
`High Thermal Conductivity` → `熱伝導率が高い`

特別なゲーム内用語を付すのではなく、文章として説明することで、この表記に効果があるのではなく、この表記は単なる（`熱容量`と`熱伝導性`という）ゲームシステムの説明なのだと誤解なく伝わるようになると思います。

**Comment by nsk4762jp** [comment]
設備の建築素材選ぶシーンで良く見る単語のやつですね。
確かに新案のほうが大小・高低が分かりやすいので良いと思います。

**Comment by kankoromochi** [comment]
この前の翻訳は私がまとめましたが、原文がとっ散らかっていて対応が分かりにくかったので、どこまで意訳するか悩んでいたところです。
正直おっしゃる通りゲームシステム上の注意書きでしかないので、それでいいと思います。
個人的には、文章だとかっこ悪いので「小熱容量」などの方が好きですが、まあそこは好みなのでお任せします。

**Comment by denev-rove** [comment]
原文が散らかっているというのは同感です。（ネイティブにとっては違うのかもしれませんが）
意訳が必要な箇所で匙加減をどうするかは、永遠のテーマですね。私もいつも悩んでいます。
個人的な方針としては、まず原文の意図が十全に伝わることを最優先として、その範囲内で単語や文法を最大限尊重する、という感じでやっています。

単語ではなく文章にしたのは、この一節があってもなくても、熱容量や熱伝導率の挙動には何の影響もないのだ（だから新たなルールを探す必要はない、この単語でググったりするなよ）という点を明確にしたかったためです。
