### ISSUE TITLE
気体や液体の Input(Intake) / Output の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#203]
気体や液体を扱う設備に備わっている、パイプの接続口（緑と白の矢印マーク）の名称についてです。

現行訳では、多くの箇所で`入力`/`出力`となっていますが、入出力は（厳密には）電力や信号など実体を持たないエネルギーなどに使う言葉のように思います。（導**線**を伝うもの）
気体や液体は実体を持った物質（導**管**を流れるもの）なので、これを`入口`/`出口`としたいのですが、どうでしょうか。

気体や液体の場合、一般には`吸気`/`排気`、`注水`/`排水`などの言い方があると思いますが、検討も兼ねて一部修正作業を進めてみたところ、`吸気ポンプ`や`排水口`といった既存の設備と紛らわしくなってしまったため、破棄しました。

`Input`/`Output`は文脈によって設備の部位を指していたり、気体(液体)を取り込む/吐き出すという行為を指していたり、微妙な意味の違いがあるのですが、幾つかの表現を試してみて`入口`/`出口`がそうした意味の違いを吸収しながら無理のない表現ができたので候補として挙げました。

`入力`/`出力`は、意味も用法も英語の`Input`/`Output`と非常に良く対応していて、訳語として説得力があるのですが、前述のとおり厳密な意味でもより正確な表現にできればと思っています。

検討をよろしくお願いします。

**Comment by nsk4762jp** [comment]
![image](https://user-images.githubusercontent.com/15379169/152736237-768a51aa-3ed3-41e5-b0fd-3c11be2abb0c.png)

了解しました。
変更内容としては上の図でいうと「出口パイプ」「設備側入口」「フィルターされた出口パイプ」「出口パイプから流れた液体」「設備側入り口」になるのでしょうか。
データベースの記述も修正しないといけないので、割と広範囲の修正が必要かも？

**Comment by denev-rove** [comment]
実は、その画面の表記も修正しようと思っています。

原文では、出口は `Output Pipe`、入口は `Building Intake` となっており、表記に対応関係がありません。これは、**出口から**（パイプを介して）**入口へ**流れるのだという点を誤解なく伝えるための配慮だと思います。（言葉の印象からは、入口から出口に流れると誤解しがちなため）

しかし、この画面では矢印自体に名前を付して列挙する形になっています。
緑の矢印と白い矢印は機能として正しく対応関係にあるので、ここの表記も（原文どおりではなく）対応する表記にしたいと思っています。具体的には、`液体出口` / `液体入口`です（`設備の液体出口` / `設備の液体入口`だと少し長すぎるので）。
緑の矢印は、決してパイプのことではなく、あくまで**設備に備わっている**の出口のことを指しているのだ（白い矢印と対になる存在だ）という点を強調する表記にしたいと考えています。

**出口から入口へ**流れるという点については、下の図に付された説明書きで十分伝えられると判断しています。

修正範囲は、今のところ4ファイルに及んでいます。(building.po, buildings.po, misc.po, ui.po)
