### ISSUE TITLE
Spacefarer Module の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#204]
現行訳では
`Spacefarer Module` → `宇宙旅行モジュール`
`Solo Spacefarer Nosecone` → `一人用宇宙旅行ノーズコーン`
となっています。

しかし改めて考えてみると、`Spacefarer` は、宇宙旅行というより、宇宙旅行**者**を表す単語です。
どちらかといえば「宇宙旅行**者用**モジュール」、いうなれば`乗組員（用）モジュール`とでも言ったほうが、本来の趣旨に沿っているのではないかと思いました。
実際、現行の翻訳ファイルの中には（実際のゲームには使用されない箇所ですが）`居住区モジュール`と意訳している箇所があり、ゲームの仕様に照らしても非常にすんなり納得できる訳に感じました。

そういうわけで
`Spacefarer Module` → `居住区モジュール` or `乗組員（用）モジュール`
`Solo Spacefarer Nosecone` → `単独居住用ノーズコーン` or `単独乗組員（用）ノーズコーン`
という案を考えてみたのですが、どうでしょうか。
ご意見ください。

**Comment by nsk4762jp** [comment]
そうですね。

`乗組員モジュール` / `単独乗組員ノーズコーン` が原語の意味を残しつつ、より良い訳になっていると思います。
居住区 は `区` とついてますけど他に工業区や商業区があるわけでもないので。
