### ISSUE TITLE
Algae Terrarium の訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#212]
`Algae`(`緑藻`)を消費して`酸素`を出す施設です。
`水`を高速で無菌の`汚染水`に変換してくれる便利なやつです。

現行訳では単に`テラリウム`となっていますが、`Algae`を省く意味は特にない（むしろ設備の趣旨が分かりにくくなってしまう）と思うので、
`緑藻テラリウム`
と改めたいのですが、どうでしょうか。

`藻のテラリウム`、`藻テラリウム`などの案も考えましたが、`Algae`が`緑藻`と訳されているので、普通に`緑藻テラリウム`とするのが無難かと思いました。

**Comment by nsk4762jp** [comment]
現実の `テラリウム` が苔や土、動植物で構成されているので、自明かなと思って `緑藻` は省いていました。
`緑藻` のための `テラリウム` なら `緑藻テラリウム` とするのはアリだと思います。

**Comment by denev-rove** [comment]
恥ずかしながら、私は`テラリウム`と聞いてもそれが具体的にどういうものかすぐに思い浮かばず、ぐぐって調べてしまいました。（存在は知っていましたが、正確な名前までは知りませんでした）

園芸に興味のない人の中には、おそらく私と似たような人もそれなりにいるのではないかと思います。
`緑藻`と付いていれば（`テラリウム`自体を知らなくとも）植物に関連する施設だと分かりますし、酸素カテゴリにあることで、光合成によって酸素を供給する（二酸化炭素を酸素に変える）設備なのだと容易に類推できるのではないかと思います。

折を見て`緑藻テラリウム`に修正したいと思います。
