### ISSUE TITLE
常用漢字による文字の制限について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#228]
`被曝`で顕在化しましたが、常用漢字に起因する、いわゆる交ぜ書きの問題についてです。
このゲームでは、私が把握している範囲では`ろ過`が該当します。

この翻訳プロジェクトは公文書でも報道文書でもないため、あえて交ぜ書きを採用する理由はないと思っています。
`ろ過`も`濾過`に統一したいのですが、問題ないでしょうか。
（筆記するには少し難しい漢字かもしれませんが、日常的に使われる単語であるため、読むだけなら不自由はないと思います）

**Comment by nsk4762jp** [comment]
あー、確かにろ過もありましたねえ。
`濾過` に統一でいいと思います。

**Comment by nsk4762jp** [comment]
`しきい値` もどうやらこれに該当しそうです。 → `閾値`
