### ISSUE TITLE
「バイオーム>表土」の説明で閉じタグ崩れがありました

### ISSUE THREAD

**Issue by nakaike** [nsk4762jp/OxygenNotIncluded-Japanese#236]
「バイオーム>表土」の説明で閉じタグ崩れがありましたのでご連絡いたします。

![image](https://user-images.githubusercontent.com/10097907/155257211-64261a42-53f1-41d1-9ec1-22ee865102f8.png)

「ぐりぐりネズミ」へのリンクタグがレイアウト崩れを起こしています。

修正箇所は下記かと思います。
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/po/subworlds.po#L649

お手すきの時に対応をお願いします。

追記：
日本語への翻訳化ありがとうございます。
楽しく、ストレスなく遊ばせていただいてます！

**Comment by nsk4762jp** [comment]
どうもありがとうございます。
画像付きで説明していただけると調査もすぐ終わるので凄く助かります。
直してすぐアップロードします。
