### ISSUE TITLE
diamondの表記ゆれについて

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#237]
`ダイヤモンド`と`ダイアモンド`が混在しています。
原語の発音と比較すると`ダイアモンド`のほうが近いと思いますが、一般に普及している表記は（圧倒的に）`ダイヤモンド`だと思います。

`ダイヤモンド`で統一しようと思いましたが、何か意図があって`ダイアモンド`にしているのであれば、そちらにしたいと思います。
ご意見お願いします。
（個人的には、統一さえされていれば、どちらでも構わないと思います。）

**Comment by nsk4762jp** [comment]
英語の綴りが `Diamond` なので `ダイアモンド` と訳していた気がします。
日本だと `ダイヤモンド` が一般的で、下記のようなページもありましたので `ダイヤモンド` で良いと思います。

[【ダイヤモンド・ダイアモンド】どちらの表記が正しい？ ](https://kikinzokukaitori.jp/diamond/diamond_column/diamond_notation.html)
