### ISSUE TITLE
cleanとsweepの使い分けについて

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#243]
前にも言いかけた気がするのですが、翻訳ポリシーのページを眺めていてふと思い出したので、改めて提案します。

このゲームにおいて、`clean`は広い範囲で使われていて、ゲームシステムに対応した固有の用語というよりも、英語という自然言語の一般的な単語として扱われているように思います。

一方で`sweep`のほうは、かなり限定的な使われ方をしていて、ほとんどの場合、散らばった瓦礫を床からどかして別の場所（`収納庫`の中など）へ運ぶ行為を指しています。`Sweepy Bot`(`スウィーピーボット`)、`Auto-Sweeper`(`自動掃除機`)など、設備の名前としても同様です。

そういうわけで`sweep`には`片付け(る)`という訳語を当てたいと思うのですが、どうでしょうか。
`清掃する`や`掃除する`は、物品の整理整頓や収納からゴミの処分、壁や床の表面に付着した埃や汚れの除去まで、何かをきれいにすることに関してほとんど全ての行為を含んでいます。（言い換えれば、抽象的です）
それに比べると、`片付ける`は主にゴミや荷物を移動させる（元の場所から消す）行為を指し、範囲が狭い（より具体的である）ため、実際のゲームの中でどんな行為を指すのか理解しやすくなると思います。（`がれき`を`片付ける`というのは、日本語として極めて一般的に使われている表現であり、ゲーム中の動作ともぴったり一致すると思います）

ご検討をお願いします。

**Comment by nsk4762jp** [comment]
そうですね。
`Tidy`(duplicants.po) に `片付ける` という訳語を既に割り当てているので、`Sweep`(ui.po) を指示した時に `Tidying` が適用されるのであれば `Sweep` も `片付け` にしてよいと思います。
