### ISSUE TITLE
ホットキー表記のパースバグについて

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#244]
翻訳プロジェクトのissueではないので、本当はここに書くべきことではありませんが、バグが修正されるまでは念頭に置いておいたほうがいいと思うため、ひとまずここに書きます。（他の場所のほうがいい場合は教えて下さい）

バージョン496912現在、ホットキーの表記をベタ書き（`<b><color=#F44A4A>[0]</b></color>` など）している文言が、ローカライズされないバグが発生しています。
タグの閉じ方が互い違いになっていること、あるいは色指定タグが原因と思われます。

この文言はゲーム本体のプログラムファイル内にもハードコーディングされているため、ローカライズ側で修正する方法は（おそらく）ありません。

こんなことならバグレポートしておくんだった‥。

**Comment by nsk4762jp** [comment]
[Bug Tracker](https://forums.kleientertainment.com/klei-bug-tracker/oni/), [Bug Tracker - Spaced Out!](https://forums.kleientertainment.com/klei-bug-tracker/oni_so/) を見る限り、まだ事例報告されてないっぽいですねえ。

試しに strings.po 側で `<b><color>xxx</b></color` という箇所を作って現象を再現できるのであれば、その時のスクリーンショットと再現手順をバグ報告してみましょう。

**Comment by denev-rove** [comment]
すみません、フォーラムは私も確認したつもりだったのですが、改めて確認したら、既に報告はあったようです。
現バージョンのリリースより何日も前に‥。
https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-translations-r34088/

既に重複して報告してしまいましたが、モデレーターによるペンディング中の記事の消し方が分からない‥。

ちなみに、この文言はハードコーディングされているため、ユーザー側で修正することは無理でした。タグの一切ない、文字も一切ないテキストで試しましたが、やはり表示は英語の原文でした。

**Comment by nsk4762jp** [comment]
コメントの一行目に `Edit: duplicate https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-translations-r34088/` って書けば、向こうにも「ああ、これは同件なのね」って分かりやすいと思いますよ。

**Comment by denev-rove** [comment]
重複レポートは避けたいので、自分の記事は消して、例示した先行レポートに問題が解決していないことをコメントしてきました。

**全ての**MODを外せば、ロシア語（公式翻訳）では正しく翻訳されました。
しかし日本語の場合、同じ手は使えないので（翻訳自体がMODなので）、Kleiになんとかしてもらうしかなさそうです。

**Comment by nsk4762jp** [comment]
了解です。

過去にも「特定のカテゴリを翻訳すると、その翻訳が表示されるときにゲームがクラッシュする」ってバグがありました。
その時は wiki の一番下に [翻訳に関する既知の不具合](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/wiki#%E7%BF%BB%E8%A8%B3%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%97%A2%E7%9F%A5%E3%81%AE%E4%B8%8D%E5%85%B7%E5%90%88) というカテゴリを作ってメモっておいたので、今回もそうしましょう。
(翻訳側で対処できないものはここに書いておきましょう)

**Comment by denev-rove** [comment]
了解しました。
翻訳ポリシーのページなので、編集はお任せしてよろしいでしょうか？
この内容がそちらに移りましたら、このissueは閉じることにします。

**Comment by nsk4762jp** [comment]
更新かけました。

**Comment by denev-rove** [comment]
ありがとうございます。
これでこのissueは閉じたいと思います。
