### ISSUE TITLE
BristleとGristleの訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#246]
長いあいだずっと気になっていたのですが、納得できる（あるいは、妥協できる）代替案が見つからず、後回しにしていたものです。
個人的には、このゲームの中でいちばん厄介な翻訳のように感じています。

- `Bristle Berry`
直訳すれば「剛毛が生えたベリー」です。表面に生えている太い棘が由来の名前です。
訳すなら`とげとげベリー`が鉄板の本命だと思います。
これが今そのようになっていないのは、ひとえに `Gristle Berry` と韻を踏んでいる表現を、どのように訳すか上手い解決策が見つからないからだと思います。
これには私も長らく悩んできましたが、原文の意味と韻を両立させるのは、思い切ってすっぱり諦めたほうがいいという結論に達しました。（強いて言えば、どちらも畳語（繰り返し語）にすれば韻を踏んだも同然だと自分に強弁しています）
韻を踏むことを考えないなら、訳に悩む点はない名称だと思います。
【変更案】
`とげとげベリー`
（そのほかの案）
`いがいがベリー`
`ちくちくベリー`

- `Gristle Berry`
直訳すると`軟骨ベリー`です。この `Gristle` が極めつけの厄介者で、ほとんど `Bristle` と韻を踏むためだけに採用された単語のように思えます。その証拠に、`Gristle Berry` やその周辺の説明文には食感に関する記述が一切なく（せいぜい「棘が邪魔だ」くらい）この単語だけが不自然に浮いている状態です。実際のところ、食感に関する詳しい設定は特にされてない気がします。
【変更案】
`ぷるぷるベリー`
`ぷるるんベリー`
（そのほかの案）
`こりこりベリー`
`もぐもぐベリー`
`グミグミベリー`
`嚙む嚙むベリー`
`焦げ焦げベリー`
    - `ぷるぷるベリー`、`ぷるるんベリー`
食感に関する記述が一切ないことを逆手に取った訳です。生の軟骨ではなく、よく煮込んだすじ肉のプルプルした食感（ゼラチン質）を表現しています（直火焼きも煮込みも同じ加熱調理ということで‥）。これなら美味しそうな印象を受けるため、ゲームシステムに照らしても、調理前の`とげとげベリー`との対比が理解しやすくなると思います。
    - `こりこりベリー`
生の軟骨の食感をそのまま表現した訳です。「○り○り○リー」と、りが3回も続くのが少し鬱陶しいです。
    - `もぐもぐベリー`
よく噛まなければ食べられない、すじ肉の食感を表現した訳です。
    - `グミグミベリー`
ハードタイプのグミの食感を表現した訳です。もはや擬音語でも擬態語でもなくなっています。
    - `嚙む嚙むベリー`
漢字にすると格好悪い。
    - `焦げ焦げベリー`
`とげとげベリー`と韻を踏んだ訳です。直火焼きにして、棘が焦げて残っているという記述があったため思いついた案です。

必ずしも全てが原文に忠実というわけではない、妥協の産物ではありますが、`ぷるぷるベリー`（`ぷるるんベリー`）が個人的に納得できる水準を上回ったため、提案に踏み切りました。

**Comment by nsk4762jp** [comment]
そのあたりの経緯は #60 にあります。今の訳になったのも #60 で話した結果なので、ぜひご一読ください。

**Comment by denev-rove** [comment]
ありがとうございます。
一応、そちらの経緯には目を通した上での提案です。あらかじめ言っておくべきでした。
そちらのissueでは、この件について結論が出ないまま（合意がなされないまま）議論が終わっているようなので、今の訳は最終結論ではないという前提で提案しています。

その前提を改めて確認したいのですが、nskさんにとって今の訳は、これまでの議論を踏まえた上で積極的に採用している妥当なものであるのか、それとも上手い訳が見つからないゆえの已むを得ない妥協の結果なのか、どちらなのでしょう。
前者であれば、この件については諦めることにします。

私としては、少なくとも`Bristle Berry`（及び`Bristle Blossom`）に敢えてカタカナ訳を採用する理由は特にないと思っています。

**Comment by nsk4762jp** [comment]
あー、すいません。どうも僕が何か勘違いしてたみたいですね。
ずいぶん昔のやりとりなので既に取り込んだものと思ってました。(items.po のコミットログを見てもベリーの名称変更は無さそうでした)  

今回の案はそのまま取り込んでOKです。`とげとげベリー` / `こりこりベリー` が個人的には好みですが、どっちが調理済みなんだっけ？というのが分かる訳のほうが良いと思います。


僕が変更を受け入れる条件みたいなものは物凄くふわっとしていて、大雑把に分けるとこんな感じです。

- 既存の訳が苦し紛れの訳になっている → 変更を受け入れやすい
- 既存の訳がそもそもおかしい → 変更を受け入れやすい
- 既存の訳が一度改定されており、ある程度定着している → 変更を受け入れにくい
- 既存の訳が一度改定されており、新訳と旧訳の差が小さい → 変更を受け入れにくい

あとはできるだけ原文にあるような韻を踏んだ文章を踏襲したいですね。
