### ISSUE TITLE
ハイパーリンクの誤りについて

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#255]
データベースほか、ゲーム内のテキストにあるハイパーリンクに、リンク切れとなっているものが散見されます。
理由はいくつかありますが、ひとつはバニラ（**ONI**）と**Spaced Out !** のDLCの有無の違いによるものです。
以下のスキルや設備は**ONI**と**Spaced Out !** で仕様が変更されていますが、名前は同じでも、内部的には全く別のスキル／設備として扱われています。しかしゲーム内のテキストは、それを厳密に区別せずに書いてしまっているようです。

**１．【DLCの有無の違いによるもの】**
名称|ONI|Spaced Out !
-|-|-
`Rocket Piloting`<br>`ロケット操縦`|`<link=\"ASTRONAUTING1\">`|`<link=\"ROCKETPILOTING1\">`
`Telescope`<br>`観測望遠鏡`|`<link=\"TELESCOPE\">`|`<link=\"CLUSTERTELESCOPE\">`

なお、`<link=\"ASTRONOMY\">天文学</link>`スキルなども仕様は変更されていますが、**ONI**でも**Spaced Out !** でも同一のスキルとして扱われています。（そのためどちらのバージョンでもリンクが生きています）

以下に、前述のスキル／設備を扱っているリンクを列挙します。
「原文」は英語版の記述です。リンクに問題があるものも、問題が**ないものも**列挙しています。
「翻訳」は本プロジェクトで採用しているリンクです。

- `Telescope`（`観測望遠鏡`）
    - buildings.po
        - `#. STRINGS.BUILDINGS.PREFABS.CLUSTERTELESCOPE.NAME`（**Spaced Out !** の設備）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
        - `#. STRINGS.BUILDINGS.PREFABS.CLUSTERTELESCOPEENCLOSED.NAME`（**Spaced Out !** の設備）
            - 原文: `<link=\"TELESCOPE\">Enclosed Telescope</link>` （**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPEENCLOSED\">密閉型観測望遠鏡</link>` （**Spaced Out !** のリンク）
        - `#. STRINGS.BUILDINGS.PREFABS.COSMICRESEARCHCENTER.EFFECT`（**ONI** の文章）
            - 翻訳: `<link=\"TELESCOPE\">Telescopes</link>` （**ONI** のリンク）
            - 翻訳: `<link=\"TELESCOPE\">観測望遠鏡</link>` （**ONI** のリンク）**（修正なし）**
        - `#. STRINGS.BUILDINGS.PREFABS.TELESCOPE.NAME`（**ONI** の設備）
            - 翻訳: `<link=\"TELESCOPE\">Telescope</link>` （**ONI** のリンク）
            - 翻訳: `<link=\"TELESCOPE\">観測望遠鏡</link>` （**ONI** のリンク）**（修正なし）**
    - codex.po
        - `#. STRINGS.CODEX.EXOBASES.PARAGRAPH_2`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
    - duplicants.po
        - `#. STRINGS.DUPLICANTS.ROLES.SENIOR_RESEARCHER.DESCRIPTION`（**共通**の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
**ONI**、**Spaced Out !** どちらでも表示される文章ですが、両立はできないため、**Spaced Out !** のリンクを有効にしています。（**ONI** ではリンク切れになります）
        - `#. STRINGS.DUPLICANTS.TRAITS.GRANTSKILL_RESEARCHING3.DESC`（**共通**の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
    - misc.po
        - `#. STRINGS.MISC.NOTIFICATIONS.SPACETRAVEL.MESSAGEBODY`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
    - ui.po
        - `#. STRINGS.UI.CLUSTERMAP.TOOLTIP_INVALID_DESTINATION_FOG_OF_WAR`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
        - `#. STRINGS.UI.CLUSTERMAP.TOOLTIP_INVALID_DESTINATION_NO_PATH`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
        - `#. STRINGS.UI.ROLES_SCREEN.PERKS.CAN_USE_CLUSTER_TELESCOPE.DESCRIPTION`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"CLUSTERTELESCOPE\">観測望遠鏡</link>`（**Spaced Out !** のリンク）
        - `#. STRINGS.UI.TOOLTIPS.MANAGEMENTMENU_REQUIRES_TELESCOPE`（**ONI** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"TELESCOPE\">観測望遠鏡</link>`（**ONI** のリンク）**（修正なし）**
        - `#. STRINGS.UI.TOOLTIPS.MANAGEMENTMENU_REQUIRES_TELESCOPE_CLUSTER`（**Spaced Out !** の文章）
            - 原文: `<link=\"TELESCOPE\">Telescope</link>`（**ONI** のリンク）
            - 翻訳: `<link=\"TELESCOPE\">観測望遠鏡</link>`（**ONI** のリンク）**（修正なし）**
本来は修正すべき対象ですが、ツールチップでのみ表示される文章であり、実質的にハイパーリンクは利用できないため、今のところ修正していません。

**２．【古いバージョンの名称が残ってしまっているもの】**
- `Rocket Piloting` (`ロケット操縦`)
    - codex.po
        - `#. STRINGS.CODEX.EXOBASES.PARAGRAPH_1`（**Spaced Out !** の文章）
            - 原文: `<link=\"ASTRONAUTTRAINEE\">Rocket Piloting</link>`（存在しないリンク先）
            - 翻訳: `<link=\"ROCKETPILOTING1\">ロケット操縦</link>`（**Spaced Out !** のリンク）
- `Super-Duperhard Digging` (`超々硬質採掘`)
    - subworlds.po
        - `#. STRINGS.SUBWORLDS.NIOBIUM.UTILITY`
            - 原文: `<link=\"SENIORMINER\">Super-Duperhard Digging</link>`（存在しないリンク先）
            - 翻訳: `<link=\"MINING3\">超々硬質採掘</link>`（**ONI**/**Spaced Out!** 共通のリンク）
        - `#. STRINGS.SUBWORLDS.OIL.UTILITY`
            - 原文: `<link=\"SENIORMINER\">Super-Duperhard Digging</link>`（存在しないリンク先）
            - 翻訳: `<link=\"MINING3\">超々硬質採掘</link>`（**ONI**/**Spaced Out!** 共通のリンク）

かなり見づらい書式になってしまいましたが、これ以上見やすくするにはどうすればいいかすぐには思いつかないので、ひとまずこのまま投稿します。

**Comment by nsk4762jp** [comment]
どうもありがとうございます。
表形式に整形しようと試みましたが、かえってぐちゃぐちゃになってしまったので諦めました。

`Telescope`/`観測望遠鏡` の該当箇所が多いですね。今後の作業のチェックリストに組み込むようにします。

**Comment by denev-rove** [comment]
【その他のリンク切れ】
そもそもデータベースにページ自体が存在しないため、リンク切れになっているもの。
（将来的な実装を予定しているのかも？）
翻訳作業を通じて気付いたものだけを列挙しているので、これで全部とは限りません。
- 作業名
`<link=\"CHORES\">何らかの作業名もしくは作業種別名</link>`
例: `<link=\"CHORES\">Sweeping</link>`
- 病名
`<link=\"SLIMESICKNESS\">何らかの病名</link>`
例: `<link=\"SLIMESICKNESS\">Slimelung</link>`
なお、病**原菌**名は存在しています。
例: `<link=\"SLIMELUNG\">Slimelung</link>`
こちらは病気の症状ではなく、病原菌の生態（生存温度など）を解説するページです。

- EXOスーツ
`<link="EXOSUIT">Exosuits</link>`

これらのリンク切れは翻訳作業に直接の関係はない（修正のしようがない）のですが、せっかくなので参考までに一応まとめました。

**Comment by denev-rove** [comment]
漏れがあったので追加です。
- `Gristle Berries`（`ぷるぷるベリー`）
    - items.po
        - `#. STRINGS.ITEMS.FOOD.BERRYPIE.DESC`（`ミックスベリーパイ`に関する説明）
            - 原文: `<link=\"PRICKLEFRUIT\">Gristle Berries</link>`（`とげとげベリー` へのリンク）
            - 翻訳: `<link=\"GRILLEDPRICKLEFRUIT\">ぷるぷるベリー</link>`（`ぷるぷるベリー` へのリンク）
        - `#. STRINGS.ITEMS.FOOD.BERRYPIE.RECIPEDESC`（`ミックスベリーパイ`に関する説明）
            - 原文: `<link=\"PRICKLEFRUIT\">Gristle Berries</link>`（`とげとげベリー` へのリンク）
            - 翻訳: `<link=\"GRILLEDPRICKLEFRUIT\">ぷるぷるベリー</link>`（`ぷるぷるベリー` へのリンク）

実際にパイの材料に使うのは**調理後**のベリーですが、原文ではなぜかリンクだけ（表示名と異なり）**調理前**のベリーへ飛ぶようになっています。

**Comment by nsk4762jp** [comment]
Fast Friends Update で一連の不整合は直っているっぽいので、この issue はクローズします。
