### ISSUE TITLE
Swamp, Bogの訳について

### ISSUE THREAD

**Issue by denev-rove** [nsk4762jp/OxygenNotIncluded-Japanese#257]
`Swamp`(`Swampy`) と `Bog` の訳語が混乱しているので、できればこれを整理したいと思っています。
（#116 の内容は確認しています）

まず `Bog` の訳語についてですが、現行訳では`泥炭地`となっています。
どこを調べても `Bog` は殆ど**泥炭**のある場所、と解説されていて、「[泥炭地](https://ja.wikipedia.org/wiki/%E6%B3%A5%E7%82%AD%E5%9C%B0)」は納得の訳語です。
ただ、実際にゲーム内で見かけると「**泥炭**」の文字がどうしても気になってしまいます。
泥炭というのは、文字通り**泥**状の石**炭**（枯れた植物が長い年月をかけて石炭へ変わる途中の物質）のことで、現実世界に於いても、実際に資源として実用された例もあるようです。なので、特に（石炭が資源として実装されている）このゲームでは、そのような資源も存在するのかと勘違いしそうになります。

そこで、**炭**の字を含まない訳語にできないかと考えてみました。
`Bog Bucket` が生えているのは、`Swampy Biome`（`沼地バイオーム`）ですが、ここには泥炭はなくとも、`Mud`（`泥`）が豊富にあります。普通に**炭**の字を抜いて`泥地`というのが案の一つになります。
ただ、`泥地`という言葉は辞書に載っていないことも多いようなので、二つ目の案として`泥沼`という訳を推します。（比喩表現で馴染み深い単語です）

次に`Swamp`(`Swampy`) ですが、これは現行訳のとおり`沼(地)`が定訳だと思います。（マジック・ザ・ギャザリングでも沼です）

まとめると、次のようになります。
原文|修正案|現行訳
-|-|-
Bog Bucket|泥沼バケツ<br>（or 泥地バケツ）<br>（or 泥バケツ）|ドロバケツ
Bog Jelly|泥沼ゼリー<br>（or 泥地ゼリー）|泥炭地ゼリー
Swampy Delights|沼地の楽しみ|泥炭地の楽しみ
Swamp Chard|沼地ビーツ<br>（or 沼ビーツ）|ヌマビーツ
Swampy Biome|沼地バイオーム|沼地バイオーム

各項目の関連性を示すために、できれば`泥`と`沼`は漢字で揃えたいのですが、どうでしょうか。
ご検討をお願いします。

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

この投稿で気が付いたのですが、これまでの改訂によって動植物の名称が

- カタカナ表記の和名
- 漢字かな(カナ)混じりの普通名

で混在している状況です。できれば動植物はユニークさを出すために和名で統一したいと思っています。

- 動植物 → カタカナ表記の和名 (例: ハッチ、ドロバケツ、トゲトゲバナ)
(でも亜種の名前は ひらがな+原種名 がとてもしっくりするんですよね...)
- 動植物の産出物 → カタカナ表記の和名 + 産出物普通名 (例: ハッチの卵、ドロゼリー、トゲトゲベリー)
- 動植物の産出物を元に変化したもの → 普通名 (例: ハッチの幼体、沼地の楽しみ、ぷるぷるベリー)

視認による関連性は若干薄れますが、読みは同じなので類推は可能かなと思います。

**Comment by denev-rove** [comment]
すべてカタカナという特徴的な表記にすることで、動植物名であることを明示する‥という意図は分かるのですが（まさに標準和名をカタカナで書くようになった理由です）、ゲームのUIとしては、弊害のほうが大きいんじゃないかと思います。

理由はいくつかあります。
まずカタカナは表音文字なので、漢字表記であれば伝わったはずの意味が失われてしまいます。
また、日本語には（英語のような）単語で区切るという概念がないため、一様にカタカナが続いてしまうと、文字列のどこが区切りなのか理解しづらくなるという面もあります。（これは一様に漢字が続く場合でも同様ですが）
総じて、標準和名の抱える問題がそのまま再現される形です。

標準和名というのは（ラテン語の）学名と同じく、学術研究の分野で使うことを趣旨とした用語です。つまり、多種多様な生物種を混同せずに分類することが第一義であり、自然言語というよりは、一意に定められた一種の記号のようなものでもあると思います。
ある意味では、襟を正した畏まった表現とも言え、ユーモアに溢れた（俗語的表現も多い砕けた雰囲気の）このゲームとは、相性が悪いようにも思います。

`ドロバケツ`くらいならまだそれほどでもないのですが、たとえば`雪ん小麦`や`ぷすぷすモー`などを標準和名表記にした場合、せっかく雰囲気のある名訳が台無しになってしまう感じがします。

標準和名の持つ学術的な雰囲気を借りるために、個別に検討した上で標準和名表記を採用する、というのは有りだと思います。しかし、すべて標準和名で統一してしまうのは、少し乱暴のような気がするのですが、どうでしょうか。

**Comment by nsk4762jp** [comment]
なるほど。確かに一理ありますね。
和名普通名混在してるのは個人的にはすっきりしませんが、和名は適切な普通名が編み出されるまでのプレースホルダーって考えるようにします。

さて、本題に戻りますと、個人的には下記の案が好みです。

原文 | 修正案
---- | ----
Bog Bucket |  泥沼バケツ
Bog Jelly | 泥沼ゼリー 
Swampy Delights | 沼地の楽しみ 
Swamp Chard | 沼地ビーツ
Swampy Biome | 沼地バイオーム 

【余談】
Bog Bucket はウツボカズラに代表される Pitcher Plant の捩りっぽいですね(Pitcher = 水差し、Bucket = バケツ)。

**Comment by denev-rove** [comment]
生意気なことを言って申し訳ありません。
和名普通名の混在が気持ち悪いという気持ちは、とてもよく分かります。
私も同じ気持ちから、動植物名の表現に関して悩む機会があって、そのときに標準和名と普通名の使い分けの難しさについて思い知りました。

標準和名で書いたほうか分かりやすいケースというのも確かにあるのです。
「向日葵」「玉蜀黍」「馬鈴薯」みたいな無理矢理すぎる当て字（植物名には本当にこういうのが多い）の場合は、カタカナ表記のほうが分かりやすいです。（「南瓜」「西瓜」までくると一般的に広く使われていますが、やはり字と発音が全く合ってないのは引っかかります。）
「葡萄」「薔薇」など、比較的見慣れてるものの、やたらと画数の多い漢字も判断に迷います。

このゲームに登場する動植物では`ケモノジゴク`などが、標準和名表記にすべき好例だと思います。`蟻地獄`なら馴染み深い名前なので、まだしも虫だと分かりますが、`獣地獄`では、生物の名前であると察するのはなかなか難しい気がします（仏教の経典に出てくる地獄の種類かと思ってしまいます）。`ケモノジゴク`なら、標準和名表記であることから、アリジゴクをもじった名前だと容易に類推できます。（これも名訳の一つだと思っています）

閑話休題。
ご提示の修正案をそのまま採用したいと思います。

ウツボカズラも食虫植物ですが、このゲームの`Bog Bucket`は違うみたいですね。（あるいは実装されていないだけで、設定としてはそうなのかもしれませんが）
