### ISSUE TITLE
実績Morale High Groundの翻訳について

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#262]
PR #211 にて修正されていた実績名について"Morale High Ground"を「天にも昇る士気」にという訳語になっていますが少し意訳が過ぎるのではないかと思い発議させていただきます。

"Morale High Ground"はもともと英語圏で"moral high ground"という定型表現があるところからのパロディなのでそこを全部無視してしまうのはどうかと思っておいます。
ちなみに"moral high ground"はWikipediaにもページがあります。→ https://en.wikipedia.org/wiki/Moral_high_ground

"moral high ground"の定訳が日本語にあれば良いのですが、どうにもそこら辺はフワフワのしているようで、「道徳的に優れた立場」というあたりになりそうです。基本的には対立構造がある片方が道徳的に優れており、そこをテコに世論を動かすような際に使う言葉のようです。係争状態を前提としているようです。

セットで使われる動詞はtakeが多く、次いでclaim、seizeあたりが使われるようです。 
"take the high ground"という軍事表現（Take the High Ground!というタイトルの戦争映画があるようです）からの転用として"take the moral high ground"という表現が使われていてさらにそれのパロディとして"Morale High Ground"があるという立ち位置のようです。

まとめとして
・"take the high ground"をベースにするので軍事的、戦略的ニュアンスが欲しい
・絶対的に強いのではなく相対的に強いというニュアンスが欲しい
・Highが士気の高さとロケットの高度のダブルミーニングになるようにしたい
・パロディとしての胡散臭さが欲しい
ということを考えまして"high ground"の訳語に「高高度」を当てると良いのではないかと思いつきました。

ストレートに
・高高度の士気

軍隊っぽく
・高高度の士気と戦略（指揮と戦略と音が同じ）
・高高度の作戦士気（作戦指揮と音が同じ）

B級映画っぽく
・高高度の士気大作戦

こんなことを考えているのですがどうでしょう。個人的には「高高度の士気大作戦」がバカっぽくて好きです。

**Comment by souki-tn** [comment]
@denev-rove
ディスカッションとして参加していただけると幸いです。

**Comment by nsk4762jp** [comment]
実績の名前なので `高高度の士気大作戦` がそれっぽくて良いですねえ。

**Comment by denev-rove** [comment]
語句の背景について詳しく説明していただいてありがとうございます。
おかげで理解が深まりました。
軍事的な文脈で使われる意味が既に、原義から派生したものだったんですね。

本来の倫理的な（ときには皮肉が込められた）意味との掛け言葉にするのは、かなり難しそうです。
軍事的な意味のほうを取り入れた訳にするのは妥当だと思います。
（軍事とは切っても切り離せない、ロケットに焦点を当てた実績ですし）

私も、このゲームのゆるい雰囲気がよく出ている`高高度の士気大作戦`がいいと思います。
訳の根拠がしっかりしていて、ゲームの仕様（実績解除の条件）にもきちんと沿っているので、英語独特の（正攻法では翻訳不可能な）言い回しの訳としては、欲張りな仕上がりになっていると思います。

**Comment by souki-tn** [comment]
後ほどRPにまとめます。
