### ISSUE TITLE
`Gristle Berry`の翻訳について

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#264]
日本語訳のアップデートで「ぷるぷるベリー」は原語からズレすぎでは思いました。

`Gristle`は辞書の上では以下のようなものなので、`ぷるぷる`という柔らかそうな語感に違和感を覚えています。
```
gristle
名
〔料理の肉に含まれる〕軟骨、すじ◆通常食べられない部分
```
(出典: https://eow.alc.co.jp/search?q=gristle)

辞書引いて出てくる「軟骨」から軟骨の唐揚げの軟骨のようなニュアンスで訳したように察するのですが、ここでいう軟骨は食べられない軟骨なので植物質であればグレープフルーツの房の皮、栗の渋皮、ミカンの硬めの筋あたりの食感イメージだと思います。
食べ物だよ？という疑問符は付きますが、このゲームそういう部分あるので。

Bristle Blossom関連の言葉は関連づけて修正することになると思いますが、韻の関係もあるので少しディスカッションしてはどうでしょうか。

私からの翻訳案です。
| 英語名 | 直訳的な意味 | 翻訳案 |
| ------------- | ------------- | ------------- |
| Bristle Blossom  | Bristle: 剛毛、ブラシなどの毛 Blossom: 花、特に果樹の花  | けばだち花  |
| Bristle Berry  | Bristle: 剛毛、ブラシなどの毛 Berry: 木の実や果実、主にベリー種  | けばだちベリー  |
| Gristle Berry  | Gristle: 固い軟骨やすじ Berry: 木の実や果実、主にベリー種   | すじがちベリー  |

`けばだち` と `すじがち` の `だち` と `がち` で辛うじて韻踏んでる感じです。
昔の翻訳データには`Bristle Berry`を未調理で食べたら喉にトゲが刺さったというデバフデータがあったはずなので、もうちょっと食べにくそうな訳にするのが正しい気もしますが、けばだちでも十分食べにくそうでしょうか。

**Comment by nsk4762jp** [comment]
`Bristle` には [〔毛が〕逆立つ、〔人が〕いら立つ](https://eow.alc.co.jp/search?q=bristle) という意味もあるようですね。
グラフィックも怒髪天を衝くと言った感じです。とげとげが生えているのもそのせいかも？

![image](https://user-images.githubusercontent.com/15379169/156867058-693361b8-5573-4522-97f2-9c49b9f84742.png)

という訳で僕の案はこちらです。

英語名 | 翻訳案
------- | -------
Bristle Blossom | いらだち花 
Bristle Berry | いらだちベリー
Gristle Berry | すじがちベリー

**Comment by souki-tn** [comment]
@nsk4762jp 
なるほど。毛が逆立つってのは猫が「ふー」とやってる時のイメージなんですかね。
比較的副次的な意味だと思うので、これ限定的なシチュエーションの言葉だったりしませんか？　調べるにも難しいですが。
日本語でも「藁」が言葉の意味として「音から転じて笑いの意味」と書いてあったとしてもネットスラングのしかも2ch時代の一部分でしか使わない表現ってことは日本人ならわかりますけど、辞書引っ張るだけだとわからないんですよね。

**Comment by nsk4762jp** [comment]
そうですね、ということでいろいろキーワードを変えて画像検索してみました。

- `Bristle` で画像検索 → ブラシの画像。
- `Bristle with anger` で画像検索 → 怒髪天を衝くの画像。ただしヒット数は少ない。
- `Bristle cat` で画像検索 → 毛を逆立てた猫と猫用ブラシの画像。
- `Bristle dog` で画像検索 → 犬用ブラシの画像。(犬は毛を逆立てないので...)
- `Bristle animal` で画像検索 → ハリネズミの画像。

[絵で覚える bristle の意味](http://ewalk2.blog117.fc2.com/blog-entry-311.html) を見ると「毛を逆立てたブラシの生き物」があって Bristle Blossom もまあ似たような感じかなと思います。

**Comment by denev-rove** [comment]
**【検討】**
私がこれまで検討してきた過程では、#60 で既出の `とげばりベリー`、`すじばりベリー`が、いくつかの要件を最も深く満たせる案だと思いました。

ここで私が考えた要件は、
1. 韻を踏んでいること
2. 意味が原文どおりであること
3. 原文とは無関係に、純粋に日本語として見たときに不自然でないこと

です。

1.については`ばり`の2文字が共通ですし、2.については`とげ`と`すじ`が十分原文どおりであると思います。
問題は3. ですが（`とげばり`も`すじばり`も、あまり一般的な形容ではないと思います）これは1.2.との引き換えの結果として受け入れるしかないと思います。（逆に、現行の私の案は1. を捨てて3. を優先した結果です。）

両者を見比べたときに、調理前と調理後の区別がすぐにはできそうにない（どっちも食べにくそうなので）点が非常に惜しまれますが、これも韻を踏むことを優先するなら諦めるしかなさそうです。

`Gristle` の語が表現する食べやすさに関しては、`#. STRINGS.ITEMS.FOOD.GRILLEDPRICKLEFRUIT.DESC` を見ると、焼け残った棘が邪魔なだけで、むしろ味自体は悪くない(exquisite taste)ように書かれていることから「食べられない」とまで言えるほどではないと思います。現実でも、`gristle` をうまく調理して食べている例は珍しくありませんし。`Bristle Blossom` も、ゲーム中で食用作物として認識されています。

また、新たにご提案の`すじがちベリー`はちょっと違和感があります。
「筋張った肉」という表現はあっても、「すじがちな肉」という表現はないためです。韻を踏むための措置だと察しますが、他の要件との兼ね合いが悪いように思います。

このissueが、韻を踏んでいないことではなく、`ぷるぷる`が原語からズレすぎているという点を問題にしているのであれば、#246 でnskさんが挙げられていた`とげとげベリー`、`こりこりベリー`がいいと思います。

**【まとめ】**
1. 韻を踏む場合

原文|案
-|-
Bristle Blossom|とげばり花
Bristle Berry|とげばりベリー
Gristle Berry|すじばりベリー

2. 韻を踏まない場合

原文|案
-|-
Bristle Blossom|とげとげ花<br>（or けばだち花）<br>（or いらだち花）
Bristle Berry|とげとげベリー<br>（or けばだちベリー）<br>（or いらだちベリー）
Gristle Berry|こりこりベリー

韻を踏まないなら、`Bristle` の訳語には自由度があると思います。

**【余談】**
モチーフとなった現実の植物は、[アーティチョーク](https://www.google.com/search?q=artichoke+flower&tbm=isch)よりも、[ごぼう](https://www.google.com/search?q=Arctium+lappa+flower&tbm=isch)のほうが近いかもしれません。（主に棘の形状が）

**Comment by denev-rove** [comment]
ここに出た案で優先順位をつけるなら
1. `とげとげベリー` / `こりこりベリー`
2. `とげばりベリー` / `すじばりベリー`
3. `けばだちベリー` / `すじがちベリー`
4. `いらだちベリー` / `すじがちベリー`

になります。
個人の好みを抜きにすれば、どの案も一定の根拠があり、ゲームを遊ぶ上で支障となるような問題点もないので、最終的にはどれでもいいと思います。（結論が出るまで議論には参加したいと思います）

**Comment by souki-tn** [comment]
海外のフォーラムで見た時は、デザインモチーフはアザミだろうと言われていました。観葉植物として栽培されてる中ではそれっぽい。
Gristle Berryの食感は、サトウキビの茎を剥いて齧ってる感じだと思っています。可食部かと言われるとやや厳しいものの、齧れば甘いしずっと齧ってたい感じ。小学校で配られてたやつです。

**Comment by nsk4762jp** [comment]
[ps_break さんの投稿](https://steamcommunity.com/workshop/filedetails/discussion/928606476/1290690669224436955/?ctp=8)

> 技術的な質問でなくて申し訳ないですが、なぜベリーなどの一部のものだけの名前が変わったのでしょうか？
> 特に調理したベリーの名前は現在のものはわかりにくいと思います
> 火を通してあるのでグリルベリーのままでよかったのでは？プルプルベリーでは収穫直後のものなのかそうでないのか直感的にもわかりにくいし、今更変えるのも日本語wikiやブログで調べるときに不便だと思います

**Comment by denev-rove** [comment]
個人的には、さすがに意訳が過ぎる（`gristle` には、そのような意味合いは存在しない）ので、今まで全く選択肢にありませんでしたが‥。
たしかに、調理前／調理後を区別するという観点からは、以前の`グリルベリー`は分かりやすいですね。
そう考えると、再検討の余地はあるかもしれません。

だとしても、`グリルベリー`というのは和製英語っぽくて、正直かなりの抵抗があります。
`グリル`という意訳を採用するなら、`グリルドベリー`もしくは`グリルしたベリー`にしてほしいです。

その場合、韻を踏むことは完全に放棄することになるので、`Bristle Berry` も特に技巧を凝らす必要はなく、単純に`とげとげベリー`でいいんじゃないかと思います。

**Comment by nsk4762jp** [comment]
[ps_break さんの投稿(2)](https://steamcommunity.com/workshop/filedetails/discussion/928606476/1290690669224436955/?ctp=8)

> ベリーの名前に関して経緯を見たのですが、すべて元の訳に戻すべきだと思います。
> 
> 以前変更された「雪ん小麦」(元スリートウィート)は生息地が同じウィーズウォートと字面が似ていてややこしい点の解消、小麦にすることでパンとの繋がりがより日本語で解りやすくなるといった妥当な理由のある良い翻訳だと感じたのですが、ブリッスルベリーに関しては変更した理由が訳の提案者の意向くらいしか無く、かえってややこしくなっている始末です。始めたてのプレイヤーが真っ先に発見するであろう物の1つで混乱が生ずるのも良くない状況かと思います。
> 
> 提案者の方は原文の意図や雰囲気・韻を大事にしているゆえの提案だと感じたのですが、たとえカタカナ・原文にそぐわない訳・和製英語であっても、すでに長い間使われ定着していて且つ、日本語で違和感や混乱が生じないのなら、無闇にいじらないほうが良いと思います。

**Comment by denev-rove** [comment]
既に定着した訳を変えることの弊害は、よく分かります。
しかし、変えた直後は違和感があっても、時間の経過とともに新たな訳が定着すれば、いずれ解消されるものだとも思います。（`メクラウナギ` → `ヌタウナギ`、など、学術的な名称の変更もそのように受け入れられていますし）

私としては、原文を無視した状態を永遠に続けるよりも、一時的な混乱を受け入れて根本的な解決を果たすほうが弊害は少ないという考えです。

`雪ん小麦` に変えて意味が分かりやすくなったのと同じように、`Bristle` も意味の分かりやすい表現であってほしいと思います。訳すことが（韻を無視すれば）特に難しい単語でもないですし。（`Gristle`のほうは、ちょっと難しいかもしれませんが‥）
`ブリッスル`はカタカナ語としてあまり一般的ではなく、意味が汲み取れないので、遊んでいてかなり引っかかります。

これについては、どちらの方針が正しいというものではないので、どこかの時点で一方を選択する決断をするしかないと思います。

私の提示できる妥協案としては、
- `Bristle` は普通に訳す（今の`とげとげベリー`など）
- `Gristle` は（普通に訳すのが難しいので）意訳である従前の`グリル`を取り入れて、`グリルドベリー`（もしくは`グリルしたベリー`）にする
- 韻を踏むことは諦める

です。

**Comment by nsk4762jp** [comment]
[OCIWCIR さんの投稿](https://steamcommunity.com/workshop/filedetails/discussion/928606476/1290690669224436955/?tscn=1647193498)

> [https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/issues/264#issuecomment-1066065464](https://steamcommunity.com/linkfilter/?url=https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/issues/264#issuecomment-1066065464)
> 全く翻訳に参加していない身として申し訳ないのですが、githubの方に転記していただいたコメントへの発案者denev-rove氏の返答が、全く同意しかねる返答だったので長文で強く書いておきます。
> 
> >既に定着した訳を変えることの弊害は、よく分かります。
> >しかし、変えた直後は違和感があっても、時間の経過とともに新たな訳が定着すれば、いずれ解消されるものだとも思います。（メクラウナギ → ヌタウナギ、など、学術的な名称の変更もそのように受け入れられていますし）
> 
> 　例に出しているヌタウナギは元が差別語が含まれるという極めて重大・深刻な「皆が納得する」「即座に変更すべき理由」があり、今回のような話とは比べ物にならない問題です。見当違いな例を出さないでください。
> 
> >私としては、原文を無視した状態を永遠に続けるよりも、一時的な混乱を受け入れて根本的な解決を果たすほうが弊害は少ないという考えです。
> 
> 　何億人が何十年と関わる現実世界とは異なり、わずかな人数のさらに1言語に絞られるゲームの翻訳では定着が遅く、弊害のほうが遥かに長く続くかと思います。
> 　原文を無視していたとしても、なにかが気に食わなくても、他に有意義な理由がなければ1度浸透した名詞は安易に変えられるべきではないと思います。
> 
> >雪ん小麦 に変えて意味が分かりやすくなったのと同じように、Bristle も意味の分かりやすい表現であってほしいと思います。
> 
> 　雪ん小麦を良い改訳と挙げたのは、「ウィーズウォートとの混乱の解消」と「小麦→パンがより明確になった」という2つの問題を解消しているからで、この2つの問題は「すでに浸透した訳を翻してでも変えるに相応しい」と感じたからです(当然、雪ん子麦に不満のある人もいるでしょう)(偉そうにすいません)。
> 　決して、決して、単語の意味がわかりやすくなったとか、ただ単に韻が良いから、ではありません。
> 
> >ブリッスルはカタカナ語としてあまり一般的ではなく、意味が汲み取れないので、遊んでいてかなり引っかかります。
> 
> 　常に意味が汲み取れる言葉である必要性を感じません。大元の意味を知らずに見ているカタカナ語なんてゲームに限らず溢れていますし、特に、ONIの植物は現実の植物とは異なるファンタジー植物なわけで、意味が分からない言葉であっても何ら問題ない部分ではないでしょうか。
> 　とにかく、浸透した翻訳を変える必要性としてはあまりにもどうでもいい事かと思います。
> 
> 　denev-rove氏の翻訳案は変更するメリットが極めて薄く、すでに浸透した翻訳を軽視し、カタカナ語を忌避し、自身の翻訳規範に固執していると返答を受けて感じました。
> 　すでに名詞部分については戻していただけたようで、管理者の方ありがとうございます。　翻訳に貢献しない外野から長文失礼しました。

**Comment by nsk4762jp** [comment]
いろいろありましたが設備名、アイテム名については気安く変えられると困る人がいるので、当面はこのままとします。

**Comment by ujihisa** [comment]
最新版日本語MODで未だにとげとげとぷるぷるのままですが、これはいつブリッスルとグリルに戻す予定なのでしょうか?

**Comment by nsk4762jp** [comment]
Oxygen Not Included Uploader 経由でMODの更新はしたんですが、ダウンロードされるバージョンが一つ前の古い奴になっています。日本語化MODが最新版に更新されない問題はかなり前からあって、原因及び解決策が不明な状態が続いています。

[バグトラッカーにも挙げられている](https://forums.kleientertainment.com/klei-bug-tracker/oni/translations-dont-update-automatically-r14178/)のですが、コメントも付いてない辺り Klei 側でも確認できていないみたいです。

[strings.po](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po) を `(マイドキュメント)/Documents/Klei/OxygenNotIncluded/mods/Steam/928606476/` に手でコピーすると名前を戻したバージョンになるはずです。

**Comment by ujihisa** [comment]
おお、なんと...。2018年からずっとそうなんですね。これは不便。
了解です、ありがとございます!

**Comment by nsk4762jp** [comment]
このまま放置するのも気持ち悪いので、フォーラムのMODセクションに投げてみます。

**Comment by souki-tn** [comment]
このイシューの役割は終えていると思うのでクローズします。
