### ISSUE TITLE
定着した訳語名称を変えることについて

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#266]
ここ数か月でいろいろと訳語名称を変えていますが、どうも評判が良くないみたいです。
理由は主に以下の通りです。

- 既に変更前の訳語名称で定着している
- wiki や blog で紹介された名称と異なるため探し出せない
- 変更後の訳語名称が変更前と比べて分かりづらい

原文と照らし合わせると変更後の訳語名称のほうが正しいのかもしれません。しかしながらこれまで特に混乱を来すわけでもなかった訳語名称をいきなり変えるのはリスクが高かったようです。

この調子で進めていくとおそらく誰も幸せにならないと思うので、訳語名称については一部戻すことを考えています。

**Comment by nsk4762jp** [comment]
今回の一連の変更でマズいなと思ったのは、訳語名称がサイレント修正されたという点です。
ある日突然名前が変わると混乱するのは当然で、事前告知やリリースノートを書くべきだったかなと思いました。

名称の変更は随時ではなく何らかの大型アップデートが入ったタイミングでやるのが良さそうです。

**Comment by nsk4762jp** [comment]
設備やアイテム名を主なターゲットとした戻しリスト


旧 | 新 | PR
---|----|----
微生物粉砕機 | 微生物圧縮機 | #184 
格納庫 | 収納庫 | #197 
気体貯蔵庫 | 気体貯蔵槽 | #197 
液体貯蔵庫 | 液体貯蔵槽 | #197 
RADボルト貯蔵庫 | RADボルト貯蔵器 | #197 
テラリウム | 緑藻テラリウム | #220 
消毒剤 | 手指消毒剤 | #227 
野営トイレ | 汲み取りトイレ | #227 
洗面台 | 手洗い器 | #227 
大広間 | 大食堂 | #227 
ブリッスル ブロッサム | とげとげ花 | #248 
ブリッスルベリー | とげとげベリー | #248 
グリルベリー | ぷるぷるベリー | #248 
ドロバケツ | 泥沼バケツ | #258 
ヌマビーツ | 沼地ビーツ | #258 
泥炭地の楽しみ | 沼地の楽しみ | #258 
泥炭地ゼリー | 泥沼ゼリー | #258

**Comment by denev-rove** [comment]
nskさんの采配にお任せしたいと思います。
今後の翻訳作業にあたって留意する点などがあればお伝え下さい。

**Comment by nsk4762jp** [comment]
そうですねえ。

設備名やアイテム名はそれが明らかに間違っている(or 著しく誤解を招く)ものでもない限り、定着しすぎてもう修正できないんじゃないかなって思います。( `雪ん小麦` はたまたま受け入れられたものだと思っています)
UI や作業名、能力名、実績名等はまだ改善の余地があるので、力を入れる方向としてはそっちが良いでしょう。

**Comment by denev-rove** [comment]
そうですか‥私も認識が甘かったようです。

**Comment by nsk4762jp** [comment]
まあ、次のDLCが出るタイミングでまた新しい設備やアイテムが出てくるでしょうから、その時は是非お知恵を拝借したいです。

**Comment by wada314** [comment]
一応申し上げておきますと、雪ん小麦すらも私は全く受け入れられません。 カタカナ名で何が悪いのか、既存の攻略情報が全く意味をなさなくなる名前の変更はたとえ大型アップデートでもやめていただきたいです。
