### ISSUE TITLE
実績の元ネタの情報交換用

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#269]
Oxygen not includedの実績は言葉遊びの要素や元ネタがあるものなど全体に翻訳難度が高く、その上でゲーム内にそのヒントがないものがほとんどなので、元ネタ収集を行った方がいいのではないかとイシューを立てました。
翻訳として組み込むことが難しいものも多いとは思いますが、結果として原文のニュアンスを残せるような成果が出れば最高です。
直訳からは距離のある翻訳になるものも多くなりそうなので翻訳の経緯を残せれば今後のためにもなるでしょう。

（不要であればクローズしてしまってください）

**Comment by souki-tn** [comment]
Morale High Groundについては→ #262

**Comment by nsk4762jp** [comment]
実績一覧があったほうが話がしやすいと思ったので一覧化しました。

原文 | 日本語訳
---- | ----
Red Light, Green Light | 赤い信号、緑の信号
Bed and Bath | ベッドとトイレ
Oxygen Not Occluded | 酸素は遮断されていません
Some Reservations | 保護区群
Outdoor Renovations | 屋外の改装
Immovable Object | 不動の物体
Super Sustainable | 超・持続可能
Pulling Back The Veil | ベールを剥がせ
Honorary Doctorate | 名誉博士号
To Pay the Bills | 身を立てるため
It's Not Raw | 生じゃない
They Got Better | 病み上がり
Carnivore | 肉食動物
And Nowhere to Go | なお出かける先は無し
Job Suitability | スーツの似合う仕事
Slick | 油まみれ
First Teleport of Call | 初めてのテレポート
Finely Tuned Machine | 精密に調整されたマシン
GMO A-OK | 遺伝子組み換え作物？ヘーキヘーキ
Good Egg | 良い卵
Down the Hatch | ハッチダウン
Easy Livin' | 気楽な暮らし
Ghosts of Gravitas | グラビタスの幽霊
Cluster Conquest | 小惑星群の制覇
Art Underground | アングラ芸術
Mine the Gap | 隙間を掘り起こせ
Locavore | 地産地消
Royal Flush | ロイヤル フラッシュ
Radical Trip | ハジケる旅
Space Race | 宇宙開発競争
That's Rad! | 元気よく、原子力！
Not 0K, But Pretty Cool | 0Kじゃないけど、かなりクール
Soft Launch | 軟発射
Turn of the Century | 世紀の変わり目
Morale High Ground | 高高度の士気大作戦
One Year, to be Exact | きっかり一年
Sweeter Than Honey | 蜂蜜よりも甘い
Critter Whisperer | ムツゴロウさん
Moovin' On Up | 気分はモーモー
Totally Tubular | すっかりチューブ状
No Place Like Clone | 複製に勝るもの無し
Get a Room | 部屋でやれ
Cosmic Archaeology | 宇宙考古学
The Great Escape | 大脱出
Home Sweet Home | 楽しき我が家

**Comment by nsk4762jp** [comment]
[Down the Hatch は `乾杯！` とか `飲み込む/飲み干す` とかいう意味らしいです。](https://www.ihcway.com/1day/20180305152237.html)

**Comment by souki-tn** [comment]
私の方で調べたものの翻訳に苦しんでいるものたち。

**Space Race**
米ソの宇宙開発競争を指す意味強いですが、Raceは人種という意味もあるので宇宙に適応した新人類の意味も多分含めているので翻訳が難しい。SFもので出てきたら、宇宙でカーレースっぽいものをやるか、宇宙の人種として出てくるかでしょう。

**Critter Whisperer**
翻訳が「ムツゴロウさん」なので良いのかこれと思っているもの。
Whispererが動物と気持ちが通じ合うような人の意味なのですが、しかしムツゴロウさん。世代的に私は全力で理解できますが、今の10代20代にわかるのだろうか。

**Down the Hatch**
そのままで乾杯の掛け声。日本語でも使われるハッチ（荷物運搬用の搬入口）から下ろすように、酒を飲むイメージ。ハッチはゲーム内ではもちろん動物種を指します。

**First Teleport of Call**
first port of callという定型句が元ネタ。船の航海の最初の寄宿港のこと。
翻訳はどうするんだろう。

**Soft Launch**
限定先行販売を行う商品展開の手法がおそらく元ネタ。
「先行試射会」とか訳すと多分近い。

**Mine The Gap**
mind the gapがおそらくネタ元。意味としては「お足元にお気をつけください」　mind your stepと使い分けがされる。

**Morale Hight Ground**
moral high groundという定型表現が元ネタ。

**That's Rad!**
that's right!が元のはず。翻訳がひねりにくい。

**Comment by nsk4762jp** [comment]
[That's Rad! というスラングがあるようです。](https://meoto-ny.com/thats-rad/)

**Comment by souki-tn** [comment]
Radにポジティブな意味でスゲーという意味がある感じですね。スラングはよくわからないな。

> また、人に対して、「rad」を使う時には特別なニュアンスがあります。それは、対象が自然に「cool」な行動をしている時です。つまり、頑張っていないのに、自然に「cool」ということです。それを説明するのは難しいのですが、皆さんにはニュアンスが伝わると思います。

出典：https://www.eigowithluke.com/rad-radical/

とあるので自然体でスーパープレーをするニュアンスが強そうです。

スラングの発祥はサーファーとのことですが、サーフボードのブランドとして「ラッドリッパー（RAD RIPPER）」あるようです。
https://www.murasaki.jp/category/RADRIPPER_SB/?condition=utm_source:WOMEN_AP_TSHIRT_from_FB

**Comment by souki-tn** [comment]
**Red Light, Green Light**
ダルマさんが転んだの英語版。

https://eow.alc.co.jp/search?q=Red+Light+Green+Light

> red light, green light
> レッドライト・グリーンライト◆子どもの遊び。参加者は鬼から離れた場所からスタート、最初に鬼に触った人が勝ち。ただし動いていいのは鬼が後ろを向いてGreen light!と言ったときだけ。鬼はRed light!と言って突然振り返ることができ、そのときすぐ止まらなかった参加者は失格。日本の「だるまさんが転んだ」と似ているが「だるまさんが転んだ」では負けた人が鬼になるのに対し、このゲームでは勝った人が次の鬼になる。

**Comment by souki-tn** [comment]
**Good Egg**
「信頼できる人（主に男性）」という意味で使われるらしい。

**Comment by souki-tn** [comment]
**To Pay the Bills**
pay the billsの定訳は「生活費を稼ぐ」
翻訳としては「手に職」がニュアンス上も実績の内容にも良さそう。

**Comment by nsk4762jp** [comment]
[Carnivore](https://eow.alc.co.jp/search?q=carnivore) はここに書いてある3個目の「肉を食べるのが大好きな人◆ユーモラスな表現」が当てはまりそうですね。
「お肉大好き」といった感じかな。

**Comment by souki-tn** [comment]
Carnivoreは肉食動物のままでもいい気がします。
理由としては、日本語でも「肉食動物」と表現した際に「肉を食べるのが大好きな人」という意味にはなると思うんですよね。
「焼き肉いいっすね。自分肉食動物なんすよ」とか言われたら、ああそういうことねってなるじゃないですか。

**Comment by nsk4762jp** [comment]
文脈で使う分には分かると思いますが、実績名称なので何をすればよいのか類推できるような表現が好ましいと思います。
例で出した「お肉大好き」であれば、「お肉」は食べ物なので続く「大好き」と来たら「複製人間に肉を食わせる実績なのね」って想像はできそうです。

まあでも元ネタが特にあるわけでもなさそうな単語なのでこのままでもいいかもしれませんね。

**Comment by nsk4762jp** [comment]
Some Reservations は「ちょっと心配」と言った意味があるそうです。
[出典１](https://gogakuru.com/english/phrase/6665) [出典２](http://toeicto.jugem.jp/?eid=869)

**Comment by denev-rove** [comment]
- `Good Egg`
何とかもう一つの意味も翻訳に反映できないか暫く悩んだ記憶があります。
いかにも上手い案がありそうな感じがしたのですが、結局できませんでした。

- `Royal Flush`
`Royal Flush`(高級な水洗)と、ポーカーの役（ロイヤルストレートフラッシュ）を掛けた駄洒落だと思いますが、これも日本語にするのは難しいですね‥。

- `Carnivore`
代案があるとは考えもしませんでしたが、`お肉大好き`はかなりいい感じの意訳に思えます。
このゲームの少し抜けた雰囲気に良く合ってるし、なにより実績の達成条件が分かりやすくなっている点が素晴らしいと思います。
`肉食動物` だと、`動物`(`Critters`) に関する実績と勘違いする余地が残ると思うので。
どちらにするか選べるなら、私は断然`お肉大好き`を選ぶと思います。

- `Radiation` と `Radical`
多用されている掛け言葉ですが、これも非常に訳すのが難しいです。`Radical` はスラングなので意味がふわふわしていて余計に。
今のところ何も思いつきません。

**Comment by denev-rove** [comment]
- `Red Light, Green Light`
本当なら私も`赤信号、青信号`と訳したかったのですが、なにしろゲーム中の論理信号(真)の色が紛れもない緑色なので、断念しました。青色と緑色を区別しないのは、日本文化の特徴のようです。

- `To Pay the Bills`
`手に職`は実績の達成条件がとても分かりやすくて良いと思います。あとは、原文の`生活費を稼ぐ`という意味合いから離れてしまう点をどう判断するかですね。
もともと技能の習得を「生活費を稼ぐために」と表現するのは少し迂遠すぎてピンとこない感じはあったので（英語だと自然な表現なのでしょうか？）、そこを割り切ってしまうなら、変える価値のある案だと思います。

**Comment by nsk4762jp** [comment]
`Some Rservations` は自然保護区を確保する実績であり、`Reservation` が「保護区」、`Some Reservations` で「いくつかの保護区」「ちょっと心配」という意味であることから、実績名は `自然を残そう` といった感じになるのではと思います。

コロニー開発で自然が無くなることについて `Some Reservations` してるのかなと思ったのでこんな訳にしてみました。

**Comment by souki-tn** [comment]
**Carnivore**
これを「お肉大好き」と翻訳するのには違和感があります。理由としては以下の3点。

1. Carnivoreの意味の中心は「肉食動物」「肉食獣」であり、副次的な意味の言葉を採用するには何かしらの根拠が必要だから
2. キリスト教系の世界観では人と動物はかなり明確に分けられる存在なので、動物に例えるということは「人としての標準からの逸脱」「人間離れしていて普通じゃない」というニュアンスを含むはずなので熱烈に肉が好きとか肉狂いとかそういう領域にある言葉のはずだから
3. 「お肉大好き」であれば They love Meat でいいところを Carnivore という単語を選んだ理由を探らない限り、そこに発生する意味の差分がごっそり抜け落ちることになるから

ということで、ちょっと深掘りしてきました。

実際の用法としては下のような例文が出てきました。
I made mostly vegetarian food but put a couple of meat dishes out for the carnivores (= people who eat meat).
出典：https://dictionary.cambridge.org/ja/dictionary/english/carnivore

例文からも分かる通り、ベジタリアンの文脈で使われるもののようです。
肉が好きな人というのは意味として間違っていないものの「（ベジタリアンから見て不道徳な生活スタイルである）肉が好きな人」という意味なのだと思います。正しい人のあり方からの逸脱という意味合いも含めての揶揄した表現ということでしょう。

「お肉大好き」と訳すのはこのコンテクストを前提とすると翻訳として正しくはないですね。
「肉食動物」で正しいかというとそれもまた違いそうです。日本語の肉食動物にはベジタリアンの主張としての意味合いがほとんどないので翻訳として不適格になるかなと思います。

意味の上でストレートに訳すなら「ベジタリアンの敵」ってことになるでしょうがラジカルすぎますね。
「菜食主義者」の反対の意味なので「肉食主義者」というのを造語的に使うと意味合いが近いと思います。

と思って調べていたら下のような記事が出てきました。
https://plaza.rakuten.co.jp/itasan85/diary/201905180001/
ブログなので信憑性のほどはわかりませんが、「肉食主義者」あたりが「菜食主義者」のパロディとしての位置付けが日本語でもわかりやすいので良いのではないかなと思います。

逆に「草食動物」を意味する herbivore はそっちの界隈でそれなりにポジティブに使われているようで、日本のベジタリアンやビーガンのレストランの名前に使われていたりするようです。
辞書の例文になる程度にこの対応関係が人口に膾炙している表現だということなのだと思います。そこを意識しないで実績名に使ったということはないでしょうから、私としては「肉食主義者」が適切な訳ではないかなと思います。

**Comment by souki-tn** [comment]
**To Pay the Bills**
この表現について、この表現を含む定型表現があるようです。
She's got the skills to pay the bills.
出典：https://nic-english.com/phrase/got-the-skills-to-pay-the-bills/
「彼女はそれで食べていけるほど有能だ。（芸は身を助く）」という翻訳がついています。

この実績は get the skill のタイミングで出る実績なのでこの表現を意識しているというのは間違い無いのではないかなと思います。
そうすると実績名は「芸は身を助く」あたりが締まりが良さそうですが、日本語の芸って余技のニュアンスがあるんですよね。
意訳を強めに入れるなら「稼げる特技」とかでも良いかもしれません。

**Comment by souki-tn** [comment]
**Critter Whisperer**
地上波放送の番組「[ムツゴロウとゆかいな仲間たち](https://ja.wikipedia.org/wiki/ムツゴロウとゆかいな仲間たち)」の放送期間は1980年12月29日から2001年3月18日らしい20年以上前...
ムツゴロウさんを誰でも知っているとして扱うのはそろそろ難しいのではないでしょうか。（あとご存命の方の呼称をそのまま使うのに抵抗がある）

海外の映像コンテンツのシリーズに Dog Whisperer というものがあるらしく、それの日本語訳は「ザ･カリスマ ドッグトレーナー ～犬の気持ち」というものになっていました。仕事で日本語訳を作る人も苦労していそうです。
翻訳としてはやや苦しいところですが「カリスマトレーナー」と訳すのはどうでしょう。

**Comment by denev-rove** [comment]
- `Some Reservations`
これも掛け言葉だったとは思いませんでした。
心の一部を占めるもの、という意味合いなんでしょうか。
日本語の「心残り」と似てると思いました。
`自然を残そう`というのは、実績の達成条件が分かりやすくて良い案だと思います。

**Comment by souki-tn** [comment]
**Home Sweet Home**
現在の翻訳は「楽しい」という訳語を使っていますがこれは少し違うかなと思います。
長旅などから家に帰り着いて、自宅の良さを再認識したときの口語表現ということになりそうです。（[参考](https://jp.blog.voicetube.com/daily/home-sweet-home/)）
「居心地が良い」「落ち着く」「安心できる」という意味合いが強そうです。

そうすると「楽しい」というのはやはり違っていて（家より旅行の方が当然楽しい）、それでも自宅が良いという意味合いになります。
「我が家が一番」なんてのが良さそうです。

**Comment by souki-tn** [comment]
** That's Rad!**
翻訳案「平常運転」
原子力発電所の場合は用語として「通常運転」なのですが、自然体でさらりとこなす様子を表現するとなると「平常運転」というのが意訳としていけるかなと思います。

**Comment by souki-tn** [comment]
**GMO A-OK**
元ネタではないですが、日本語の方に元ネタを入れる形で「どんと来い、遺伝子組換え作物」ってどうですかね。
特定の年齢層の人が笑ってくれそう。

**Comment by nsk4762jp** [comment]
Bed and Bath の元ネタは [ベッド・バス・アンド・ビヨンド](https://ja.m.wikipedia.org/wiki/%E3%83%99%E3%83%83%E3%83%89%E3%83%BB%E3%83%90%E3%82%B9%E3%83%BB%E3%82%A2%E3%83%B3%E3%83%89%E3%83%BB%E3%83%93%E3%83%A8%E3%83%B3%E3%83%89) なんじゃないかな、って気がします。

> ベッド・バス・アンド・ビヨンド（英: Bed Bath & Beyond, Inc.、NASDAQ: BBBY）は、1971年に設立され、今日ではアメリカ合衆国とカナダで地域雑貨小売店チェーンを展開している。ほとんどの商品は中級品だが、高品質の地域限定商品も扱っている（寝室、浴室、台所、そしてダイニングルーム用商品）。S&P 500のメンバーである。

**Comment by nsk4762jp** [comment]
Easy Livin' は[ジャズの有名ナンバー](https://enjoyjazzlife.com/easy-living)に似ていますが、名前を借りただけなのかも。

**Comment by souki-tn** [comment]
**Red Light, Green Light**

[レッドライト・グリーンライト - テレビ朝日](https://www.tv-asahi.co.jp/red-green/#/)
テレビ番組名でも使われていたらしい（見たことはありません）。
「レッドライトは止まれ、グリーンライトは進め」というのが掟というテーマとのこと。
元ネタがダルマさんが転んだであるのでかなり意訳も込めて「レッドライトは止まれ、グリーンライトは進め」にしてしまうのも良いと思います。

**Comment by souki-tn** [comment]
**Job Suitability**

Job Stability + Suit = Job Suitability という言葉遊びだと思います。
Job Stabilityは職の安定性、仕事の継続性、安定雇用と言った意味です。
そこにSuitを継続利用するという意味で実績解除条件が作られているのだと思います。
Job Suitability自体は職業適性という感じの意味だと思います。

さてどう訳すかですが、考えておきます。

**Comment by souki-tn** [comment]
実績名修正しました。→ #280

原文 | 旧日本語訳 | 新日本語訳
-- | -- | --
To Pay the Bills | 身を立てるため | 手に職
Down the Hatch | ハッチダウン | ハッチに乾杯

**Comment by nsk4762jp** [comment]
何か新しく実績が追加されたらまた issue を立てるということで、ここは一旦クローズしておきます。
（DLCは出さないって言ってるので追加される見込みはなさそうですが...)
