### ISSUE TITLE
Manufactured Materialの翻訳について

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#271]
現在「人工素材」という翻訳がついているのですが違和感があり修正を発案します。
違和感の中心は、精錬金属なども天然素材とは言いづらく、間違いなく人工素材であり、それらが含まれないにもかかわらず、人工素材という名前を選択している点です。

Manufacturedは「（工業的に）人の手を加えられた」という意味なので、人工も間違っているとは言いにくいところがありますが、ゲーム的に適訳ではないと感じています。

定訳の定まっているものだとManufactured Foodが「加工食品」になります。
Manufactured Materialには天然素材を一次素材として、「二次材料」という翻訳もあるようです。対応する原料としての Raw Material が必ずあるという対応関係があります。（Google検索では幼稚園児向けと思われる画像資料が大量に出ます）

element/solid.yamlを参照してこのカテゴリーの物質を列挙すると

- elementId: EnrichedUranium
- elementId: Glass
- elementId: Polypropylene
- elementId: SolidSuperCoolant
- elementId: SolidViscoGel
- elementId: Steel
- elementId: SuperInsulator
- elementId: TempConductorSolid

これらのようです。超冷却剤とビスコゲルを含むカテゴリーということで「素材」という翻訳を採用するのも違和感のあるラインナップです。固体限定なので滅多にお目にかかることはないでしょうけど。

他のゲームで Manufactured Material をどう処理しているかを確認していたところ、「Elite:Dangerous」でも Manufactured Material が存在し、そちらでは「製造品」という定訳が与えられていました。[出典](https://elitedangerousjp.swiki.jp/index.php?MANUFACTURED)

そこで「製造品」「加工品」あたりを翻訳として使うのはどうでしょうか。
「加工材料／素材」にすると「加工に使う材料／素材」と読めてしまうので、加工されたものという意味合いを使うのであれば「品」を使って示せるのではないかと思います。

**Comment by nsk4762jp** [comment]
最近は何というか `羹に懲りて膾を吹く ` といった感じで名称変更はしり込みしがちです。

#266 にも書きましたが「間違ってはいないが適訳ではない」レベルだと変えることによるデメリットの方が大きそうです。
過去にやった `Wrangler` の `懐柔/間引き` → `縄掛け` のような「明らかに間違っている/誤解を招く」レベルのやつだとメリットの方が勝るので良いんですが...。

**Comment by souki-tn** [comment]
その気持ちはよくわかりますし、そうだと思うのですが、新しい翻訳でおかしなものは定着する前に修正したいという趣旨になります。
定着したらそれこそ変えようがなくなります。
なんなら「既製材料」に戻すのも良いとは思います。（これも良い訳だとは思いませんが、Wikiなどには定着しているので）
毎週200サイクル程度遊んでいる身としては気になるのですよね。

Rimworldで「癒し根」をやったやつだから注意という話が私のところに来ているような状態なので、今触る分には比較的プレイヤーコミュニティの理解も得られやすいと思いますよ。

**Comment by nsk4762jp** [comment]
あー、なるほど、そういうことでしたか。定着する前に直したいのであれば賛成です。

製造品だとちょっとざっくりしすぎなので `加工品` が良さそうですね。

**Comment by denev-rove** [comment]
翻訳ポリシーでは、`material`の訳語は`素材`となっていますし、現にほぼ`素材`で統一されているので、`加工素材`ではどうでしょう。
ガラスも鋼鉄も最終製品ではないので、`material`の意味合いは残したいです。
例に挙がっている`加工食品`も「加工に使う食品」ではなく「加工された食品」という意味なので、誤解の余地は薄いと思います。

**Comment by denev-rove** [comment]
固体の`超冷却剤`や`ビスコゲル`のことまで考えるなら、`加工物質`でもいいと思います。
いずれにせよ、何らかの構造を持った完成品なのではなく、元素や物質の特性に意味のあるものが分類されたカテゴリだと分かるような表現にしたいという意図です。

**Comment by souki-tn** [comment]
海外の工学書に「Advanced Materials Processing and Manufacturing」というものがあるようです。
Manufacturingした結果Advanced Materialsが得られるという表現はそこまで違和感がないのではないかと思います。

翻訳が難しいので実際は違いますがManufactured Materials＝Advanced Materialsとしてもこの場合違和感はないのではないかと思います。
Manufactured Materialsの方はAdvanced Materialsよりは低級の素材という位置付けだとは思います。

Advanced Materialsだと材料工学の論文雑誌の名前にあります。
Advanced Materialsだと定訳は「先端材料」らしいのですが、翻訳に採用するには流石に飛ばしすぎだと思うので、Advanced Material Businessの定訳である「機能材料事業」の「機能材料」と翻訳するのはどうかなと思いますがどうでしょうか。

**Comment by nsk4762jp** [comment]
[機能材料](https://kotobank.jp/word/%E6%A9%9F%E8%83%BD%E6%9D%90%E6%96%99-1523598)

> 特定の有用な機能をもつ材料の総称。

とあるのでまあ妥当かなと思います。用途不明な `人工素材` よりも何かしらの役に立ちそうな名前ですしね。
