### ISSUE TITLE
「Fast Friends」アップデート準備ディスカッション

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#277]
新アップデート「Fast Friends」のテスト版が公開されました。
https://forums.kleientertainment.com/forums/topic/140002-game-update-public-testing-506365/

新要素が多くあり、特に名詞の準備だけは先にしておかないと翻訳に困りそうなアップデートですのでイシューを立てました。

翻訳を考えた方が良さそうなものを一覧にしておきます。追加があれば順次追加します。

- Pipの変種
  - [ ] Cuddle Pip
- Shove Voleの変種
  - [ ] Delecta Vole
- Pokeshellの変種
  - [ ] Sanishell
  - [ ] Oakshell
- 複製人間
  - 人名
    - [x] Amari
    - [x] Pei
    - [x] Quinn
    - [x] Steve
  - ストレス反応
    - [ ] Banshee
    - [ ] Yodeler
- 服装
  - 設備
    - [ ] Clothing Refashionator
  - 衣類アイテム
    - [ ] Purple Polyester
    - [ ] Classic Cummerbund
    - [ ] Snazzier Red Suit
    - [ ] Snazzier Blue Suit
    - [ ] Snazzier Green Suit
    - [ ] Snazzier Violet Suit
    - [ ] Pompom Knit
    - [ ] Citrus Spandex
    - [ ] Cubist Knit
    - [ ] Spiffy Overalls
    - [ ] Pinstripe Waistcoat
    - [ ] Smoking Jacket
    - [ ] Confetti Suit
    - [ ] Midnight Velour
    - [ ] Blue Velour
    - [ ] Bubblegum Velour
    - [ ] Pink Unitard
    - [ ] Primo Garb
- 食料品
  - [ ] Tonic Root
  - [ ] Curried Beans
  - [ ] ~Cooked Sea Meat~
  - [ ] Radiation Resistant: Aquatic Diet

**Comment by nsk4762jp** [comment]
- 追加動物の詳細は [こちら](https://forums.kleientertainment.com/forums/topic/140028-info-feedback-on-new-critters/)
- Banshee の症状については [こちら](https://forums.kleientertainment.com/forums/topic/140002-game-update-public-testing-506365/?do=findComment&comment=1567709) : ストレスが70%を超えると、作業開始時に金切り声を挙げるようになる

**Comment by souki-tn** [comment]
Pokeshell系はPokeshellも含めて翻訳変更が必要かもしれませんね。Pokeは突っつくとかチョンチョンとかなので、「どつきガニ」とかの意味なんですよね。

まずは楽そうな人物系を確定させましょう。人名はそのままカタカナで良いと思います。
上で謎だったPeiさんは中国系で良いようです。ペイさんで良いはず。

Bansheeは「バンシー」で良いでしょう。
海外ゲームにはちょくちょく出てくる存在ですが、日本での定着状況がちょっと未知数です。
画像検索をすると、遊戯王のカードにあるのと、魔法使いの嫁のキャラクターの来歴にあるのと、ぷよぷよのキャラクターにトリオザバンシーがあるぐらいでしょうか。ヤマハのバイクにもあるようですね。
妖怪図鑑とかには普通に紹介される存在なので、このゲームのプレイヤーならわかると信じて良いと思います。

Yodelerは「ヨーデル」か「ヨーデルの歌い手」あたりでしょうか
「ヨーデル歌手」にしてしまうと、プロの職業というニュアンスになるので原語の意味とはずれると思います。
特性「ヨーデル」で意味は通じる気がします。ただ、他の特性との並びがちょっと良くない気がします。
他の特性を見ていると人物説明的なものではなくタイトルコールのような言葉の選び方なので「ヨーデルの歌声」とかかなぁという感じです。

まとめるとこんな感じですね。
Amari - アマリ
Pei - ペイ
Quinn - クイン
Steve - スティーブ
Banshee - バンシー
Yodeler - ヨーデルの歌声

Tonic Rootの元ネタだと思われるのはGinger Rootという音楽ユニット。
管理用のIDでの名前はそのままGingerなので多分そう。

**Comment by nsk4762jp** [comment]
Tonic Root 自体が[音楽の用語](https://ja.m.wikipedia.org/wiki/%E3%83%88%E3%83%8B%E3%83%83%E3%82%AF%E3%82%B3%E3%83%BC%E3%83%89)みたいですね。Ginger なのは見た目が生姜に似てるからだと思ってます。
Curried Beans の材料の一つですが、生姜で豆カレーってのも「？？？」といった感じです。

**Comment by souki-tn** [comment]
Tonicそのものはキナノキの樹皮から出た抽出物なので、そっち系のスパイスのニュアンスでしょうね。シナモンとかも植物の皮ですし。
キナノキには薬効があるので強壮薬という意味に派生しているので、漢方っぽい名称に翻訳するとニュアンスが近い気がします。

**Comment by souki-tn** [comment]
非常にアグレッシブな翻訳になりますがTonic Rootに「強壮ウコン」とかありでしょうかね。
ウコンの「コン」は「根」ではないのですが、音で引っかけてます。

**Comment by souki-tn** [comment]
SnazzierとSpiffyの訳しわけが難しいと思っていたのですが、そのものの比較ページがありました。
[Spiffy vs Snazzy - What's the difference?](https://wikidiff.com/snazzy/spiffy)

服装に関する形容詞なので意味としてはこんなところのようです。
> Spiffy:
> (informal) Dapper; fine or neat, especially in style of clothing or other appearance.
> Snazzy:
> (informal) Elegant in manner of dress; stylish, modern or appealing in appearance; flashy.

Snazzyの方のシノニムにDapperがあったりと、根本的にはかなり近い言葉のようです。

比較をすると、Spiffyの方は特別に服が良いというのが意味の中心で、Snazzyの方は着こなしがスタイリッシュで目立つという方向なのかなと思っています。

そうするとSnazzierを「小粋な」、Spiffyを「イケてる」と翻訳するのが近いのかなと思っています。（この辺は難しい）

**Comment by souki-tn** [comment]
Snazzyの語源について
> Unknown but perhaps a blend of snappy +‎ jazzy, or from Irish snas (“polish; good appearance”).

とのこと。snappyはおしゃれでかっこいいという方向性の言葉で、それプラスJazzyなので、ステージ衣装のようなニュアンスの様子。

**Comment by nsk4762jp** [comment]
ステージ衣装ですか。
お洒落でカッコいいステージ衣装なら Snazzy は `ゴージャス` ってところでしょうかね？

**Comment by souki-tn** [comment]
うーん、どうなんでしょう。日本語の「ゴージャス」は比較的奇抜な服装のニュアンスを含んでしまいます。成金趣味的な感じのやつです。おそらくそっち方向ではない言葉ですね。
"Elegant in manner of dress" という意味が一番最初にあるように、比較的硬めな服装で、結婚式に参列する際にふさわしいような方向性だと思います。Jazzのステージ衣装は結構フォーマル寄りなのでそこら辺もあるのでしょう。言葉としてそのまま使うなら「エレガント」でしょうか。ただ、Snazzyは口語表現らしいので「エレガント」と口で言うかというと日本語だとあまりない気がする。
「パリッとした服装」というのが言葉として近そうですが、ゲーム内の言葉としては持ち込めないですね。

**Comment by nsk4762jp** [comment]
ご参考までに現行だと `Snazzy Suit` は `おしゃれスーツ` になっています。
それの上位版なので `Snazzier XXX Suit` も `上品なXXXスーツ` (口語的に 上品 と当ててみました)というのも一案です。

**Comment by souki-tn** [comment]
「上品」も良い訳語ですね。
ただ「上品」はClassicの方に使いたいです。
Classicも相当に翻訳に困る言葉だとは思います。日本語で「古典的」というと古臭いというネガティブイメージが出ますが、Classicの意味の根本は「最高級に良いもの」という意味なので「上品な」を当てると誤魔化せるかなと思いました。
Classic Cummerbundを「上品なカマーバンド」と翻訳した方がいいかなと思います。
（`She is so classic`が褒め言葉として使われるというのに昔衝撃を受けました）

**Comment by nsk4762jp** [comment]
カマーバンドって初めて聞きましたが、腹巻の礼服バージョンなんですね。
カマーバンド自体がフォーマルな場で使われるみたいなので `Classic` が付くのも納得です。
ただ、礼服なので上品なのは自明な気がします。`正統派カマーバンド` とかにするとちょっと弱いかな。

**Comment by souki-tn** [comment]
「正統派」はどちらかと言うと善悪に属する言葉だと思います。Classicは良し悪しに属する言葉だと思うのでそこに意味のズレがあるのが気になります。
フォーマルファッションには明るくないのでカマーバンドにアレンジの幅というものはあるのでしょうか。幅がないとすると「正統派」というのも何か違う気がします。正統派のネクタイというものは成立しますが、邪道なネクタイが世に溢れるので成立する気がしています。カマーバンドに邪道はあるのだろうか。

別の案として、Classicに「由緒ある」という訳語を当てるとポジティブかつ伝統的なニュアンスで良さそうだとも思ったのですが、由緒ある新品の服というのは日本語だとおかしいですね。由緒ある製法で作られた衣装を由緒ある衣装とは言わないように思います。由緒あるユニフォームと言う言い方は可能ですが、由緒ある（配色とデザインの）ユニフォームと勝手に補っている気がします。
その点「正統派」は正統派の新品の服というものが成立するので語としては良いんですよね。

「カマーバンド」というものを日本人プレイヤはほとんど知らないと思うので、それでもフォーマルで良いものってニュアンスにしたいですね。Cummerbundに「カマーバンド」以外の訳語は当てれそうにないしなぁ。悩みどころですね。

**Comment by nsk4762jp** [comment]
[カマーバンド - Wikipedia](https://ja.m.wikipedia.org/wiki/%E3%82%AB%E3%83%9E%E3%83%BC%E3%83%90%E3%83%B3%E3%83%89)

どうやら柄物もあるようで、蝶ネクタイとセットで販売されているみたいですね。

> 正式な物は黒とされるが、軍服では赤（例：アメリカ海兵隊）やオレンジ（例：陸上自衛隊）等の色も見られる。

ということなので（ゲーム中に出てくるカマーバンドが黒かったら）「正統派」もあながち間違いではないのかもしれません。

**Comment by souki-tn** [comment]
カマーバンドは準礼装（セミフォーマル）の一部なので、さらに格式の上の正礼装（フォーマル）があるにはあるんですよね。
セミフォーマルが正統で良いのかなぁ。

「正統派」は分かりやすさは素晴らしいのですが、「正統派」だけどダサいは成立してしまうのです。
orthodoxではなくclassicという言葉を使われている以上、カッコいいアイテムというニュアンスは混ぜ込みたいです。

**Comment by souki-tn** [comment]
Sanishellについて
> The first obvious usage for the Sanishell is removing germs.

とのことなので「衛生ガニ」という意味で、sanitary shellからの造語で間違いなさそうです。翻訳は悩みますね。

**Comment by nsk4762jp** [comment]
落としどころとして、Classic は `上品な` にしますか。
Snazzier も当初案の `小粋な` もしくは(Refashionatorによって) `洗練された` ですかね。

**Comment by souki-tn** [comment]
このゲームのポップ感から考えるとSnazzyを「おしゃれ」と翻訳した上でSnazzierを「もっとおしゃれ」と翻訳してしまうのもアリな気がしてきました。
下手に翻訳をいじりすぎると`Snazzy Suit`の方の翻訳を変えないと整合性が崩れそうなので、そこを崩さないということを優先すると`Snazzier Red Suit` を「赤のもっとおしゃれスーツ」という翻訳にしてしまうのもアリではないでしょうか。
英語の方ではアイテムの上位下位が分かりやすいので、そこを翻訳には反映させるべきですし、これぐらいのポップな翻訳がこのゲームに合う気がしてきました。このゲームのプレイヤーなら分かってくると信じたい。

**Comment by souki-tn** [comment]
没案ですが、言葉遊び的に気に入ったので書いておきます。ゲームに反映させたら絶対に大ブーイングになります。絶対に目が滑る。

> Pokeshell: きらいきらいガニ
> Sanishell: きれいきれいガニ
> Oakshell: きるいきるいガニ

**Comment by ujihisa** [comment]
> Cuddle Pip

直訳に近い、"抱擁ピップ" (前述)、"抱きしめピップ"、"なでなでピップ"、など素直な名前がよさそうです。孵卵器に対して行う子守唄とはまた別ですね。


(余談ながら、pip (種) には植物の種や動物の卵など、生物の増殖を司る役割が与えられているようにみえます。病原菌も生物と考えると、以後そちらの方向性の変異種も作られるのかなーなんてぼんやり空想しています。)

> Amari

アクセントが最後から二番目の母音にくるパターンなので、アマリではなくアマーリになりそうです。

**Comment by nsk4762jp** [comment]
Cuddle は我々に馴染みがありませんが Hug ならまあ通じるでしょうってことで `はぐはぐピップ` というのを腹案で考えていました。[Cuddle と Hug は厳密には違う](https://web-trans.jp/blog/%E6%8A%B1%E3%81%8D%E3%81%97%E3%82%81%E3%82%8B%E3%81%AFhug%E3%81%A7%E3%81%84%E3%81%84%E3%81%AE/)みたいですが...。


ひらがなだとカイジが焼き鳥食べてるシーンを想像してしまうのでカタカナ表記の方がいいかもしれません。

**Comment by souki-tn** [comment]
Cuddle Pipは「だっこピップ」というのを考えていました。
抱擁は他の動物の名前に比べて固すぎるんですよね。

Amariさんはイギリスのサッカー選手のアマリ・ミラーが元ネタだと思っています。
日本語での記述は「アマリ・ミラー」のようです。
発音の音声データは「[アマリ](https://kanji.reader.bz/celebrities/name/アマリ)」に聞こえます。
英語由来の名前ではないのかもしれませんね。

**Comment by denev-rove** [comment]
> Sanishell
> Oakshell

`Pokeshell`を`どつきガニ`にするのは、ゲーム内の挙動が分かりやすくなって、とてもいいアイデアだと思います。（「どつく」という動詞もユーモアがあって、ゲームの雰囲気にぴったりだと思います）

`Sanishell`（液体中のGermsを死滅させる）と`Oakshell`（脱皮した殻を岩石粉砕機で砕くと木材になる）は、意味としては各々`殺菌ガニ`、`樹皮ガニ`くらいになりそうです。ただ直訳すぎて風情がないので、できれば`ごつごつ`とか`ふさふさ`みたいな擬音語（擬態語）にできれば理想的なんですが、難しいですね。

> Primo Garb

`Garb`といえば[Wizardry](https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A3%E3%82%B6%E3%83%BC%E3%83%89%E3%83%AA%E3%82%A3)の`Garb of Lords`が思い浮かびますが、意味としては単に「衣裳」「服装」といった抽象名詞のようです。直訳すれば`最高級の衣裳`になりますが、簡単に`高級衣裳`とかでいいかと思います。（今後、これ以上の衣裳が実装されないとも限りませんし）

これは`Clothing Refashionator`を使って仕立て直した衣裳を総称する言葉のようです。（データベースの`Clothing Refashionator`の頁には、`Primo Garb`を成果品とするレシピが幾つも並んでいます）
実際に生成した衣裳アイテムには、`Primo Garb`ではなく、個々の衣裳名（`Classic Cummerbund`とか）が付きました。

> Purple Polyester
> Citrus Spandex

`Spandex`というのは、日本ではあまり馴染みがないですが、`ポリエステル`と同じく、人工繊維の名称のようです。対応する日本語があるはずもないので、そのまま`スパンデックス`とするしかないように思います。

`ポリエステル`も`スパンデックス`も、日本語では繊維の名前にしかならず、衣裳の名前としては違和感があります。
かといって、言葉を補って`紫のポリエステル製の衣裳`などとすると、さすがに冗長すぎると感じます。
ここは短く`紫のポリエステル`と直訳してしまって構わない気がします。（「製の衣裳」の部分はプレイヤーの脳内で補ってもらう）

**Comment by souki-tn** [comment]
**Amari**
追加で少し調べましたが「アマーリ」という翻訳もありました。
https://www.名前の意味.com/n/Amari
女性名の場合は「アマーリ」男性名の場合は「アマリ」のようです。
ゲーム内のグラフィックは男性なので「アマリ」で良いと思います。
（余談ですが、このゲームの人名はカミーユのように両方の性別に使える中性的な名前が多めです）

**Sanishell**
直訳すれば「衛生ガニ」になると思います。
ゲーム内での特徴は大きく2つあります。
・水の中の菌を殺菌する
・死んだ際に食糧になる
pokeshellと対比して衛生的だという扱いです。（pokeshellは不衛生で食べられないということです）
現実で言えば「無菌豚」に近い概念な気がしますね。

**Oakshell**
Oakは日本語では楢木や樫の木のことですが、オーク材として建材としてのイメージが強いようです。
日本語でも「ヒノキ」と言われたら、樹木ではなく角材をイメージしますがそれに近いのでしょう。
良い翻訳が思いつかないので、ヤシガニならぬ「カシガニ」というのがどうかなと思っています。

**Polyester/Spandex/Velour**
素材名のものはその素材を使った典型的な服装という意味合いがあるのだと思います。
日本語では少ないですが「カシミア」あたりは「カシミアを着てきたんです」と言ったら間違いなくカシミアコートという解釈になるのと似たようなところでしょう。
Polyesterは「ポリエステルシャツ」、Spandexは「スパンデックスウェア」、Velourは「ベロアローブ」あたりになるのかなとおもっています。
ゲーム内のグラフィックをまだ確認してないのでもっと適切なのがありそうです。後ほど修正入れると思います。

**Comment by souki-tn** [comment]
Oakについての言葉の背景についての情報です。
[Acorn - Wikipedia](https://en.wikipedia.org/wiki/Acorn)を参照すると下のようになってます。

> The acorn, or oaknut, is the nut of the oaks.

Arbor TreeのタネはArbor Acornなので、暗黙に繋がりがあるという言葉を選んでいるようです。

**Comment by denev-rove** [comment]
`Snazzier XXXX Suit`の訳についてですが、`Snazzier`が比較級であることから、ゲームシステム上`Snazzy Suit`(`おしゃれスーツ`)の上位版であることを表現しているのは間違いないと思います。
一方で、英語の比較級は、比較対象が具体的でなくとも（一般的な水準と比べて、よりおしゃれ、のような感じで）使われることもあるため、下位版の`Snazzy Suit`の存在を知らない人が見たとしても、単体のアイテム名として違和感なく成立しています。

日本語でも同様に（比較対象を想定しない）単体のアイテム名としても成立するよう、`おしゃれすぎる`という訳を考えてみました。
一時期ネット上で「美人すぎる〇〇」といった表現を見かけましたが、同じような用法です。一種のスラングですが、もともと`Snazzy`がinformalな単語なので。

ポイントは次の2点です。
- `Snazzy Suit`の上位版であると分かる
- `Snazzy Suit`を知らない人が見ても意味が通じる

**Comment by souki-tn** [comment]
Snazzierを「おしゃれすぎる」と訳すのには違和感があります。
「〇〇すぎる」という言葉はネットスラング発祥ではなく週刊誌とかワイドショーとかの煽り文が発祥だと思います。ちょっとその界隈の言葉というのはこのゲームとの相性が良くないのではないかと思います。このゲームに品があるとは言いませんが、品のなさの方向性が小学生男子が好きそうな方向だと思います。週刊誌的な下世話さはゲームの雰囲気に合わない気がします。
週刊誌的な使い方の「〇〇すぎる」煽り文の用法には「〇〇」に入るものに制約があります。過剰がない、過剰であっても困らないものにしか使われません。過剰に美人は困りませんし、スポーツで強すぎるというのも言いますが、これも過剰に強いのは困りません。面白すぎる〇〇というのも、電車内で読めないものかもしれませんが困りません。
それに対して「おしゃれ」は過剰があります。「おしゃれすぎるスーツ」はTPOを弁えていない服装という意味になります。
アイテム名はその単体で意味が通った方が良いと思うので、解釈の幅が大きすぎる訳語は相応しくないと思います。

**Comment by souki-tn** [comment]
**Curried Beans**
Bean CurryではなくCurried Beansなので「豆カレー」は適切な翻訳ではないということになるのだと思います。
なので「豆のカレー煮」「カレー煮豆」あたりの正しい翻訳になるのではないかと思います。ただ、オーブンでの料理のようなので「豆のカレー粉焼き」という方向でも良いかもしれません。

**Comment by nsk4762jp** [comment]
商品的にはカレー風味の豆水煮ってとこでしたね。

[Heinz | Curry Beanz](https://www.heinz.co.uk/beanz/flavoured/product/100185200043/curry-beanz)
[Batchelors Curried Beans](https://www.batchelors.ie/products/beans/curried-beans/)

無理に翻訳せずとも、そのままカレービーンズで通じる気がしてきました。

**Comment by souki-tn** [comment]
**Curried Beans**
豆カレーではないので缶詰のイメージになりますね。
カレー味ではないですが、アマゾンのレビューにこのアイテムの立ち位置を正確に表現していそうなものがありました。

- [うんざりした顔で飯を食う米兵になりきれる](https://www.amazon.co.jp/gp/customer-reviews/R13WRQWWCH1UU7/) ハインツ (Heinz) ベイクドビーンズ

ハイスクールのカフェテリアとかで缶詰の豆料理が出てくると _うげっ！_ ってなるという文化的な前提があると予測しています。
軍用レーションの豆の缶詰が美味しくないってことが(少なくとも映画や小説では)定着していてそこに乗っかっている感じでしょう。 (高校生はそういうのをよく真似するお年頃)

私の印象では「カレービーンズ」はスナック菓子のような、それこそ柿ピーのような美味しいイメージが湧きます。もうちょっと不味そうな名前にしたいです。

**Comment by nsk4762jp** [comment]
今週の金曜日辺りにアップデートが来そうなので、そのタイミングでブランチを切ります。
ブランチ名は `fast-friends-update-ビルド番号` になる予定です。

**Comment by souki-tn** [comment]
**Cuddle Pip**
「だきつきピップ」というのを考えています。
他の動物がひらがな2文字繰り返しになっていますので、そこに最低限「き」の繰り返しで合わせる形です。

**Delecta Vole**
「うまうまネズミ」以外できませんでした。対案求む。

**Pokeshell**
1. とりあえず音そのまま案
Pokeshell: ポークシェル
Sanishell: サニシェル
Oakshell: オークシェル
メリット：既存のポークシェルがそのまま移行できる。
ディメリット：名前から活躍の場面が分かりづらい。オークは日本語のイメージは亜人の方に引っ張られるのでそこは微妙。

2. 音そのまま＋コウラ案
ポークシェルとしたままだと変種に対応できないので、「〇〇ガニ」系への切り替えが必要だとは思います。
「〇〇ガニ」にしてしまうと、shell が訳出されていない状態になってしまうと思うので「〇〇コウラガニ」にする案を提案します。
Pokeshell: ポークコウラガニ
Sanishell: サニコウラガニ／サニーコウラガニ
Oakshell: オークコウラガニ
メリット：既存のポークシェルからのつながりが一応維持できる。
ディメリット：正直、これを採用するなら1案でいい。

3. 意味を翻訳（ひらがな）＋コウラ案
Pokeshell: どつきコウラガニ
Sanishell: むきんコウラガニ／めっきんコウラガニ
Oakshell: もくめコウラガニ
メリット：生態と機能がよくわかる。もくめコウラガニが個人的にお気に入り。
ディメリット：他の動物との一貫性が弱い。「むきん」が結構苦しい。

4. 手触り＋コウラ案
Pokeshell: つんつんコウラガニ
Sanishell: つるつるコウラガニ
Oakshell: ざらざらコウラガニ
メリット：他の動物名との一貫性ができる。
ディメリット：元々の意味をガン無視することになる。先頭に「つ」が重なるので視認性が悪い。

5. 擬音語＋コウラ案
Pokeshell: ぽこぽこコウラガニ
Sanishell: ぴかぴかコウラガニ
Oakshell: こんこんコウラガニ
メリット：元の言葉に近い範囲で他の動物との一貫性が作れる。殴ってくるぽこぽこと清潔感のぴかぴかはいい感じ。Pokeとぽこの繋がりは一押し。
ディメリット：機能性の表現としてはやや弱い。手触りに比べるとコウラとのつながりが弱い。

6. お気に入りアラカルト案
Pokeshell: ぽこぽこコウラガニ
Sanishell: ぴかぴかコウラガニ
Oakshell: もくめコウラガニ
メリット：私が楽しい。
ディメリット：統一感がない。

**Comment by souki-tn** [comment]
そうですね。ポーク種はそれでよいとして、ピップ変種とぐりぐりネズミ変種はどうしましょうか。
ぐりぐりネズミの方は音をカタカナには難しいかなと思います。
ピップの方は「カドルピップ」になるのかな。字面が馴染みのない感じになります。（個人的には苦手）

**Comment by souki-tn** [comment]
PRが作られ役割を終えたのでクローズします。
