### ISSUE TITLE
Analyze の訳語: `分析` と `解析`

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#299]
文脈によって切り替えるのか、一意に決めてしまうのか悩みどころ。
例えば、遺伝子は `解析` するものだが、Botanical Analyzer は `植物分析機` になっている。

分析と解析の違いについては下記サイトに詳しく説明されている。

[解析と分析の違い！アクセスやデータの場合はどうなる？](https://違いは.net/archives/5805.html)

- 解析
 事柄を細かく分けて、組織的・論理的に調べること。
- 分析
 物事をいくつかの要素に分け、その要素・成分・構成などを細かい点まで調べること。

**Comment by souki-tn** [comment]
化学分野は主に `分析` と呼んでいるように思います。
化学領域で正しいのは成分 `分析` であり、成分 `解析` は誤用に近い扱いになっているように見えます。

逆に数学が絡むと解析になりそう。Analysisは解析学でこれを分析学とば絶対に言いません。
数学から影響を受けて派生しているものは解析〇〇学になっています。

そうは言っても、Multiple regression analysisは「重回帰分析」であり、multivariate analysisは「多変量解析」なので、一貫性があるのかというと難しいもののようです。この辺りは語感で選んでいる気がします。

定訳として統一せず訳し分けがあるのは限界があるかなと思います。
個人的な印象になりますが、特性や性質を明らかにするものを `解析` 、要素や成分を明らかにするものが `分析` となるように思います。
そのため用語の使い分けとして、DNA `分析`であり、遺伝子 `解析` となっています。
そうなると、Botanical Analyzer は `植物解析機` の方が正しそうです。

**Comment by nsk4762jp** [comment]
文脈によって訳し分けるのが仕方ないということが分かりました。
こういうのは単語辞書に載せておかないと翻訳揺らぎの原因になりそうですね。
