### ISSUE TITLE
単語の区切りについて

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#3]
"Super Computer" → "スーパーコンピューター" と訳した時に、画面上は一続きの文字列として認識されるので見切れてしまうことがある。
間にスペースを入れて、(ゲーム側で)適宜折り返してもらうほうが見やすいだろうか。

**Comment by seameteo** [comment]
個人的にはスペースを入れた単語は少しぎこちない感じになるので、必要な時だけ改行・スペースを挿入して対策という形にしたいですね

**Comment by nsk4762jp** [comment]
了解しました。
この Issue はいったんクローズします。
