### ISSUE TITLE
githubのほうも更新お願いします。

### ISSUE THREAD

**Issue by Hage-Jyoutou** [nsk4762jp/OxygenNotIncluded-Japanese#32]
当方の環境ではなぜかサブスクライブでの導入ができないのでこちらを利用させていただいているのですが、この間あったアップデートでの更新分をこちらにも反映していただけないでしょうか？

**Comment by nsk4762jp** [comment]
大変失礼しました。  
Workshopのほうを更新した後にGithub側を更新するのを忘れていました。  
先ほどマスターブランチにマージしたものをリリースしたので、ご確認ください。

**Comment by Hage-Jyoutou** [comment]
わざわざ返信していただいてありがとうございます。
無事に更新できました、ありがとうございました。
