### ISSUE TITLE
衣装の色合いの訳語について

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#324]
| 原語 | 色 | 備考 |
| --- | --- | --- |
| True Blue | 青 |  [True Blue とは](https://ja.wikipedia.org/wiki/TRUE_BLUE)  |
| Underdog | 茶色 | 負け犬、咬ませ犬 |
| Team Captain | 深紅 | |
| Go Team | 緑 | |
| Pep Rally | ピンク | Pep Rally (壮行会、激励会) |
| Hype | レモン | | 
| Superfan | オレンジ | タグにある `SATSUMA` は何故か 温州ミカン を指すらしい |
| Yellowcake | 黄色 | (ウラン粉末の)イエローケーキ |

**Comment by souki-tn** [comment]
https://webmagazine.ouj.ac.jp/kagoshima2206/
薩摩オレンジらしいですね。経緯がなんかまとまってました。
薩摩武士が関わってたらどう訳すか困るところでしたね。「チェストオレンジ」とか訳します？

**Comment by nsk4762jp** [comment]
これもぼちぼち閉じて良さそうな頃合いなので閉じます。
