### ISSUE TITLE
Packed Snacks Update で追加された設備の訳語について

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#355]
#351 アップデートで追加された設備のうまい日本語訳を考える issue

- `Dehydrator`
  食糧から水分を抜いてパック包装する。パック包装された食糧はそのままでは食べることができない。
- `Rehydrator`
  パック包装した食糧に水分を補給して元の食糧に戻す。
- `Critter Condo`
  地上動物の遊び場を提供する。見た目はキャットタワー。
- `Water Fort`
  水中動物の遊び場を提供する。
- `Storage Tile`
  タイルを小さな収納庫として使える。

**Comment by souki-tn** [comment]
調べた範囲の補足。

`Dehydrator`と`Rehydrator`の語幹の`hydrate` は日本語では「メタンハイドレート」ぐらいにしか音では入ってきてない様子。
`hydrate`で動詞では「水分補給」、名詞では「水化物」となる。
イメージでは「水をする」といったニュアンス。
De-は「反対にする」接頭辞、Re-は「元に戻す」接頭辞

`Critter Condo` の`Condo`は`Condominium`の意味。日本の分譲マンションとほぼ同じ意味で使われる。マンション、アパートといった意味が近い。

`Water Fort`の`Fort`は`Fountain`の意味。[Anker Eufy Pet Water Fountain P940](https://www.amazon.co.jp/Fountain-P940（犬・猫用自動給水器）【給水器-モーターとタンクが別-お手入れ簡単-食器洗い機対応ステンレストレイ/dp/B0B51B3ZM8?th=1) というものを見つけてしまった。「犬・猫用自動給水器」と翻訳されてる。「給水器」ありでは？

`Storage Tile`、つまりは壁金庫。

**Comment by nsk4762jp** [comment]
`Water Fort` は水中動物用の遊び場なので、人工岩礁みたいなものだと思います。 
(水中動物に噴水を与える必要はないと思ってます)


```
A fancy respite area for adult <link="CRABSPECIES">Pokeshells</link> and <link="PACUSPECIES">Pacu</link>.
---
成体<link="CRABSPECIES">ポークシェル</link>や<link="PACUSPECIES">パクー</link>のためのおしゃれな休息エリアです。
```

**Comment by souki-tn** [comment]
`aquarium fountain` で検索しても、水中のものは出てこないですね。それっぽいのがあるのを期待したのに。

**Comment by souki-tn** [comment]
`Dehydrated`に「乾燥パック」という訳語を与えました。
その時に思ったのですが、このゲーム色々と名前はふざけたものが多いので`Rehydrator`について「潤い注入器」とかでどうでしょう。
`Dehydrator`は「乾燥圧縮器」とかパック化を意識してもいいかもしれません。
なお戻した食糧を食べると`Rehydrated food`というデバフ(士気-1)が付きます。「水で戻した食糧」としてみました。

**Comment by souki-tn** [comment]
あ、そもそもに作られるのは`Dry Ration`なのか。

**Comment by nsk4762jp** [comment]
- `Dehydrator` と `Rehydrator`
これらは関連する設備なので、訳語もそれに合わせたものにしたいですね。
個人的には「食糧向けであること」「乾燥させること」「水戻し(湯戻し？)すること」の意味合いが欲しいところです。
(原語には「食糧向けであること」がないので抜いてもいいかもしれません)

- `Critter Condo` と `Water Fort`
`Critter Condo` は `動物ハウス` でいいかなと思います。
`Water Fort` の `Fort` は `Fortress`(要塞) の構成要素の一つらしいです。`水中基地` (秘密基地的なノリで) あたりでしょうか。
> 「fort」と「fortress」の違い
> 「fort」と「fortress」はどちらも「砦」や「要塞」という意味であるが、一般的に「fortress」はより大規模で強固な建造物を指す。
> また、「fort」は一時的な防御施設を意味することが多いのに対し、「fortress」は恒久的な建造物を指すことが一般的である。 
[「fort」とは・「fort」の意味](https://www.weblio.jp/content/Fort)

- `Strage Tile`
これは従来の `Strage bin`(収納庫) と揃える形で `収納タイル` で良いと思います。

**Comment by souki-tn** [comment]
なんか勘違いしてましたが、ROOMSの説明では `Critter Fountains` で設備名の方は `Fortress` なのか。これ後日アップデートで統一されそう。

**Comment by souki-tn** [comment]
`水中基地` はOKだと思います。

`Dehydrator` は使うと床が水浸しになるので乾燥よりは脱水が近いと思っています。`脱水パック器`とかだとストレートに機能名かなと思います。
それと対応させると`Rehydrator`は`パック注水器`とかかな。
乾燥レーション以外の生産物が出てくると名前が合わなくなることはありそうですけど。

**Comment by nsk4762jp** [comment]
という訳でこんな感じにまとまりました。

- `Dehydrator` → `脱水パック機`
- `Rehydrator` → `パック注水機`
- `Critter Condo` → `動物ハウス`
- `Water Fort` → `水中基地`
- `Storage Tile` → `収納タイル`

他に何かあったらその都度対応ということで、この issue はマージが終わったら閉じておきます。

**Comment by nsk4762jp** [comment]
取り込んだのでクローズします。
