### ISSUE TITLE
カテゴリ名の「装飾品」で変数の展開に失敗しているテキストがある

### ISSUE THREAD

**Issue by enslo** [nsk4762jp/OxygenNotIncluded-Japanese#362]
![image](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/39163737/31404965-c5e3-4b5e-9d9e-65f9120cb9c5)
![image](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/39163737/4a9cddf9-ab6f-48e2-aa87-09e123bb8fe9)

**Comment by nsk4762jp** [comment]
こちらでは特にやれることもないので一旦クローズします。
Klei Forum のバグトラッカーにも見つからなかったので新たに作り込んだバグかもしれません。
