### ISSUE TITLE
自動化ワイヤーブリッジの説明文が気体ブリッジのものになっている

### ISSUE THREAD

**Issue by enslo** [nsk4762jp/OxygenNotIncluded-Japanese#363]
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/d8cf222fe035d53e42a6c4ce96fa911081caf797/po/buildings.po#L9480-L9488

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

ここの修正をしていたら `<link="GASPIPING">` とすべき箇所が `<link="GASCONDUIT">` となっていた箇所を複数見つけたので合わせて修正します。
