### ISSUE TITLE
浮遊動物誘導餌の説明文に使用されているタグが適切でない

### ISSUE THREAD

**Issue by enslo** [nsk4762jp/OxygenNotIncluded-Japanese#364]
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/3dde857898cc1b3c3bb8275d088aa2f9dcea165f/po/buildings.po#L2216-L2227

![image](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/39163737/70d81a28-4bf1-446c-9a75-4ea2e7adfb76)

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

`<style></style` と `<link></link>` のタグ間違いが他にも無いか斜め読みしてみましたが(漏らしがあるかもしれません)、該当箇所はここだけみたいなので取り込んでおきます。
