### ISSUE TITLE
リボンリーダーの説明文に翻訳前の文章が残っている

### ISSUE THREAD

**Issue by enslo** [nsk4762jp/OxygenNotIncluded-Japanese#365]
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/3a9fbd569bb9fa713c9ad612bc8831f2ab0175a6/po/buildings.po#L9065-L9067

![image](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/39163737/9554b63a-bb24-471f-9e64-b8b75a0e5fea)

**Comment by nsk4762jp** [comment]
どうもありがとうございます。

`Inputs the signal...` の部分は未翻訳ではなく削除漏れでした(後続の日本語文が翻訳文になります)
