### ISSUE TITLE
翻訳案

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#37]
Eiran_Kisotsu[JP]  さん:
> FF外から失礼します、
> 私が気づいた点を列挙します、使えそうなのがあれば採用してください。
> 
> ・施設のタブにある Properties → プロパティ
> 
> ・施設の 「ボトル開け」 → ボトル流し
> ・Only Sweep 、掃除のみ → 掃除指定のみ
> ・Auto Bottling → 勧んで流す
> ・Auto Disinfest → 勧んで消毒
> ・Auto Repair → 勧んで修理
> 「自動」だとオートメーション系の意味と混同されるから
> 
> ・Super Computer → スパコン or ｽｰﾊﾟｰｺﾝﾋﾟｭｰﾀ
> (文字が長すぎてアイコンをはみ出して読めないから、
> 略語か半角カタカナで補う？)
> 
> ・低加熱性 → 低変温性
> (Slow Healing だとゆっくり発熱しているように見える。
> ここは比熱が高いという意味なので意訳すると 低い変温性)
> 
> ・38000 Germs → 38000 「ｼﾞｬｰﾑｽ」 or 「の菌量」
> (とりあえず訳語を当てておきたいかも？)
> 
> ・Compost → 肥え溜め
> ・Sweep、掃除 → 片付け 
> (掃除だと、モップがけも含むような広い意味に解釈される、
> ここは 落ちている固体を拾う という意味を強調して…片付け )
> 
> 変圧機のフレーバーテキスト、
> 変換 → 変身と訳せば適切かも。
> 「シッ、誰も見ていない時に変身 (transform)するんだ」
> これは確か海外のトランスフォーマーか何かの台詞だったと思います。

**Comment by nsk4762jp** [comment]
- **Germs**
これは単位としての記号みたいなものなので、(Kgを「キログラム」と訳さないように)このままとします。  
現実にはない単位なので翻訳されてない箇所と思われがち。

**Comment by nsk4762jp** [comment]
- Only Sweep 、掃除のみ → 掃除指定のみ
これは採用してもいいかも。

- Auto Bottling → 勧んで流す
- Auto Disinfest → 勧んで消毒
- Auto Repair → 勧んで修理
「Auto」「Manual」の対義語翻訳で「自動」「手動」としていますが、機械的自動ではなく複製人間が(指示せずとも)自発的に行うということなので、「自発〇〇」「〇〇指示」という訳語にしても良いかもしれません。

- Super Computer → スパコン or ｽｰﾊﾟｰｺﾝﾋﾟｭｰﾀ
「スーパー コンピュータ」のように間に半角スペース1個を空ければUIの幅に応じて折り返されるはず。

- Sweep、掃除 → 片付け
Clean と Sweep の意味合いの差が分かるような訳語にしたい。

**Comment by seisuke** [comment]
Super Computerはスパコンがいいと思います。

Autoは「適宜」とか「随時」とかが近い気がしますが、難しすぎる単語はよくない気もしてます、
「よしなに」とかもあるんですが、これも微妙かもですね...
自発は「自発的に消毒」が文字数として入るならいいと思います。

**Comment by seisuke** [comment]
スパコンとトランスフォーマーの変身は実装しました。

**Comment by nsk4762jp** [comment]
日本人がイメージするコンポストはプラスチックのデカいドラム型容器なので、ゲーム内イメージとそぐわない気がしました。
そのため今のところ「堆肥置き場」にしてあります。まあでも最近のバージョンで堆肥作らなくなったんでコンポストにしても良いかもしれませんね。

**Comment by nsk4762jp** [comment]
このチケットもだいぶ古くなってきたので一旦クローズとします。
