### ISSUE TITLE
Modが本体の起動時に削除されてしまう現象が起こっている

### ISSUE THREAD

**Issue by oshiro3** [nsk4762jp/OxygenNotIncluded-Japanese#373]
いつも mod 利用させていただいております。
恐らく QoL Update 以降だと思うのですが、本体起動時に下記画面が表示されて Restart を実行すると無限に Restart されてしまうという現象が確認できました（後ろにある MESSAGE には何かが書かれていそうだったのですが、一瞬で再起動してしまうため確認できていません）。

![キャプチャ](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/40717789/a30f3196-efd2-4388-a7b1-09b130c4dd14)

リリースから zip を取得して再実行したところ、起動直後のロード中に `mods/Steam/928606476/strings.po` が削除されてしまっていることが確認できました。
こちらの現象について心当たりや解消法等あれば教えていただきたいです。

以上よろしくお願いいたします。

**Comment by nsk4762jp** [comment]
報告どうもありがとうございます。初めて聞く現象ですね...。
`C:/Users/[ログインユーザー名]/AppData/LocalLow/Klei/Oxygen Not Included` フォルダに `Player.log` というファイルがあるはずなので、差し支えなければそれをこの Issue に貼り付けて頂けますか。
「PCのフォルダ構成見せたくなーい」という場合は `Player.log` ファイルの `Japanese Language Pack has...` で始まる行から `Loaded language from mod:` で終わる行をコピーしてここに貼り付けてください。

僕の環境だとこんな感じでした。

> [13:36:05.776] [1] [INFO] 	Japanese Language Pack has a mod.yaml with a staticID `nsk.ONI_JapaneseLanguagePack`, using that from now on.
> [13:36:05.777] [1] [INFO] Japanese Language Pack: Successfully loaded from path 'root' with content 'Translation'.
> [13:36:05.778] [1] [INFO] Using builtin mod system.
> [13:36:05.778] [1] [INFO] Loading mod content DLL [Japanese Font Patch:3135364297] (provides DLL)
> [13:36:05.779] [1] [INFO] Loading MOD dll: OniFontPatchJp.dll
> Fallback handler could not load library G:/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Mono/data-0000015D55A3CCA0.dll
> Fallback handler could not load library G:/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Mono/data-000001601DE28530.dll
> Fallback handler could not load library G:/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Mono/data-000001601F482D10.dll
> [13:36:06.398] [1] [INFO] Localization.Initialize!
> [13:36:06.398] [1] [INFO] Localization Initialize... Mod-based localization
> [13:36:06.439] [1] [INFO]  -> Locale is now  ja:Japanese:LeftToRight:NotoSansCJKjp-Regular
> [13:36:06.759] [1] [INFO] TRANSLATION ERROR! The following do not have the same amount of <link> tags as the english string which can cause nested link errors:
> 	STRINGS.BUILDINGS.PREFABS.TELEPORTALPAD.NAME
> 	STRINGS.BUILDINGS.PREFABS.DEVPUMPGAS.NAME
> 	STRINGS.BUILDINGS.PREFABS.DEVPUMPLIQUID.NAME
> 	STRINGS.BUILDINGS.PREFABS.COSMICRESEARCHCENTER.EFFECT
> 	STRINGS.BUILDINGS.PREFABS.DEVPUMPSOLID.NAME
> 	STRINGS.BUILDINGS.PREFABS.FACILITYBACKWALLWINDOW.NAME
> 	STRINGS.BUILDINGS.PREFABS.POIBUNKEREXTERIORDOOR.NAME
> 	STRINGS.BUILDINGS.PREFABS.POIDOORINTERNAL.NAME
> 	STRINGS.BUILDINGS.PREFABS.POIFACILITYDOOR.NAME
> 	STRINGS.BUILDINGS.PREFABS.LONELYMAILBOX.NAME
> 	STRINGS.ELEMENTS.CREATURE.DESC
> 	STRINGS.ELEMENTS.MOLTENNIOBIUM.DESC
> 	STRINGS.ELEMENTS.NIOBIUM.DESC
> 	STRINGS.ELEMENTS.NIOBIUMGAS.DESC
> 
> [13:36:06.790] [1] [INFO]  -> Loaded language from mod: 928606476
>

**Comment by oshiro3** [comment]
確認ありがとうございます！
ONI自体のログがそちらに出ていたのですね。

私の方でログを確認したのですが、ロードの際に onedrive と不整合を起こして削除されていたらしいということが分かりまして、該当ディレクトリの onedrive との連携を停止したところこの問題は解消されたことが確認できました！
おまかんの話でお騒がせしてしまい申し訳ありませんでしたとともに、解決に至ることができたのでありがとうございました。

こちらの Issue はクローズにさせて頂きます！

**Comment by nsk4762jp** [comment]
原因が解決できて何よりです。
OneDrive 絡みでのトラブルは前にもあったような気がするのでどこかにメモっておきます。
