### ISSUE TITLE
乾燥関連における Stuffed Berry の翻訳間違い

### ISSUE THREAD

**Issue by KoheiKanagu** [nsk4762jp/OxygenNotIncluded-Japanese#374]
`Stuffed Berry` の訳は `ベリーの香辛料詰め` ですが、
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/9a6ce04661cdd534e512288950dcdd12925c2674/po/items.po#L1035-L1038

乾燥関連の文章では `どろどろベリー` となっています
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/9a6ce04661cdd534e512288950dcdd12925c2674/po/items.po#L1008-L1024

<img width="995" alt="スクリーンショット 2024-07-01 22 20 42" src="https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/assets/6175794/c3f6398d-364f-4290-90c1-e208ce63818d">

**Comment by nsk4762jp** [comment]
どうもありがとうございます。
master ブランチの修正は完了しました。MOD本体も対応させます。
