### ISSUE TITLE
フレーバーテキスト(STRINGS.BUILDINGS.PREFABS.*.DESC)にあたる文章の口調

### ISSUE THREAD

**Issue by seameteo** [nsk4762jp/OxygenNotIncluded-Japanese#4]
施設の追加説明文(STRINGS.BUILDINGS.PREFABS.*.DESC)ですが、これはフレーバーテキストであり会話文を引用しているような文章ですので、敬体に統一する必要はないと思われます

**Comment by nsk4762jp** [comment]
ここだけ他の文章と違ってたので気になって変更してしまいました。また後で見直します。
