### ISSUE TITLE
翻訳Discordグループの作成について

### ISSUE THREAD

**Issue by seameteo** [nsk4762jp/OxygenNotIncluded-Japanese#6]
翻訳メンバーはWorkshopの公開などによって増えてくるかもしれません（今は2人ですが…）。そういった時に軽快な情報交換の場があると意思疎通がやりやすくなるでしょう。勿論Githubの機能でも情報交換が可能ですが、インスタントなやり取りができるような場所も欲しい所です。
そこで軽快なSMSサービスである Discord でグループサーバーを立ち上げようと思っているのですが如何でしょうか。

Discordには次のような特徴があります:
- 軽量です。
  - Skypeと違って重くなったりしません。
- URL を使えば簡単にサーバーに参加できます。
- チャンネル分けができます。
  - 翻訳話題用、誤訳報告用、プレイ話題用、その他雑談用、といったチャンネル分けが可能です。
- Webhook に対応しています。
  - GithubでプッシュされたらDiscordで通知、という使い方が可能です。

**Comment by nsk4762jp** [comment]
いいですね。

ただ、同じ Klei のゲームである Invisible, Inc. を日本語化していたときの翻訳メンバーは結局僕一人だったのと、翻訳に参加してみたい人が皆 Discord アカウントを持っているわけではないところがちょっと気になります。
Steam アカウントなら皆持ってるはずなので Steam 上でユーザーグループを作って、そこを足場にするのも手だと思います。
翻訳についての話題は Workshop の日本語化MODにも該当スレッドを立ち上げておきました。

まあ、いずれにせよ、もう一人増えてから考えても遅くはないと思いますよ。

**Comment by seameteo** [comment]
そうですね、誤訳報告等はSteam掲示板でも間に合わせることは可能ですし、まだ翻訳者は少ないので今すぐ必要とは言えないでしょう。
Discordアカウント所持の有無に関しては登録が実質不要（しておいたほうが良い程度）なのであまり考えていませんでしたが、まだ認知度が低いアプリであることが問題です。

今はこのままで問題ないですし、必要になったら思い出す程度ですね。
