### ISSUE TITLE
【ディスカッション】原文から意味が離れているものを修正したい

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#60]
主に食料と動物の翻訳について英語での意味と離れているものについて名称を変更したい。
すでに定着してしまっているものもあるので、今更変えられるのかという問題もありますが、それも含めてディスカッションしたい。
言葉遊び的、皮肉を含む言葉が多いのでいろいろな角度から検討してみたいのでご意見いただければと思います。
いろいろと辞書上の意味や元ネタを漁りましたが、全体にロクなもんじゃないことがわかりました。これは難しいやつだ。

優先して修正したいものとしては以下のものです。
- Gristle Berry → ~グリルベリー~ ごりごりベリー
- Stuffed Berry → ~ベリーの香草焼き~ ベリーの香辛料詰め
- Royal Bug → ~豪華 バグ~ ロイヤル バグ
- Sage Hatch → ~もさもさ ハッチ~ セイジ ハッチ
- Gassy Moo → ~ふわぷか モー~ ぷすぷす モー

特に翻訳が難しいと考えているのは以下のものです。ご意見ください。
- Mush Bar → マッシュバー
- Meal Lice → ミールライス
- Bristle Berry → ブリッスルベリー
- Raw Egg → 生卵
- Dense Puft → ごつごつ パフ

コメントで補足入れます。

**Comment by souki-tn** [comment]
- 食料
  - Nutrient Bar → 栄養バー
    - 問題なし。美味しくなさそうな印象も素晴らしい。
  - Muckroot → ムックルート
    - 英語ではドロドロの汚い根っこという意味になるようですが、どのみち正体不明の謎食品らしいのでカタカナの音表記で良いと思います。
  - Meat → 肉
    - 問題なし。
  - Mush Bar → マッシュバー
    - マッシュポテトなど日本語にもなっているマッシュは `mash` なので別物。
    - 適訳があれば変更したいところ。直訳なら「泥棒」だと別の意味になるので「泥バー」正直微妙。「マッシュバー」でも良いと思う。
    - 「ぐずぐずバー」とかにすればニュアンスは近いものになりそう。
  - Mush Fry → マッシュフライ
    - 原文も正体不明な感じの食品なのでこれでOKだと思います。Mush Barの方が変わった場合合わせて変える。
  - Meal Lice → ミールライス
    - RiceではなくLiceなのでこのシャレが伝わるものがあれば変更したい(が、難しそう)。「ミール虱」にしてしまうと今度は米っぽいというシャレが伝わらないので候補としては「ムシゴメ」とかにすると危険な感じがして良いです。
    - 前提としてミールワームを連想するというのがあるのだと思います。ミールワームを日本語ではミールワーム以外にならないので難しい。
    - このゲームのユーザーにはミールライスで定着していそうな気がしますので変更なしがいいかもしれません。
  - Liceloaf → ライスローフ
    - ミートローフは日本語でもメニューとして通じるので、ライスをそれっぽく固めたものという意味で通じると思います。
  - Pickled Meal → ピクルス
    - 日本語に訳す段階で `Meal` の意味が抜け落ちてますが、これは省略でも良いかなと考えています。Meal自体「食事」ぐらいの意味しかないので。
  - Bristle Berry → ブリッスルベリー
    - `Bristle` の意味が「毛が逆立つ」「人がいらだつ」という意味なので、トゲがあって食べようとすると刺さるからイライラするというネーミングなのだと思います。
    - 栗のような形状が予想されるので、「イガベリー」「イガイガベリー」あたりに変更してもいいのではないでしょうか。
  - Gristle Berry → グリルベリー
    - 焼いて作ったとは説明にありますが「グリル」という名前がつくのは原文と照らし合わせておかしいです。`Gristle` は軟骨という意味ですが辞書では＜通常食べられない部分＞と明記されているのでひどい食事なようです。
    - 軟骨で食べるのには食べるには硬すぎるということで「ごりごりベリー」という訳を推します。
  - Berry Sludge → どろどろベリー
    - `Sludge` は汚泥とかぬかるみという意味なので、「どろどろベリー」は適訳だと思います。
  - Stuffed Berry → ベリーの香草焼き
    - 「香草焼き」では少なくともなさそうです。 `Stuffed Fruit` で検索するとそれっぽい画像が出てきます。
    - 定訳がある同類のものでは `Stuffed Peppers` が「ピーマンの肉詰め or 肉詰めピーマン」になります。
    - 「ベリーの香辛料詰め」あたりが一番意味が近いのではないかと思います。
  - Mushroom → キノコ
    - 問題なし。
  - Fried Mushroom → 焼きキノコ
    - 問題なし。
  - Frost Bun → フロストバンズ
    - Bunが「バン」なのか「パン」なのかが問題になりますが、日本語ではBreadからBunまで全部「パン」と呼ぶのが一般的なので「パン」で良いのではないかとおもいます。
    - 日本でBunを「バン」と呼ぶ代表格はバーガー業界で、頑なに「バンズ」と呼んでますが、それ以外で見かけないと思います。
    - そんなわけで「フロストパン」を推します。
  - Pepper Bread → ペッパーブレッド
    - 問題なし。ジンジャーブレッドやガーリックブレッドは日本語でも一般的。
  - Omelette → オムレツ
    - 問題なし。アメリカ英語でないと強調できれば面白そうだが、難しい。
  - Barbeque → BBQ
    - 英語の側でも省略語になってないのでカタカナで「バーベキュー」でもいいかなと思います。
  - Pincha Peppernut → ピンチャペッパー
    - あえて `nut` の意味を落とす必要もないと思うので「ピンチャペッパーナッツ」に変えたほうがいいと思います。
    - ちなみに `Pincha` はヨガの逆立ちのポーズであるらしく、逆さに生える性質を表している模様。カタカナの書き下しも「ピンチャ」です。
  - Sleet Wheat Grain → スリートウィートの穀粒
    - 脱穀作業もありませんし `Grain` を「種もみ」と訳したほうが世紀末感が出る気がします。「穀粒」でもわかることはわかるので問題ないとも思います。
  - Raw Egg → 生卵
    - これは翻訳が難しい。通常日本語で「生卵」と言ったら「ゆで卵」の反対で生で割ってない卵のイメージになると思います。
    - 「卵の中身」や「割った卵」と意訳したほうがゲームメカニズムに沿ってくると思います。

**Comment by souki-tn** [comment]
- 動物
  - Shine Bugs
    - Shine Bug → シャインバグ
      - 問題なし。
    - Sun Bug → 太陽 バグ
      - 問題なし。
    - Royal Bug → 豪華 バグ
      - `Royal` を「豪華」と訳すのはいささか問題があるように思います。直訳で「王室」や「王族」と訳すのはおかしくなるので「ロイヤル」とカタカナにしてしまった方がいいと思います。
    - Coral Bug → 珊瑚 バグ
      - 問題なし。
    - Azure Bug → 空色 バグ
      - 空色でも間違ってませんが変種の名前は全て色名ではなく、それと紐づくもの名前が付いているので統一感という意味で「青空バグ」の方が妥当な翻訳だと思います。
    - Abyss Bug → 深淵 バグ
      - 「深淵」と訳すと他と並べた時浮く感じがするので「アビス バグ」とカタカナにしても良いのではないかと思います。
    - Radiant Bug → 輝き バグ
      - 「輝き」では `shine` と何が違うかわからない状態になるので「きらめき」や「キラキラ」に変更したい。少なくとも最高級な感じにした。ただ、きらめきやキラキラがやや安っぽいのが気になります。Dupe相手だし十分と考えてもいいですが。
  - Hatches
    - Hatch → ハッチ
      - 何を元ネタに `Hatch` と名付けたのか正直わからないのでカタカナで「ハッチ」以外に思いつかない。
    - Stone Hatch → いしころ ハッチ
      - 「ストーン」とカタカナ表記にしても良いかもしれない。
      - `Stone` には `Rock` に比べて小さいというニュサンスはないので、いしころと言ってしまうと小さすぎるイメージかもしれない。
      - つるつると対応づけるならば「ごつごつ」を使うのも良いと思います。
    - Sage Hatch → もさもさ ハッチ
      - `Sage` にはもさもさ要素はなく「賢い」や「思慮深い」などの意味で、「賢人ハッチ」「聖人ハッチ」あたりが直訳としては正しいです。
      - デザインを見るに `Sage` の意味として他にあるハーブの方のセージとも掛けてあると思われるので「セージ ハッチ」とカタカナにしてしまった方がいい気がします。
      - セージをベースに聖人っぽい書き方にして「セイジ ハッチ」という訳を推します。
    - Smooth Hatch → つるつる ハッチ
      - 問題なし。
  - Pufts
    - Puft → パフ
      - これはカタカナにするしかないやつだと思います。 `Puft` で検索するとゴーストバスターズのマシュマロマンしか出てこない。ふわふわしたもののイメージだと思います。
    - Puft Prince → パフ プリンス
      - パフ プリンスはパフ プリンスで。
    - Dense Puft → ごつごつ パフ
      - `Dense` は「濃い」「密度が高い」「理解が遅い」という意味になるので「ごつごつ」は適さないと思います。訳すなら「こってり パフ」あたりで。「ごつごつ」を使うなら `Stone` 相手に使いたい
    - Squeaky Puft → やかまし パフ
      - 問題なし。ですがドアの金具が軋むような音を指すらしいので他と合わせて「きいきい パフ」でもいいかもしれません。
  - Slicksters
    - Slickster → スリックスター
      - カタカナにしておくのが妥当。
    - Molten Slickster → とろける スリックスター
      - とろけるで正しいですが、他の動物の変種の名前から「とろとろ」の方が良いと思います。
    - Longhair Slickster → ふさふさ スリックスター
      - 問題なし。
  - Dreckos
    - Drecko → ドレッコ
      - ググっても情報が類似語が見当たらないので、カタカナにしておくのが妥当。
    - Glossy Drecko → つやつや ドレッコ
      - 意味として幅がないので正しいだと思います。
  - Pacus
    - Pacu → パクー
      - 南米の魚が元ネタだと思われるので「パクー」でOK。別名「ボールカッター」「睾丸食い魚」らしい。いい元ネタだな。
    - Tropical Pacu → 熱帯パクー
      - 問題なし。
    - Gulp Fish → ガルプフィッシュ
      - `Gulp` はごくごく飲み込むという感じの意味なので「がぶ飲み魚」「ごくごくフィッシュ」などに変更した方が今の翻訳のテイストには合うと思います。
  - Moos
    - Gassy Moo → ふわぷか モー
      - `Gassy` は風船のように膨らんでいるイメージらしいので「ふわぷか」の「ふわ」は適さないと思います。むしろパツパツな感じ。
      - 「ぷくぷく モー」あたりが膨らんでいるイメージとしてはいいと思います。ただ当然 `Gassy` はお腹が `Gassy` なのも指すので「ぷすぷす モー」がいいかもしれません。
  - Voles
    - Shove Vole → 掘りネズミ
      - `Shove` は掘るというよりも埋めなので、訳すなら「埋めネズミ」。
      - イメージとしては無理やりねじ込む/突っ込むという感じなので「ぐいぐいネズミ」「ぐりぐりネズミ」ぐらいにしたいです。
      - タイルを貫通して移動する性質からだと思います。
  - Morbs
    - Morb → モーブ
      - 造語っぽいので「モーブ」で問題なし。 `Morbid` あたりから作った言葉だと思います。

**Comment by nsk4762jp** [comment]
提案どうもありがとうございます。  
翻訳時に苦労したところが大体カバーされているので助かります。:sweat_smile:  

優先度の高いものについて、まずはどうしてその訳語になったかの経緯を説明しておこうと思います。

- Gristle Berry (グリルベリー)  
Bristle Berry (ブリッスルベリー)を調理すると Gristle Berry になるので、原文の音遊びに合わせています。グリッスルベリーにしなかったのは、「どっちがどっちか分かりづらい」のと、「似た音の"グリル"のほうが焼いたものであるということが分かりやすい」だろうと思った次第です。  
「ごりごりベリー」にするのであれば、Bristle Berry のほうも見直したいと思います。  
- Stuffed Berry (ベリーの香草焼き)  
これはどう訳したものか途方に暮れたものの一つなので、香辛料詰めのほうを推したいです。
- Royal Bug (豪華 バグ)、Sage Hatch (もさもさ ハッチ)  
動物の亜種の訳語については、そのまま音訳すると意味が伝わりづらいものもあったので、思い切って見た目から適当に造語した訳を当てはめています。完全に個人の好みです。  
訳語の統一感を出したいので、一部の亜種だけ音訳にするのはできれば避けたいです。
- Gassy Moo (ふわぷか モー)  
当時 MonsterHunter World をプレイしていて、ゲーム中の「ふわぷか パオウルムー」というクエスト名から借用しています。  
動いている現物をまだ見ていないので、「ふわぷか」ほど優雅でないのであれば「ぷすぷす モー」が良いと思います。

残りの分についても追ってコメントしたいと思います。

**Comment by souki-tn** [comment]
コメントありがとうございます。

`Gristle Berry` についてはなるほどと思いました。横のつながりはそこまで意識してなかったのですが `Bristle Berry` との言葉遊びなのは間違いないですね。
そうすると「こりごりベリー」を焼くと「ごりごりベリー」になるとかそういう対応が必要ですね。
「こりごり」と「ごりごり」ではゲーム内で表示した時に潰れて判別できなくなるかもしれないので何か考えてみます。

動物の亜種の語感をそろえるのであれば「ガルプフィッシュ」はどうにかしたいですね。
`Royal` についてはロイヤルストレートフラッシュやロイヤルファミリーという言い方で日本語に定着しているので「ロイヤル」でもいいと思いますが、漢字にするなら「高貴」あたりでしょうか。
`Sage` は、このゲームの言葉には珍しくポジティブな意味の強い言葉です。それに対して「もさもさ」はネガティブ寄りすぎかなと考えてます。 `Sage Hatch` は優秀な子とわかる翻訳を考えたいです。

`Gassy Moo` は草を食べて天然ガスを出す動物なのでDupesの特性の「屁こき虫」と似たものです。お腹がGassyなのは間違いないと思います。 `Gassy` は比較的ネガティブ寄りの言葉のようなので優雅に訳すのはどうかなとおもいます。

**Comment by souki-tn** [comment]
いろいろ考えてみましたが、今のところベストだと思えた組み合わせができました。もう少し考えてみますが、これはいかがでしょう。
- Bristle Blossom → とげばりブロッサム
- Bristle Berry → とげばりベリー
- Gristle Berry → すじばりベリー
`Bristle` から「とげばり」は意味が遠目で、 `Gristle` から「すじばり」は意味が近くなってます。
意味の遠近は逆の方がいいとは思うのですが、説明文から照らし合わせてこれでも良いかなと思っています。

**Comment by nsk4762jp** [comment]
- Nutrient Bar → 栄養バー
- Muckroot → ムックルート
- Meat
- Mush Bar → マッシュバー
- Mush Fry → マッシュフライ
- Meal Lice → ミールライス
- Liceloaf → ライスローフ
- Pickled Meal → ピクルス
- Bristle Berry → ブリッスルベリー  
> Bristle の意味が「毛が逆立つ」「人がいらだつ」という意味なので、トゲがあって食べようとすると刺さるからイライラするというネーミングなのだと思います。  
> 栗のような形状が予想されるので、「イガベリー」「イガイガベリー」あたりに変更してもいいのではないでしょうか。  

「逆立つ」「イライラする」という語感から、両方に使える「ささくれ」を思いつきました。  
この言葉は爪の根本にできるアレ以外にも「木材や竹などが部分的に毛羽立った状態を指す、またはそのようなさま」という意味もあるらしいので、「ささくれ ベリー」も案の一つとして挙げておきます。
- Gristle Berry → グリルベリー  
> 焼いて作ったとは説明にありますが「グリル」という名前がつくのは原文と照らし合わせておかしいです。Gristle は軟骨という意味ですが辞書では＜通常食べられない部分＞と明記されているのでひどい食事なようです。  
> 軟骨で食べるのには食べるには硬すぎるということで「ごりごりベリー」という訳を推します。  

Gristle Berry の説明を読むととても美味いらしいので、軟骨のニュアンスを出した「こりこり ベリー」か、硬いものを食べるときの「ボリボリ ベリー」なども案として挙げたいと思います。
- Berry Sludge → どろどろベリー
- Stuffed Berry → ベリーの香草焼き  
「ベリーの香辛料詰め」
- Mushroom → キノコ
- Fried Mushroom → 焼きキノコ
- Frost Bun → フロストバンズ  
「フロストパン」または「ひんやりパン」
- Pepper Bread → ペッパーブレッド
- Omelette → オムレツ
- Barbeque → BBQ  
「バーベキュー」で良いと思います。
- Pincha Peppernut → ピンチャペッパー  
> あえて nut の意味を落とす必要もないと思うので「ピンチャペッパーナッツ」に変えたほうがいいと思います。  

UIの表示の都合上、省略しても意味が通るものについてはできるだけ省略しています。  
(2バイト文字で長い名前にしてしまうとUIが崩れる)
- Sleet Wheat Grain → スリートウィートの穀粒  
> 脱穀作業もありませんし Grain を「種もみ」と訳したほうが世紀末感が出る気がします。「穀粒」でもわかることはわかるので問題ないとも思います。  

麦の粒なので、「麦粒(ばくりゅう)」にしようかと思いましたが、ものもらい(麦粒腫)が検索上位に来てしまったので「穀粒」のままにしたいと思います。  
- Raw Egg → 生卵  
「卵の中身」でいきましょう。

**Comment by nsk4762jp** [comment]
- Shine Bug → シャインバグ
- Sun Bug → 太陽 バグ
- Royal Bug → 豪華 バグ
「ロイヤル バグ」案で良いと思います。
- Coral Bug → 珊瑚 バグ
- Azure Bug → 空色 バグ
「青空バグ」案で良いと思います。
- Abyss Bug → 深淵 バグ
「アビス バグ」
- Radiant Bug → 輝き バグ
きらめきを漢字で書いて「煌き バグ」にしますかね。
- Hatch → ハッチ
- Stone Hatch → いしころ ハッチ
こちらを「ごつごつ ハッチ」に変更し、ごつごつ パフのほうを「こってり パフ」の案が良いと思います。
- Sage Hatch → もさもさ ハッチ
> Sage にはもさもさ要素はなく「賢い」や「思慮深い」などの意味で、「賢人ハッチ」「聖人ハッチ」あたりが直訳としては正しいです。
> デザインを見るに Sage の意味として他にあるハーブの方のセージとも掛けてあると思われるので「セージ ハッチ」とカタカナにしてしまった方がいい気がします。
> セージをベースに聖人っぽい書き方にして「セイジ ハッチ」という訳を推します。

これも翻訳時に「賢人 ハッチ」にすることも考えたんですが、他のと訳語が揃わないので敢えて外した訳語にしています。  
「セージ(セイジ)」で他の人がすぐ分かるのであれば「セイジ ハッチ」で良いと思います。  
- Smooth Hatch → つるつる ハッチ
- Puft → パフ
- Puft Prince → パフ プリンス
- Dense Puft → ごつごつ パフ
「こってり パフ」
- Squeaky Puft → やかまし パフ
- Slickster → スリックスター
- Molten Slickster → とろける スリックスター
「とろとろ スリックスター」
- Longhair Slickster → ふさふさ スリックスター
- Drecko → ドレッコ
> ググっても情報が類似語が見当たらないので、カタカナにしておくのが妥当。  

これは Drake + Gecko のかばん語だと思います。
- Glossy Drecko → つやつや ドレッコ
- Pacu → パクー
> 南米の魚が元ネタだと思われるので「パクー」でOK。別名「ボールカッター」「睾丸食い魚」らしい。いい元ネタだな。  

発音は「パク」らしいんですが、パフと区別しづらいので長音記号を加えてみました。
- Tropical Pacu → 熱帯パクー
- Gulp Fish → ガルプフィッシュ
> Gulp はごくごく飲み込むという感じの意味なので「がぶ飲み魚」「ごくごくフィッシュ」などに変更した方が今の翻訳のテイストには合うと思います。

二つ合わせた「がぶ飲み フィッシュ」とかはどうでしょう。
- Gassy Moo → ふわぷか モー
「ぷすぷす モー」
- Shove Vole → 掘りネズミ
「ぐりぐりネズミ」
- Morb → モーブ

**Comment by souki-tn** [comment]
細かいところの検討も含めて第三者の意見を聞いてみたいですね。ここで二人で練りましたというのは限界が何処かにある気がします。
だれかコメント書かないかなと待ってたんですけどね。

継続検討という感じになっている `Bristle Brossome` 関連ですが、個人的に `Bristle Berry` というもの自体が美味しいのかと言われるとそうでもないんじゃないかと思っています。
フロストパンのレシピにピンジャペッパー1kg追加で、4000kcalの「ペッパーブレッド」(品質+5)になるわけですが、`Gristle Berry` *2 にピンジャペッパー2kgでやっと4000kcalの「ベリーの香辛料詰」(品質+4)なので、香辛料が多いにも関わらず美味しくならない微妙なものという感じだと思ってます。

説明文の方も `leave something to be desired` は辞書的には「いまひとつ物足りない、ちょっとあれだ〔不満が残る〕」という意味なので
`Heat unlocked an exquisite taste in the fruit, though the burnt spines leave something to be desired.`
→焦げたトゲはいまひとつ不満があるものの、熱によって絶妙な味わいを引き出しました。
という感じだと思います。to不定詞はこの先得るもの、今はまだ無いものという意味合いがあるはずなので、この場合不満じゃーって意味なんですよね。英語って難しい。
絶妙な味わいと言っているのでどちらかというと珍味系の表現でしょうかね。

そんなわけで「こりこり」「ぼりぼり」は美味しそうすぎる気がします。
`Bristle Berry` を「ささくれベリー」にするのはとてもいい訳だと思うのでそれとセットで `Gristle Berry` には「ふしくれベリー」か「いしくれベリー」あたりを考えました。
英語の意味はガン無視ですが、美味しくなさそうでかつ、言葉が似てる言葉です。これに関しては言葉遊び優先でいいと思います。

**Comment by nsk4762jp** [comment]
Groom: 「手入れ」→「毛づくろい」 or 「ブラッシング」 or 「世話」

**Comment by nsk4762jp** [comment]
他の方から指摘がありましたが、Launch Upgradeで追加された Pinch Roe (Pokeshell の卵) を「窮屈な卵」と訳すことについて。

- Pinch は(Pokeshellの持つハサミの)摘まむ、と掛けているのではないか。
- Roe は魚卵を指すので (窮屈な) 魚卵 になるのではないか。

Pokeshell はどうみても魚ではないので、魚卵にはならないだろうと思ってただの卵にしています。

**Comment by souki-tn** [comment]
辞書的には `cod roe` で「鱈子、タラ子」、 `Herring roe` で「数の子」 、 `crab roe` で「カニみそ」らしいので「ハサミの子」とかでもいいかもしれないですね。

**Comment by nsk4762jp** [comment]
おー、確かにそれっぽくていい感じですね！ 😃

**Comment by nsk4762jp** [comment]
LLturnさん曰く:

> 翻訳提案です
> ・きのこのレタス巻き→きのこのレタス包み
> 巻きだと巻き寿司みたいな形状を連想するのと、アイテム画像の印象から包みを推したいです
> ・ベリーの香辛料詰め→ベリーの印籠詰め
> 馴染みないですが、くり抜いて詰める料理は印籠というらしいです。香辛料詰めは料理のイメージがわかなかったので変更提案
> ・セイジハッチ→もさもさハッチ
> 見た目が毛だらけで世俗に関心のない仙人の伸びっぱなしの髪やヒゲを揶揄してのsageだと思うので、和訳も見た目から入って以前のもさもさに戻して他の亜種と統一感が欲しいです

**Comment by nsk4762jp** [comment]
「ハサミの子」、「きのこのレタス包み」を採用しました。

「ベリーの印籠詰め」「もさもさハッチ」については保留とします。
理由: stuffed berry は「ピーマンの肉詰め」のように縦に半分に割ったものに香辛料を詰め込んだもので、袋状のものに詰め込むタイプの印籠詰めとはちょっと感じが違うため。もさもさハッチについてはもう少し他の人の意見を聞いてから判断したいと思います。

**Comment by souki-tn** [comment]
個人的にもさもさについては語呂的にもさもさも好きなんですが、もさもさのイメージは仙人みたいなヒゲのイメージではなく、ハーブの方のSageが生えてるイメージだと思ってます。まぁ、この会社がそんなストレートなイメージでモノ作ってるとは思えませんけど。ネタがわかりにくいよという話はその通りだなと思います。
「印籠詰」についてはイカの腹に詰めるもの以外にはほとんど使わないと思っています。ネットで漁っていたらサツマイモに詰めるものはありましたが、イカの腹にご飯を詰めてゲソを添えて紐っぽく見せることで印籠と言っているようです。イメージとしてやや遠いのではないいでしょうか。
「stuffed peppers」が元にあって、外身と中身が逆転してるというネタなんだと思います。外がpepperではなく中身がpincha pepperで文字通り辛かったらというifの食べ物をなのだと思います。なので、私としては「香辛料詰め」を強く推したいです。

**Comment by nsk4762jp** [comment]
このチケットも長らく新規提案が無いので一旦クローズとします。
