### ISSUE TITLE
翻訳の未反映部分の修正

### ISSUE THREAD

**Issue by kankoromochi** [nsk4762jp/OxygenNotIncluded-Japanese#66]
プレイしてみましたところ、どうも私のプルリクエストのやり方がまずかったのか、私の行った部分の翻訳が一部反映されていないようです。なにかお心当たりありますでしょうか…。

**Comment by nsk4762jp** [comment]
Github 上の [strings.po](https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/master/strings.po) を確認してみてください。  
ここの strings.po がOKだったら、PC上のstrings.poファイルが更新できてないかもしれません。NG だった場合は僕がマージした時に元に戻しちゃった可能性があります...

**Comment by kankoromochi** [comment]
確認してみましたが、OKでした…いわゆる「おま環」で、ローカル消して再インストールしたらきちんと反映されました…真っ先に確認すべきでした。お騒がせしまして申し訳ありません。
あまりにも不慣れなもので自分が何かやらかしたかと思って焦って書き込んでしまいました。恥ずかしすぎますのでこれにて閉めさせていただきます…
