### ISSUE TITLE
翻訳ファイルを導入すると設定の「コントロール」でフリーズする

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#7]
日本語化した strings.po を導入して、ゲームの設定画面から「コントロール」を選択するとゲームがフリーズする。
デフォルトのままだとフリーズしないので、翻訳した STRINGS.INPUT.* または STRINGS.INPUT_BINDINGS.* が悪さをしているのかもしれない。

**Comment by nsk4762jp** [comment]
STRINGS.INPUT.* の翻訳文を原文と同じにして確認したが、結果は変わらず。

**Comment by seameteo** [comment]
INPUT_BINDINGS.ROOT.* を po ファイルから完全に削除したところ、正常に設定画面を開くことができました。
プルリクエストに該当コンテキストを削除したコミットを入れておきますが、削除前の状態をこちらのforkプロジェクトのsub-inputsブランチとして残しておきます。

**Comment by nsk4762jp** [comment]
Oil Upgradeで当事象が再現するようになったため再開

**Comment by nsk4762jp** [comment]
INPUT_BINDINGS.ROOT.* を全てコメントアウトしてみたが、事象は変わらず。

**Comment by nsk4762jp** [comment]
Rocketry upgrade で確認したところ修正されているようなのでクローズします。
