### ISSUE TITLE
製造ポッド→コロニー概要を開くとゲームがクラッシュする

### ISSUE THREAD

**Issue by shohei918** [nsk4762jp/OxygenNotIncluded-Japanese#73]
製造ポッド→コロニー概要を開くとゲームがクラッシュします。
以前のバージョンのstrings.poでは問題無かったので、差分を取りながら確認した所、
STRINGS.UI.RETIRED_COLONY_INFO_SCREEN.STATS 以下のテキストが翻訳されているとクラッシュするようです。

**Comment by nsk4762jp** [comment]
ありがとうございます。  
こちらでも現象を確認しました。当面は STRINGS.UI.RETIRED_COLONY_INFO_SCREEN.STATS を抜いて提供することにします。

**Comment by nsk4762jp** [comment]
hotfix で修正したものを取り込んだら、落ちなくなりました。謎ですね...。
とりあえずこの issue は一旦クローズします。
