### ISSUE TITLE
物質の状態を表す訳語について

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/OxygenNotIncluded-Japanese#85]
Aliisa さん曰く

> msgid "The selected object will cool into a solid at {0}"
> msgstr "選択した物体は {0} で固体に凍結します"
> の部分ですが、ここは凍結ではなく凝固の方が良いと思います。
> （ただ「固体に凝固します」というのも重複表現で変なんですけど、
> 「凝固します」だけにすると、液化・気化のも修正しないと統一性がなくなる？）

[物質の状態 - Wikipedia](https://ja.wikipedia.org/wiki/%E7%89%A9%E8%B3%AA%E3%81%AE%E7%8A%B6%E6%85%8B) の記述に合わせたほうが良いかも。

**Comment by tailriver** [comment]
「（固体・液体・気体）に変化します」はいかがでしょうか。
関連して、 vaporization point は直訳すると確かに「蒸発点」ですが、「沸点」の方が適切かもしれません。

ただ、これらのテキストは原油（液体） → 石油（液体）などにも使われているので、あまりこだわっても仕方ないかも、とも思います。

**Comment by nsk4762jp** [comment]
該当する箇所はこの4つだけみたいですね。

気体 → 液体への状態変化(凝縮・液化・凝結・結露)
> The selected object will condense into a liquid at {0}
> 選択した物体は {0} で液体に凝縮します

液体 → 固体への状態変化(凝固・固化)
> The selected object will cool into a solid at {0}
> 選択した物体は {0} で固体に凍結します

固体 → 液体への状態変化(融解)
> The selected object will melt into a liquid at {0}
> 選択した物体は {0} で液体に融解します

液体 → 気体への状態変化(蒸発・気化)
> The selected object will evaporate into a gas at {0}
> 選択した物体は{0}で気体に蒸発します

液体→固体だけ用語から外れているようなので、ここだけ直すのが無難でしょうか。

**Comment by nsk4762jp** [comment]
とりあえず指摘通り 「固体に凝固します」 に修正しました。  
これで一旦クローズとします。
