### ISSUE TITLE
過去のPRの内容が一部消えているようです

### ISSUE THREAD

**Issue by souki-tn** [nsk4762jp/OxygenNotIncluded-Japanese#93]
@nsk4762jp 
以前取り込んでいただいたこちらの内容がゲームから消えてしまっているようです。
他にもありそうなので整理して再度PRを作らせていただいてよろしいでしょうか？
PRの出し方が悪かったかもしれないと思っております。

サンプル
Anemicの翻訳と説明がゲーム内の内容とずれていたので修正しました
https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/pull/61

**Comment by nsk4762jp** [comment]
よろしくお願いします。週末にレビューして取り込みます。

**Comment by nsk4762jp** [comment]
どうもありがとうございました。masterブランチに取り込んだのでこのissueはクローズします。
