### ISSUE TITLE
意味が逆になっている特性がありそう

### ISSUE THREAD

**Issue by yamashush** [nsk4762jp/OxygenNotIncluded-Japanese#97]
- `底なし胃袋` -> `カロリーが減少`
- `腸過敏` -> `トイレ利用速度が減少`

![Screen Shot 2020-07-06 at 10 06 50](https://user-images.githubusercontent.com/38120991/86546633-e5bf8e00-bf70-11ea-858e-90beb867b045.png)

このあたりで定義されている文言は使われていなかったです。
単語の組合わせで表現されるようなアップデートでも入ったのでしょうか 🤔 
何もわからないけどとりあえず Issue を作ってみます 🙏 

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/duplicants.po#L10416

**Comment by yamashush** [comment]
あ、すいません、利用速度減少＝トイレが長くなるなので合ってました 🙇

**Comment by yamashush** [comment]
![Screen Shot 2020-07-06 at 10 25 25](https://user-images.githubusercontent.com/38120991/86547267-6089a880-bf73-11ea-9868-8dbc6f07311b.png)

底なし胃袋は逆かもしれません。

**Comment by nsk4762jp** [comment]
@yamashush さん

どうもありがとうございます。原文を当たってみます。

**Comment by nsk4762jp** [comment]
原文を当たってみました。

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/ui.po#L1611-L1614

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/duplicants.po#L139-L151

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/duplicants.po#L10173-L10181

個々の訳語としては合ってるっぽいですけど、「カロリーが減少」だと分かりづらいのは否めませんね。  
消費するカロリーが他人より多いというニュアンスを「減少」という言葉と上手く組み合わせる必要がありそうです。

**Comment by yamashush** [comment]
わー、ありがとうございます 🙏 🙏 🙏

**Comment by yamashush** [comment]
なるほど、この2つの汎用的に利用される言葉が使われているのでなかなか難しそうですね 😭 

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/ui.po#L1844-L1847

https://github.com/nsk4762jp/OxygenNotIncluded-Japanese/blob/469358a69ab855cd77dbf18ff93074d6e8ad4304/po/ui.po#L1611-L1614

**Comment by yamashush** [comment]
`保有カロリー` とかをあてればここの説明はいけそうですが `カロリー` が他にどこで使われているか全体が見えてなくて、他が破綻しそうな気がします…

**Comment by nsk4762jp** [comment]
`STRINGS.DUPLICANTS.ATTRIBUTES.CALORIESDELTA.NAME` は `STRINGS.DUPLICANTS.ATTRIBUTES.CALORIESDELTA.DESC` でのみ使われているテキストに見えます。
`STRINGS.DUPLICANTS.ATTRIBUTES.CALORIESDELTA.DESC` は今のところ `底なし胃袋` の説明のみに用いられているように見えるので、`STRINGS.DUPLICANTS.ATTRIBUTES.CALORIESDELTA.NAME` の `カロリー` を変更すれば解決するような気がします。

説明文から考えると、`保有カロリー` or `カロリー収支` が妥当かなと思いますがどうでしょうか。

**Comment by nsk4762jp** [comment]
プルリクを取り込んだのでこちらの issue はクローズしておきますね。
